### ISSUE TITLE
FoxPro THIS keyword

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#10]

**Comment by RobertvanderHulst** [comment]
Moved to X-Sharp/XSharpDev#6

**Comment by JohanNel** [comment]
Robert,
Sorry for this late response to this issue.  Matt or another VFP users might need to enlighten us.  As far as I know VFP also use BASE and not SUPER, so thought it should just be clarified.

**Comment by RobertvanderHulst** [comment]
Johan,
As far as I understand there is no BASE or SUPER concept in FoxPro. You never call methods on the base class directly. They are automatically called, unless you include the NODEFAULT command in the code of your method or event handler.

**Comment by JohanNel** [comment]
Hi Robert,
Thanks, found this on a VFP to .NET site, so include it for completeness.  Matt can maybe comment if we missing something.

Extending inherited methods
More often than not, you extend rather than completely override an inherited method. In Visual FoxPro you accomplish this by placing code in a method, then issuing a DODEFAULT command. You can run DODEFAULT first, before executing your subclass code, or you can run your code first, and then issue a DODEFAULT.

**Comment by mattslay** [comment]
If you override a method on a class, the code in the parent class does *not* happen automatically, you must explicitly make the call.

To do this, you use the function to default and you must pass any required parameters.

<<Maybe some of my code here ...>>

DoDefault(Param1, Param2, ...)

<<Maybe more of my code here>>>



Also,  because there could be multiple inheritance going on, instead of DoDefault() you can make a call to a method on a specific class in the hierarchy stack:

ClassBlah::MethodName(Param1, Param2,...)

**Comment by RobertvanderHulst** [comment]
Matt, I got that. I may have not expressed myself very clear. But in any case, there is no BASE or SUPER keyword involved. You either call DoDefault(p1, p2, p3) (Which would be SUPER:Foo(p1, p2, p3) in other dialects if the current method is Foo().
What exactly does ClassBlah::MethodName do, if you would write it in C# terms. Something like 
((ClassBlah) this).MethodName(Param1, Param2,...) ?
If MethodName() is virtual, that would still call the Method in the current class in most languages.

**Comment by RobertvanderHulst** [comment]
And what do you mean with "Multiple Inheritance", GrandFather, Father, Son ?

**Comment by mattslay** [comment]
Yes, by “multiple inheritance”, I meant GrandFather, Father, Son, but I also know that is not what “multiple hesitance” really is. I just wasn’t sure what else to call it. 

So, if B inherits from A, and C inherits from B, then in C one can call A::MethodName() and it would skip right over the code in that method on class B.

**Comment by JohanNel** [comment]
Matt,
So Super.Super.MethodName() if I read correctly or base.base.MethodName()?

**Comment by mattslay** [comment]
Johan - I guess you could state it that way, but he important part of this is the part where it is literately skipping code in the Super class, and diving back into the call stack it some lower level, and then resuming the call stack path from that point. 

If you had 5 levels of inheritance, you could skip form 5 to 2 (skipping 4 and 3) and then 2 code in and 1 would execute.

**Comment by JohanNel** [comment]
Matt - I understand.  Was just as clarification for myself that we on the same page.  I think Robert's Cast example is the correct and elegant way of how it is addressed in .NET
