### ISSUE TITLE
IVarPut should not test value of public property with private setter

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1023]
IVarPut throws "No exported variable" when trying to set private properties, but gives no error when trying to set public properties with private setters.

    var xxx := TestClass{}
    IVarPut(xxx, #PrivateSetDummy, 5) // Runtime should give exception "No exported variable", but instead sets the value
        
    class TestClass
        public property PrivateSetDummy as int auto get private set
    end class

Example solution: [XSharpTestsIVarPut.zip](https://github.com/X-Sharp/XSharpPublic/files/8630580/XSharpTestsIVarPut.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
Thanks for the report. This  is probably easy to fix

**Comment by RobertvanderHulst** [comment]
Hmm. I suspect it will be more difficult to detect this, since the implementation of IVarPut() is always outside of the DLL where the class is declared.

What I can do is:
when the method is internal, then detect the stackframe where the call originated and get the assembly through the method and its class and compare that with the assembly where the property is declared.
If we limit this code to properties that have internal visibility then this should not really harm the performance of other code.

**Comment by cpyrgas** [comment]
Yeah, makes sense. Or you could completely ignore INTERNAL, and only let PROTECTED/PRIVATE decide if a property/method is callable. After all, the IVarGet() mechanism is legacy for VO code which did not have INTERNAL members.

**Comment by RobertvanderHulst** [comment]
Ignoring INTERNAL only makes sense for the short term. In the long run people are going to detect this anomaly and will ask for a solution anyway.

**Comment by cpyrgas** [comment]
Confirmed fixed!
