### ISSUE TITLE
Problem with cast expression and numeric literals with the +/- sign in the macro compiler

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1025]
https://www.xsharp.eu/forum/private-product/2992-macro-compiler-issue-cast-numeric-value-to-usual#22381

```
FUNCTION Start() AS VOID
// all following work fine:
? &("1 + INT(+1)")
? &("1 + INT(-1)")
? &("1 + INT( 1)")
? &("1 + (INT) 1")
? &("1 + (USUAL) 1")
? &("1 + USUAL(+1)")
? &("1 + USUAL(-1)")

// all the rest result to XSharp.Error: Variable does not exist
? &("1 + (INT) +1")
? &("1 + (INT) -1")
? &("1 + (USUAL) -1")
? &("1 + (USUAL) +1")
```

```
XSharp.Error
Variable does not exist

Callstack : 
static __Usual XSharp.MemVar._Get(System.String cName)() 
static __Usual XSharp.RT.Functions.__MemVarGet(System.String cName)() 
__Usual XSharp.MacroCompiler.UsualMacro.MacroCodeblock.Eval(XSharp.__Usual[] args)() 
XSharp.MacroCompiler.UsualMacro.MacroCodeblock.Object XSharp.Codeblock.EvalBlock(System.Object[] args)() 
static __Usual XSharp.RT.Functions.Evaluate(System.String cString, System.Boolean lAllowSingleQuotes)() 
static __Usual XSharp.RT.Functions.Evaluate(System.String cString)() 
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  10
```

**Comment by RobertvanderHulst** [comment]
The problem is that in the following code the parentheses should be parsed as a parenthesized expression:
`{|x| (x) +1 }`

and the return value should be x+1 , even when x is also the name of a known type.

where in this code they should be parsed as a typecast expression:
`{|| 1 + (INT)+1 }`

The problem lies in the fact that the '+' (and also the '-') operator can be both a binary operator and a prefix operator.
The compiler now thinks that INT or USUAL are variable names and will try to find a memory variable with that name.

I will ask Nikos if he can add a check to see if the name inside the parenthesized expression is an existing type, and when it is then tread the expression as a typecast, and otherwise as a parenthesized expression.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed from me as well
