### ISSUE TITLE
foreach results to an "Conversion Error from USUAL (OBJECT) to ARRAY"

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1033]
With the following code and version X# 2.12 Beta (I don't know if the error was also in the versions before), you get an runtime error "Conversion Error from USUAL (OBJECT) to ARRAY"
```
using System
using System.Collections.Generic
using System.Linq
using System.Text

class Test
	public property Values as List<int> auto get set := List<int>{}
end class

function Start() as void strict
	local obj := Test{} as object
	obj:Values:Add(1)
	obj:Values:Add(2)
	
	foreach var i in obj:Values
		Console.WriteLine(((int)i):ToString())
	next
	Console.ReadLine()
	return
```
If "obj" is typed, everything works fine

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
This is not a new problem.

Because obj is untyped the call obj:Value is translated into IVarGet(obj,"Value")
The result of that function call is a USUAL.
The compiler cannot determine the type of this usual at compile time and therefore generates a call to special function in the runtime tries to detect if the usual value can be enumerated. (`FUNCTION __UsualEnumerator(u AS USUAL) AS ARRAY`)
At this moment this code checks to see if the USUAL is an array and when it is, then it returns the array. Otherwise a runtime error is returned. 

In your example the result of IVarGet() is an object that implements IEnumerable. So you could argue that this should work too.
This special function in the runtime is declared with an ARRAY return type. 
Ideally the function should return an Enumerator so we could return the List<int> from it.
However I cannot change the return type now because that would make the XSharp.RT.DLL binary incompatible with previous releases.

But what I can do is the following: create a temporary array inside this function, enumerate the elements of the collection and add these to the array. That should work too, but with a small overhead. And this overhead is to be expected, because you are using late binding in the code that triggers this.
I'll mark this ticket, so the return type of the function can change when we do a "breaking" build of XSharp.RT

**Comment by RobertvanderHulst** [comment]
HansJoerg,
Can you confirm that with the latest build this is working (although a better solution would be to not create an array)

**Comment by hpetriffer** [comment]
Confirmed fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
