### ISSUE TITLE
Feature request: make an overload for the Min and Max functions for dates

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1068]
The Min and Max functions are often used for the DATE and DateTime types. For type INT, for example, I can replace the Max function with Math.Max. But for the DATE and DateTime types, you need to look for other options. The Min and Max functions exist in X# only with the USUAL type. As a result, when they are called, both parameters are packed into the USUAL type. In this regard, it would be nice to have overloads of the Min and Max functions in X#, at least for the DATE type. In most other cases, the Min and Max functions apply to numeric types, but they have an alternative in the Math class.

**Example:**
```
[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Min(dValue1 AS DATE, dValue2 AS DATE) AS DATE
	RETURN IIF(dValue1 < dValue2, dValue1, dValue2)

[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Min(dValue1 AS DateTime, dValue2 AS DateTime) AS DateTime
	RETURN IIF(dValue1 < dValue2, dValue1, dValue2)

[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Max(dValue1 AS DATE, dValue2 AS DATE) AS DATE
	RETURN IIF(dValue1 > dValue2, dValue1, dValue2)

[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Max(dValue1 AS DateTime, dValue2 AS DateTime) AS DateTime
	RETURN IIF(dValue1 > dValue2, dValue1, dValue2)
```

**Comment by RobertvanderHulst** [comment]
Leon,
We are seeing some "noise" in users code while testing because of these new functions.
When customers have code like this
```
// error XS0121: The call is ambiguous between the following methods or 
// properties: 'XSharp.RT.Functions.Max(int, int)' and 'XSharp.RT.Functions.Max(dword, dword)'
// /vo4+ enabled
FUNCTION Start() AS VOID
LOCAL n AS INT
LOCAL a AS ARRAY
Max(n,ALen(a))
```

The compiler is right of course and this is bad code, but unfortunately people are doing this.
We are not looking forward to the (negative) noise that this will create.
We have therefore planned to move these functions out of XSharp.RT and to add a new assembly XSharp.Tools in which we will move these functions:  
Wolfgang has created a  XSharp.Tools repository already a while ago: https://github.com/X-Sharp/XSharpTools/tree/main/XSharp.Tools. 
We will integrate these functions into that assembly and we will make the assembly part of the X# distribution. We will also include the docs into our runtime documentation.

**Comment by leon-ts** [comment]
Robert,
I suggested making overloads only for the DATE and DateTime types. And for other types, leave USUAL as it was. Where did the compiler get overloads for INT and DWORD?

As I wrote above, if typed versions of the Min and Max methods for numeric types are needed, then the Math system class can be used.

P.S. I looked at the XSharp.Tools library and saw that I was unlikely to use it. It contains a set of methods for solving some very specific (and sometimes strange) tasks. There are some useful extension methods, for example, IsDigitsOnly, but similar methods have long been in the library (the solution with many thematic libraries) of the common components of our company.

**Comment by RobertvanderHulst** [comment]
Leon,
Maybe we got a little over enthusiastic when implementing the various Between() functions and added the overloads for the numerics ourselves.
I think we can leave the Max() and Min() functions for Date and DateTime in the runtime. These should not cause problems.

**Comment by cpyrgas** [comment]
In my opinion, adding Min() and Max() for only DATE and DateTime seems a little weird from the outside, why add to those specific datatypes, out of the dozens others? The reason of course is that I guess Leonid, this is what you actually need in your own code. 

In which case, why don't you simply define those extra overloads in your base library yourself, making them automatically available to all of your code? This way you will have full control over them, add as many as you like and freely modify them, without having to rely on us and/or risk we break something for other users.

I know, it does sound that adding some overloads sounds safe, but it really isn't, because of the huge complexity of the method/function resolving mechanism, which is already full of tricks and hacks for various reasons. And then we also have the problem of being able to call functions through macros, which adds another layer of complexity and things that can go wrong with multiple overloads. 

We've already had several problems at runtime reported to us by other people from when we introduced the Empty() overloads, then several other in build 2.12 when we made small changes to the resolve mechanism, now getting even more after we introduced new overloads in other functions, and those only the problems found so far, there are surely more waiting to be discovered at some point by users at runtime. We have already disappointed many people by introducing such issues out of the blue, we cannot risk further causing more like that.

But fortunately the best solution is very easy as mentioned above, please just define the functions yourself, and you are both fully under control, and we also do not risk breaking something.

**Comment by leon-ts** [comment]
Chris,
I suggested these overloads as being missing in general, not as being used by me personally (though i use them of course). If you take into account all the data types for which you can apply the functions for selecting the minimum and maximum values, you will see that they include not only numeric types, but also DATE and DateTime types. Numeric data types in NET have Min and Max methods in Math class, but DateTime does not.
At the same time, in the untyped version, the Min and Max (VO) functions work with all the mentioned types, including the DATE type. Thus, I did not suggest adding anything new, but only typing functions.
