### ISSUE TITLE
Access violation when calling a function/method with DECIMAL argument with default value

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1075]
```
FUNCTION TestDecimalDefault(nDec := 123.5m AS DECIMAL) AS VOID STRICT

	? nDec

RETURN

FUNCTION Start() AS VOID STRICT
	
	TestDecimalDefault() // access violation

	WAIT
RETURN
```

AFAIS, the problem is with [DefaultParameterValue] attribute which is given value 123.5 and not 123.5m.

**Comment by cpyrgas** [comment]
Thanks, problem confirmed!

**Comment by RobertvanderHulst** [comment]
There is a problem here: when compiling in non core dialect we are storing default parameter values in a DefaultParameterValueAttribute. This attribute has 2 fields: Value and Type. Value is of type object.
In this case the attribute should become `[DefaultParameterValue(123.5m, 0)]`. The 0 indicates that the value is a normal .Net type.
However Roslyn does not allow us to encode a decimal value in the object field of the attribute because it only allows "Primitive" types in attributes and decimal values are not considered to be primitive types.
Other possible values for the type field of the attribute are:
0 = Normal .Net value
1 = NIL
2 = Date (stored as ticks)
3 = Symbol (stored as string)
4 = PSZ
5 = IntPtr

I will change the way the DefaultParameterValue is encoded and add a new type (**6**) for decimals (and store the value as a string) and also change the compiler to decode this.
However this also requires a change in the runtime (in the late binding code). That will have to be done separately.

An alternative would be to store the value as a normal default value for the parameter. However that has the disadvantage that you will have to declare defaults for all parameters following the decimal too and these also have to be encoded as normal .Net defaults (so Date, Symbol, Psz and IntPtr are not possible).

**Comment by cpyrgas** [comment]
Confirmed fixed
