### ISSUE TITLE
Peek and Goto Definition not working correctly.

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1100]
See attached solution, in Start.prg there's this code:

oMainWindow:DoOpenFile()

- Try to use Goto Definition on "DoOpenFile" and the method declaration definition is opened as expected, but the caret is NOT positioned at that location of code. Instead it remains in the previous place were it was (or first line in the file, if the file was opened just now automatically).

- Try to use Peek Definition, this shows an empty box, with a message "We did not find any results".

Problem is reproducible with both VS2017 and VS2019

**Comment by RobertvanderHulst** [comment]
Ok, This makes sense now. 
I found:
- Peek definition fails for items start start at (1 based) column 1 in the source file
- A Goto definition in the **same** file does net set the Caret position

The reason for the first issue is a change that I made in the lexer because you (Chris) reported an issue with incorrect column numbers in error messages. The "problem" is that Antlr uses 1 based column numbers where VS uses 0 based column numbers. After the change we were sending in column numbers with the value "-1" for entities that start at the start of a line in the source code. 

I will also change goto definition to set the caret position. 
This will goto the start of the entity, so that will be the first token in the entity. This may be a keyword such as METHOD or FUNCTION or a modifier if the entity is prefixed with a modifier.


Btw: I also noticed that breakpoint lines are now 1 off. I'll fix that in the compiler.

**Comment by cpyrgas** [comment]
Robert, that explains some things, but it's not what I am seeing. Even if I move the method to the right a few tabs and/or spaces, Peek() definition still doesn't work. 

Without making this change, Goto Definition doesn't work even if the method is declared NOT on the same file, but in a different one (Standard Shell.prg, while it is being invoked from Start.prg). When moving the declaration a few columns to the right, indeed now goto definition puts the caret at the correct line, just by one off column position as you described.

**Comment by RobertvanderHulst** [comment]
I'll try to create a new build tomorrow that fixes these and also corrects the  debugger issue

**Comment by cpyrgas** [comment]
Confirmed fixed
