### ISSUE TITLE
VS does not show resource related errors in the Errors window

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1102]
See attached solution, contains a .rc file with a wrong filename. When trying to build, the error does appear in the Output window:

C:\Users\cpc\source\repos\VOMDIApp26\VOMDIApp26\Help About.POWXSHARPBMP.rc(1,0): error RC2135: file not found: Resources\NonExistent.BMP

but nothing is shown in the Errors window. In large projects, with tons of message in the Output, this makes it extremely difficult to spot what the reason for the project fail is.

[VOMDIApp26.zip](https://github.com/X-Sharp/XSharpPublic/files/9403894/VOMDIApp26.zip)

**Comment by cpyrgas** [comment]
The same problem exists also for managed resources and similar items. This solution shows an error in the Output window:

C:\Users\cpc\source\repos\WindowsFormsApplication38\WindowsFormsApplication38\Properties\Resources.resx(123,5): error MSB3103: Invalid Resx file. Could not find file 'C:\Users\cpc\source\repos\WindowsFormsApplication38\WindowsFormsApplication38\CALUP.BMP'. Line 123, position 5.
	Processing resource file "Form1.resx" into "obj\Debug\WindowsFormsApplication38.Form1.resources"

But again nothing is shown in the Errors window.

[WindowsFormsApplication38.zip](https://github.com/X-Sharp/XSharpPublic/files/9403938/WindowsFormsApplication38.zip)

**Comment by RobertvanderHulst** [comment]
In an attempt to prevent the error list from refreshing too often I was monitoring if the compiler did actually do something. Sometimes the build is started but VS detects that "no build is needed". In that case I do not refresh the list.
In this case the compiler did not run because of the errors with the resources.
Of course in that case the error list must be refreshed as well.
The error message IS shown on the Output window.
I personally have told VS to show the output window during builds:
Tools/Options
   Projects And Solutions
      Show Output Window when build starts

**Comment by cpyrgas** [comment]
Confirmed fixed.
