### ISSUE TITLE
Some issues with passing parameters by reference

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1166]
1. Passing a param to a function that expects it by reference without using @ or REF should produce a warning that value is passed automatically by reference and suggest that either @ or REF should be used 

```
PROCEDURE ByRef(p REF DWORD)
p := 2 
FUNCTION Start() AS VOID
LOCAL p := 1 AS DWORD
ByRef(p) // no warning
? p // 2 OK
```

2. When using the wrong type to pass a param by reference, without using @ or REF again, the compiler complains "Argument 1 must be passed with the 'ref' keyword". But this is not the problem, the problem is that the wrong data type is used:

```
PROCEDURE ByRef(p REF DWORD)
p := 2 
FUNCTION Start() AS VOID
LOCAL p := 1 AS INT
ByRef(p) // error XS1620: Argument 1 must be passed with the 'ref' keyword
? p
```

3.  In the following case, the function expects a Decimal by reference, but we are passing it an INT. There is no compiler error or warning and additionally the wrongly typed variable is not being updated, which is not a surprise of course. I guess there's an intermediate var passed to the function, which gets updated and its contents are afterwards lost?

```
PROCEDURE ByRef(p REF Decimal)
p := 2m
FUNCTION Start() AS VOID
LOCAL p := 1 AS INT
ByRef(p) // no error
? p // 1 again, wrong
```

**Comment by RobertvanderHulst** [comment]
I can (and have) fixed issue #1.
Issues 2 and 3 have 2 errors in the same parameter (a missing REF keyword and an incorrect type). 
The current Roslyn fails to find the correct method because of the 2 errors and 'thinks' that only the missing REF keyword is the problem. If you add that keyword then the type mismatch is detected. For now I would like to leave it like that.
