### ISSUE TITLE
MemVars created inside macros do not continue to exist after macro execution

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1182]
Reported by QLAdmin: Following code results to a runtime error in X#, that the var cannot be found. In VO, it works and returns the expected result:

```
FUNCTION Start() AS VOID
//PUBLIC somevar // works with that
//Evaluate('__MemVarDecl("somevar", false)') // also with that
? Evaluate("somevar := 123")
? Evaluate("somevar") // XSharp.Error: Variable does not exist
? somevar // XSharp.Error: Variable does not exist
```

**Comment by RobertvanderHulst** [comment]
This is by design. Only public memory variables are allowed to "live" longer than the scope  in which they were created. That is why MemVardecl("somevar", false) works.
That is also why I asked Nikos to create a special subclass "MacroMemVarCodeblock" that sets up a local memvar scope and evaluates the codeblock inside this scope.
I was not aware of the fact that VO allows this.
It should not be to difficult to eliminate this level, but I really do not like this...

**Comment by cpyrgas** [comment]
OK, I have asked the QLAdmin guys to review this and comment, as I am not sure how much they are depending on this VO "feature".

**Comment by qldev2016** [comment]
We will use Public to resolve this issue.

**Comment by RobertvanderHulst** [comment]
So we will leave this "as it is"
