### ISSUE TITLE
Undo/Redo now working when keyword case sync is enabled

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1205]
That's an old issue, put keyword case sync to upper and type this (not paste) and press enter (2 times):

function test()
local n as int

the editor turns this correctly to 

```
FUNCTION test()
    LOCAL n AS INT
```

Now the "Undo" toolbar button is enabled as expected. Try to press it, or press CTRL+Z, nothing happens. Still, it is possible to undo by pressing the small arrow next to the Undo button and manually select the actions that need undoing, and VS will now indeed undo them, but of course this is not practical.

**Comment by leon-ts** [comment]
I join Chris. This problem is often annoying.

**Comment by RobertvanderHulst** [comment]
Are you sure Ctrl+Z is defined as hotkey for Undo? VS very configurable, so you could have chosen a configuration with a different hotkey.
Anyway, I will see if I can trap this key (as well as Ctrl-Y for Redo) inside our editor code and map it to undo/redo.

**Comment by cpyrgas** [comment]
It's the same also when using the toolbar button, so it does not have to do with the key combination (which anyway always works when there's no automatic uppercasing of a line)

**Comment by leon-ts** [comment]
I confirm, this is not related to the way changes are rolled back (hotkey or left arrow in the toolbar menu). It just doesn't work (the first time). But it works from a certain 100th time (exaggerated). For example, you can hold down Ctrl+Z and after a while the changes will finally start to roll back.

**Comment by leon-ts** [comment]
As far as I understand, the problem is looping. The last action is converting words to uppercase (in the undo buffer, this position is described as "Text Buffer Change"). We undo the last action and the editor returns the original lowercase string. It works. But immediately after that, the editor "sees" that changes have been made and the changed line contains words in lower case - and this is a signal to translate words into upper case, according to the setting. And so in a circle.

**Comment by cpyrgas** [comment]
Leonid, that's exactly my understanding, too!

**Comment by cpyrgas** [comment]
Confirmed fixed!
