### ISSUE TITLE
IsNil returns false for variables typed as symbol

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1231]
The following method returns always false.
 
```
function IsSymbolNil(sym := nil as symbol) as logic
    return isNil(sym)
```
The reason for this is, that I use symbol as parameter type. Null_Symbol is not considered as nil. 
When I use the Object type instead of Symbol, IsNil works as expected.

```
function IsObjectNil(obj := null as object) as logic
    return isNil(obj)
```

Here is an example solution: [XSharpTestsSymbolIsNil.zip](https://github.com/X-Sharp/XSharpPublic/files/11029077/XSharpTestsSymbolIsNil.zip)

**Comment by cpyrgas** [comment]
Volkmar, from what I see VO has the same behavior, so in my opinion we should keep it that way in X#, too.

Actually I think it should not be allowed (or a warning should be reported) assigning NIL to a var strongly typed as SYMBOL, since it's not really a valid value for that data type. In fact, from what I see VO does exactly that, for this code:

LOCAL s AS SYMBOL
s := NIL

it reports a warning indeed "converting NIL->SYMBOL: 51423". We probably need to introduce the same warning in X#

**Comment by cpyrgas** [comment]
Confirmed, now the compiler reports

error XS1503: Argument 1: cannot convert from 'NIL' to 'symbol'

One small imperfection is that the error is reported on the calling code, not in the declaration of the function itself.

**Comment by cpyrgas** [comment]
As suggested in the beta forum, this needs to be changed to a warning. Sample showing the behavior in VO that needs to be reproduced in X#, this needs to print FALSE, TRUE in all cases:


```
FUNCTION Start() AS VOID
LOCAL s AS SYMBOL
s := NIL
? IsNil(s), s == NULL_SYMBOL
IsSymbolNil(NIL)
IsSymbolNil()

PROCEDURE IsSymbolNil(sym := NIL AS SYMBOL)
? IsNil(sym), sym == NULL_SYMBOL

```

**Comment by cpyrgas** [comment]
Confirmed fixed and warning looks good
