### ISSUE TITLE
X# preprocessor insert excess spaces

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1232]
**Describe the bug**
X# preprocessor insert excess spaces into #translate. Because of this it isn't possible to convert our date literals to X# native.

**To Reproduce**
```
#translate $(<d>/<m>/<y>) => {^<y>-<m>-<d>}

local d := $(23/03/2023)

if $(24/03/2023) < d
   ? "More"
else
   ? "Less"
endif
```

**Expected behavior (ppo file)**
```
local d := {^2023-03-23}
    
if {^2023-03-24} < d
    ? "More"
else
   ? "Less"
endif
```

**Actual behavior (ppo file)**
```
local d := {^23 -03 -2023 }
    
if {^23 -03 -2023 } < d
        ? "More"
    else
        ? "Less"
    endif
```

**Error message**
Error XS9111 The error is most likely related to the token '$' that was used at this location
Error XS9002 Parser: unexpected input '23'

**Additional context**
X# Compiler version 2.14.0.4 (release)

**Comment by RobertvanderHulst** [comment]
I will have a look. For now change the UDC to

`#translate $(<d>/<m>/<y>) => ConDate(<y>,<m>,<d>)`

**Comment by RobertvanderHulst** [comment]
The real problem in this case is that the date literal is normally recognized in the lexer. Since the date literal is created here in the preprocessor, then the parser does not receive a DATE_LITERAL but a sequence of LCURLY .... RCURLY and that is not recognized as a date literal. I will change the parser to also recognize this for those cases where the date literal is created by the preprocessor.
The spaces in the ppo file do not really play a role here.

**Comment by cpyrgas** [comment]
Confirmed fixed
