### ISSUE TITLE
VS Integration: inaccurate coloring of arrays of generic types

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1263]
The following screenshot shows the problem:
![Screenshot1](https://github.com/X-Sharp/XSharpPublic/assets/64518775/2ab43bb6-317f-4c17-b8db-027f5746ef20)

The square brackets of the array a1 are displayed in the correct color in the current color theme (white).
And the square brackets of the array a2 are displayed in the color used for string literals (the same color as in the third line with the example).

**Environment:**
X# 2.16.0.5
IDE VS2019

**Comment by RobertvanderHulst** [comment]
Distinguishing if the square brackets are string delimiters or array delimiters is tricky.
Our lexer has to decide after which token the '[' is seen as LBRKT and after which token as the start of a bracketed string.
Right now we are treating them as bracket after an ID, `']'`, `}'` and `')'`
And at the start of a line or after a keyword it is also treated as LBRKT (attributes)

And inside the attributes rule we also match bracketed string, because in a parameter declaration you could also have attributes
`FUNCTION Foo([SomeAttribute] Bar as INT) AS VOID`
But in a method call
`Foo([somestring])`
then the brackets would indicate a string

We cannot simply tell the lexer that after a `'>'` character, the `'['` should be a LBRKT. 
In this case 
`if C>[]`
it would have to be the start of a string
So we cannot simply add the '>' character, but we also have to analyze the context. That makes this difficult. It cannot be solved in the lexer, but has to be done by analyzing the context. And in the editor, we try to do things as fast as possible.

The easiest solution would be to drop support for bracketed strings. But not everybody will like that.
Maybe we should add a compiler option for that?

**Comment by leon-ts** [comment]
Robert,
I think that the coloring in this particular case is not critical. If you're saying it's too hard to fix without hurting performance, then it's best to leave the feature as it is. It is definitely impossible to remove support for square brackets for strings, since this method is actively used in the VO dialect. For example: `DBSetFilter(&("{||DToS(SOME_DATE_FIELD) == [20230525]}"))`

**Comment by RobertvanderHulst** [comment]
Ok, let's leave it like it is then.
