### ISSUE TITLE
PRG-Filenames in Visual Studio

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#1292]
Hi Dev-team,

for sorting-reasons I have several filenames of prg's in squared brackets. (See example: [Mailer].PRG)
If I open these prg's, close VS (2019) and restart VS, VS tries to open these prgs in designer-mode.
Not too important, but can this be changed or is it a Microsoft-Bug ?

![grafik](https://github.com/X-Sharp/XSharpPublic/assets/45791974/5740ce61-449b-4c1a-8bc3-6ed4a04f8f64)

Karl

**Comment by RobertvanderHulst** [comment]
Karl,
This is not a Microsoft Bug. We try to detect which files are in design mode and reopen them in Design mode.
Our extension checks for window captions that contain an '[' and end with an ']' when the solution is closed and tries to reopen them in design mode.
We cannot check for the word "[Design]" because that may be translated to [Entwurf] as you see in your image.
I will see if I can find a better method.
In the mean time, if you choose another character (like a parenthesis) that would prevent this from happening.

**Comment by RobertvanderHulst** [comment]
This was already fixed and is included in 2.17

**Comment by cpyrgas** [comment]
Confirmed fixed
