### ISSUE TITLE
Сalling parent methods with an explicit class indication (Xbase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1338]
**Describe the bug**
I see the point in moving part of the previous [ticket ](https://github.com/X-Sharp/XSharpPublic/issues/1215#issuecomment-1517280859) into a separate one. I conducted some experiments, and I was surprised to find that calling parent vars from a child works, but calling methods does not.

**To Reproduce**
```
procedure Main()
    local o

    o := DerivedExample():new()
    ? o:a
    ? o:Example:a
    ? o:Name()
    ? o:Example:Name()
    ? o:OldName()

    wait
    return

class DerivedExample from Example
exported:
    inline method Init()
        super:Init()
        ::a := 4
        ::Example:a := 5
        ? "DerivedExample:Init(): ", ::a, super:a, ::Example:a
        return self

    inline method Name()
        // return "DerivedExample:Name():" + super:Name() + " " + ::Example:Name() // stackoverflow
        return "DerivedExample"

    inline method OldName()
    return "DerivedExample:OldName(): " + super:Name() + " " + ::Example:Name()

    var a
endclass


class Example
exported:
    inline method Init()
        ::a := 3
        return self

    inline method Name()
        return "Example"

    var a
endclass
```

**Expected behavior (xBase++ exe)**
Output
```
DerivedExample:Init():           4          5          5
         4
         5
DerivedExample
Example
DerivedExample:OldName(): Example Example
```

**Actual behavior (X# exe)**
```
DerivedExample:Init():  4 5 5
4
4
DerivedExample
DerivedExample
DerivedExample:OldName(): Example DerivedExample
```

**Additional context**
X# Compiler version 2.17.0.3 (release)
-dialect:xBase++ -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment]
I managed to change this with some "dirty" tricks.
The `Example` property of the `DerivedExample` class is now typed as object. That means that method calls and property acccess/assign will always be late bound.
Inside that (compiler generated) `Example` property we now no longer return the object itself, but we wrap that object in a special class that holds the value and a type. In this case, that type is the type of the class `Example`
Inside the runtime whenever we do a late bound method call or access a late bound field/property the runtime recognizes that the object is "wrapped" and unwraps the object. To look up the members we no longer use the type from the Object (that would be `DerivedExample` in this case) but we use the type that was stored in the Wrapped Object (`Example`)
We then look for the method (`Name`) in that `Example` type. 
Because that method is declared Virtual we cannot simply call `MethodInfo:Invoke()` because that would call the implementation of the `Name` method inside `DerivedExample`

Instead we therefore have to generate a bit of IL on the fly (using a Dynamic Method) and inside that code we call the method with the `Call` opcode and not the `CallVirt` opcode that is used inside MethodInfo:Invoke().
The result is that everything will work just like you expect it.

There is one known issue:
If you assign `o:Example` to a local of type `Example` and then call the `Name` method on that local, then (because the method is virtual) you will still call the Name method in the `DerivedExample` class because the `Name` method is Virtual.
But this should not happen a lot, since code like this is usually part of untyped code ported directly from Xbase++

The only (theoretical) solution to that would be to create a complete new object of type `Example` inside the `Example` property and copy the relevant field values of `DerivedExample` over to that new object. But I am sure that a solution like that will have lead to other problems.

**Comment by cpyrgas** [comment]
Confirmed fixed
