### ISSUE TITLE
Call method of untyped object with expressions gives a NullReferenceException

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1343]
The following code throws an NullReferenceException. The problem ist that the code 
`test:AddColorCondition({val => val > 0})`
 is converted to 
`test:AddColorCondition(null)`

I understand that the compiler is unable to detect the type of the delegate. But it should at least print an error for the affected line and not simply ignore the parameter

```
delegate BrwRowCondition(val as int) as logic

class Test
	public method AddColorCondition(uCondition as BrwRowCondition) as logic
		var x := uCondition(1)
		return x
end class



function Start() as void strict
	local test := Test{} as object

	test:AddColorCondition({val => val > 0})

	return
```

[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/12609301/XSharpTests.zip)

**Comment by RobertvanderHulst** [comment]
The problem is that the test object is typed as object.
The compiler then generates a late bound call to AddColorCondition.
I am not seeing:
`test:AddColorCondition(null)`
but
`XSharp.RT.Functions.__InternalSend(test, "AddColorCondition", default(__Usual))`
Apparently there is no good conversion from the lambda to a usual.
It would indeed be a good idea to generate a compiler error, something like "cannot convert lambda to usual".
If you add a type for the Test local then the compiler generates the correct code (IlSpy):

```
public static void Start()
{
	Test test = new Test();
	test.AddColorCondition((int val) => val > 0);
}
```
Please remember that the USUAL type and Late Binding is for backward compatibility. Code like this should be strongly typed.

**Comment by hpetriffer** [comment]
In this case it was an oversight that it was not strongly typed. Unfortunately, we still have a lot of old code. The main problem for us is that the parameter was simply ignored and no error message came during compilation, but only at runtime the NullReferenceException. A compiler error for this is really important

**Comment by RobertvanderHulst** [comment]
I will try to add the error message.
I understand that you still have old code. But if you start adding methods like these (with a delegate as parameter) then you also need to start disabling "late binding" for at least that part of your app. You can disable late binding at the module/source file level by adding a pragma like 
`#pragma options("lb", off)`

**Comment by cpyrgas** [comment]
Confirmed fixed, compiler now reports:

error XS9121: Cannot convert from Lambda Expression to usual.
