### ISSUE TITLE
CTOD returning NULL_DATE

### ISSUE THREAD

**Issue by fxxm** [X-Sharp/XSharpPublic#1346]
I suspect this relates to the fix for #1275

In 2.17.0.3 this returns NULL_DATE

`CTOD("15/09/2023 09:22:26:617")`

In 2.16.0.5 this would return a valid date 15/09/2023

I'm not saying it's a great string to pass to a function but it used to work.

**Comment by cpyrgas** [comment]
I'm afraid that even though it used to work, it was incompatible to VO, which also returns NULL_DATE for this string (and similar ones). I understand it might be handy that it allowed this in X# previously, but since CToD() is a VO compatibility function, it's probably better to keep it compatible to VO (well as much as possible, because 100% compatibility with this function is impossible).
