### ISSUE TITLE
XSharp.VORDDClasses: untyped FileSpec object in constructor gives a runtime error

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#1348]
The following code I'm using in VO gives a runtime exception with the XSharp.VORDDClasses:
```
class AppDBServer inherit DbServer

constructor( oFileSpec, lShareMode, lReadOnly, cDriver )

	if Isnil( oFileSpec )
		oFileSpec		:= FileSpec{ Symbol2String( ClassName( self ) ) + ".DBF" }
		oFileSpec:Path	:= oApp:DataPath + "\"
	endif
	if Isnil( lShareMode )
		lShareMode	:= true
	endif
	if Isnil( lReadOnly )
		lReadOnly	:= false
	endif
	if Isnil( cDriver )
		cDriver		:= oApp:StdRDD
	endif

	super( oFileSpec, lShareMode, lReadOnly, cDriver )		///XSharp

	return self
end class
```
When I change the call to the super() constructor this way, it works:
```
	super( ( FileSpec ) oFileSpec, lShareMode, lReadOnly, cDriver )
```

**Comment by RobertvanderHulst** [comment]
At this moment the typed RDD classes have 2 overloads:

`CONSTRUCTOR( cFile AS STRING, lShareMode := FALSE AS OBJECT, lReadOnlyMode := FALSE AS OBJECT, xDriver:= "" AS STRING, aRDD := NULL_ARRAY AS ARRAY)`
and 
`CONSTRUCTOR( oFS := NULL AS FileSpec, lShareMode := FALSE AS OBJECT, lReadOnlyMode := FALSE AS OBJECT, xDriver:= "" AS STRING, aRDD := NULL_ARRAY AS ARRAY)`

It looks like the compiler chooses the one with the string parameter, because the oFileSpec is of type usual.
I'll add an overload with a usual parameter

**Comment by wriedmann** [comment]
that would be a great solution, I think. I have code like my sample code in nearly all of my VO applications in the base DBServer class.

**Comment by cpyrgas** [comment]
Confirmed fixed. Wolfgang, if you still see any problems with this, please reopen it.
