### ISSUE TITLE
Feature request: Optimizing MSIL code in constructors

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1354]
In the following example, the class 'TestClass' has several constructor overloads where the call is simply passed to the main (most complete) overload.
```
CLASS TestClass

	PRIVATE a, b, c AS USUAL

	CONSTRUCTOR(a AS USUAL, b AS USUAL, c AS USUAL) STRICT
		SELF:a := a
		SELF:b := b
		SELF:c := c
	END CONSTRUCTOR
	
	CONSTRUCTOR(a AS STRING) STRICT
		SELF(a, NIL, NIL)
	END CONSTRUCTOR

	CONSTRUCTOR() STRICT
		SELF(NIL, NIL, NIL)
	END CONSTRUCTOR

END CLASS
```
As a result, the generated MSIL code creates empty try...catch blocks that initialize the memvar variables.
![Screenshot](https://github.com/X-Sharp/XSharpPublic/assets/64518775/8803eddd-d9ed-4d57-9cd4-53edc4d4824b)

Please optimize this situation and remove unnecessary memvars initialization from the code.

**Example project:**
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/12712992/XSharpBetaTest.zip)

**Environment:**
Compiler X# 2.17.0.3
IDE VS 2022

**Comment by RobertvanderHulst** [comment]
What we can do is suppressing the generation of these blocks when the body of the constructor is empty.
To be honest: we did not foresee the combination of using dynamic memory variables ("old style code") and multiple constructors ("new style code").
I will also see if I can suppress this code generation by adding a pragma to the code to suppress dynamic memory variables for a certain file or section of code.

**Comment by leon-ts** [comment]
Robert,
What is the sign by which the compiler decides whether to insert MemVarInit framing blocks into a method/function? I now selectively looked (via ILSpy) at the code in my DLLs and some have MemVarInit, but others do not. Moreover, all these methods/functions are typed and do not use memvars at all.

**Comment by RobertvanderHulst** [comment]
Leonid,
We try to determine at compile time if a method / function can /will have memory variables. 
Some of the criteria:
- a memvar, private, public, parameters statement
- a dimension statement (FoxPro dialect)
- evaluation of a macro (because the macro may create a dynamic memory variable), or a call to Eval() / ExecScript()
- calls to memvarget(), varget(), memvarput(), varput() 
- Aliased expressions (M->Name)
- a variable prefixed with "M." (FoxPro dialect)
I saw in your example that this is not working perfectly. 
The best way to a void this code generation is  not to enable memvar support

**Comment by cpyrgas** [comment]
Confirmed done
