### ISSUE TITLE
DBFCDX: strange lock problems and index corruption after DBPack() 

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1367]
There is a reproducible but very multi-step situation in a sample project. The problem is in the real world. It would very kind of you to investigate the problem ASAP.
X# 2.17.0.3

[TestAppend.zip](https://github.com/X-Sharp/XSharpPublic/files/12916840/TestAppend.zip)

1. The table is created with 3 certain indexes. You change them or make less of them - there is no problem.
2. Then 134 records of particular data are appended . You append less lines - there is no problem.
3. DBPack(). If omitted - there is no problem (though no records were deleted).
4. You append two more lines and get a lock problem on the second of them - it is not appended and DBAppend() returns false.

**Comment by Serggio** [comment]
The problem seems to be with the third index while going cold on append operation.

**Comment by cpyrgas** [comment]
Indeed, but it does not seem to be caused by that 3rd index itself. Removing any of the other indexes and keeping that one intact still reproduces the problem. I could also reproduce this with a cut down version of the index expressions:

DbCreateOrder("DR_TIN", "TESTTABLE.CDX", "Str(FORWHAT,1)+TIN")
DbCreateOrder("DR_TN", "TESTTABLE.CDX", "Str(FORWHAT,1)+Str(TN,8)")
DbCreateOrder("DR_PAGE", "TESTTABLE.CDX", "Str(FORWHAT,1)")

but removing any further part of the index expressions results to the problem not being reproducible anymore

**Comment by cpyrgas** [comment]
Can't confirm this one, both the original sample and the test I entered in the suite still fail.

**Comment by cpyrgas** [comment]
Confirmed fixed
