### ISSUE TITLE
IEnumerable Debugger Visualizer not working with X#

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1373]
Visual Studio 2022 (17.2) supports debug visualizers for IEnumerables and DataTables.

https://devblogs.microsoft.com/visualstudio/view-net-collections-with-the-new-ienumerable-debugger-visualizer/

If i try to use these visualizers in an x# project (2.17.0.3), i'll get the following error: "Could not load this custom viewer."

Here's a example project in c# and x# that shows that problem. When you put a breakpoint on the dt.Rows.Clear line and try to use the debug viewer on arr or dt.

![image](https://github.com/X-Sharp/XSharpPublic/assets/9860916/e8a7f5b7-e823-4b41-b0c1-52b8a1af026e)
![image](https://github.com/X-Sharp/XSharpPublic/assets/9860916/93213242-6ca7-4a22-9579-f5c7ce315980)

X# Example: [XSharpTestsDataTableViewer.zip](https://github.com/X-Sharp/XSharpPublic/files/13052989/XSharpTestsDataTableViewer.zip)
C# Example: [Visualizer.zip](https://github.com/X-Sharp/XSharpPublic/files/13052983/Visualizer.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
Thanks for the report and the examples. I will look into this.

**Comment by RobertvanderHulst** [comment]
It's working now, but the visualizer is not very smart. It also includes fields and properties that are marked with an attribute to be hidden. See https://github.com/microsoft/ConcordExtensibilitySamples/issues/108
Therefore, the visualizer output for arrays is Terrible because it shows all the hidden properties of the Usual values in the array elements.....
