### ISSUE TITLE
Class Navigation bar does not show the method name

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1381]
In our case the "navigation bar" does not show the methodname.

![image](https://github.com/X-Sharp/XSharpPublic/assets/20905638/2c361c89-fc1c-4083-9d8c-e475666f978d)

I send an example directly to Robert

Hansjörg

**Comment by RobertvanderHulst** [comment]
Found and Fixed.
if you open the file and use the Combobox to navigate to the GetGSTransformInfo() method and then press the cursor down it works until the cursor enters the line 
`IF symNode == #Valtype`
After that the lookup is broken until you close the file and reopen it.

The reason is that the lookup system inside VS matches the symNode token with the symNode parameter. It does a type lookup and finds that the underlying type is XSharp.__Symbol. This change from SYMBOL to XSharp.__Symbol has a side effect that causes the lookup in a dictionary with method prototypes - combobox item positions to fail.

**Comment by cpyrgas** [comment]
I don't have the repro sample, so will let Hansjörg confirm this

**Comment by hpetriffer** [comment]
Works in 2.19
