### ISSUE TITLE
Bogus compiler error messages with not found type

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1396]
Following code produces one correct error message:

error XS0246: The type or namespace name 'NowhereToBeFound' could not be found (are you missing a using directive or an assembly reference?)

and 3 bogus ones:

test.prg(3,1): error XS0012: The type 'NowhereToBeFound' is defined in an assembly that is not referenced. You must add a reference to assembly 'xRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
test.prg(4,1): error XS0012: The type 'NowhereToBeFound' is defined in an assembly that is not referenced. You must add a reference to assembly 'xRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
test.prg(5,3): error XS0012: The type 'NowhereToBeFound' is defined in an assembly that is not referenced. You must add a reference to assembly 'xRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

In large apps, this can produce 100s of error messages, making it difficult to spot the real problem.

```
FUNCTION Start() AS VOID
LOCAL o AS NowhereToBeFound
o:nothing()
o:IdoNotExist := 123
? o:WhatAssembly
```

**Comment by RobertvanderHulst** [comment]
Fixed in 8c1c7a597de6914995fade03ced058ed307a18db

**Comment by cpyrgas** [comment]
It's better now, but still problematic, the sample code now produces two error messages for the local type declaration, on the same line:

`error XS0246: The type or namespace name 'NowhereToBeFound' could not be found (are you missing a using directive or an assembly reference?)
error XS0246: The type or namespace name 'NowhereToBeFound' could not be found (are you missing a using directive or an assembly reference?)`

One would be enough :)

**Comment by RobertvanderHulst** [comment]
Chis,
I only see a single error message. Maybe this depends on compiler options?

**Comment by cpyrgas** [comment]
Oh indeed, it's because I had /initlocals enabled. Surprised this makes a difference here!

**Comment by cpyrgas** [comment]
Robert, it's still a bug that the error message gets doubled when /initlocals is enabled. Not critical of course, but still...

**Comment by cpyrgas** [comment]
Some more info, when /initlocals is enabled, then the two error messages point to the same line, but different column. For the line

LOCAL o AS NowhereToBeFound

the first error points to the token "o" and the second one to "NowhereToBeFound".

Guess this is an issue with /initlocals that will surface also with other errors or warnings

**Comment by RobertvanderHulst** [comment]
The reason why you see 2 messages is this:
- the /initlocals compiler option changes the code `LOCAL o AS NowhereToBeFound` to `LOCAL o := DEFAULT(NoWhereToBeFound) AS NowhereToBeFound`
- I cannot generate `LOCAL o := NULL AS NowhereToBeFound` because at that phase in the compiler I do not know if the local is a value type or a reference type.
- The generate initializer needs to be bound to a source code location. I have chosen to bind it to the identifier of the local (o). 
- There are now 2 references to the unknown type bound to 2 different source code locations. That is why you see 2 messages.

I will change the code to bind the initializer expression to the location of the type. That will still generate 2 errors, but these errors point to the same location then and the compiler will suppress the 2nd error message.

**Comment by cpyrgas** [comment]
Confirmed fixed
