### ISSUE TITLE
Add FoxPro SQL Workarea support

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#143]
This will have to be an RDD implementation on top of a DataTable or DataView. The default behavior of FoxPro is that `SELECT ... INTO CURSOR` creates a Readonly cursor.
To get an updatable cursor you need to add the READWRITE clause.
You can also use 
`SQLEXEC(m.lnConn, 'SELECT * FROM authors', 'PubAuthors')`
To create a cursor named 'PubAuthors'

I suggest to NOT support 'embedded' SQL for now. That can be done later.
One 'special' thing is the syntax for embedding parameters in SqlExec statements:
`SQLEXEC(m.lnConn, "exec #myProc2 ?lnPercent, ?@lnOutput")`
These parameters can be both dynamic memvars, in which case they can be resolved in SQLExec() but also local or global variables. So we will have to somehow convert this to a kind of interpolated string and create an array of in and out parameters that can be passed to SqlExec().
So SQLEXEC() can't be a normal function call but should be handled by the compiler.

**Comment by mattslay** [comment]
> I suggest to NOT support 'embedded' SQL for now. That can be done later.

What do you mean by 'embedded' SQL?  Do you mean that native part of the FoxPro language that allows one to make a SQL query against FoxPro DBF tables??  If so, I don't think you can put that in the "can be done later" category, as this is a canonical part of FoxPro.

SQLXEC() is called against SQL Servers, or even MySQL, but many FoxPro apps only work with DBF, so with DBF SQL, X# usage by many VFP people will be delayed until it is supported in X#.

**Comment by RobertvanderHulst** [comment]
Matt,
I mean the 'SELECT - SQL command' from the FoxPro Help file  that allows you to run SQL queries against data in DBF files.
We'll add that eventually but not in one of the upcoming Milestones. We can probably emulate this fairly quickly if we open tables with the Advantage driver, since Advantage has support for SQL selects on DBF files. But to allow this on our own RDDs we need to add a SQL Parser to our compiler or runtime which is too much work for the upcoming milestones.
Like the SQLEXEC() command the SELECT - SQL command needs to also support passing in local variable, so we also need to add special handling to the compiler to allow values of local variables to be passed in. It is not enough to send the SQL command as a string to a runtime function because that function will not be able to see the locals and globals that are not in scope.
I know this is probably not what you want to hear, but we really can't afford to spend a LOT of time on this at this moment.

**Comment by mattslay** [comment]
I can't even imagine all the complexity and competency that is required to tackle this stuff. I am truly in awe of you and the X# Team that you can do these things. I do indeed appreciate that these difficult things take time.

**Comment by lazy-fox** [comment]
There is also the "Nofilter" clause important to the Select.. into Cursor.
Both "ReadWrite" and "NoFilter" clause force the result to be "materialized", whereas (esp. if a filter condition equal to existing index exists) otherwise only a "filtered cursor", which is nothing but a way to step via index over the records of the base table without changing them, can be returned.
Materialized cursors can again be queried via SQL - which is often needed, therefore most Select .. into Cursor are either ReadWrite, Nofilter or both - of which last option of course is unneccessary, but found in the wild.

**Comment by lazy-fox** [comment]
As SQL query via strings is supported via ADO.Net, another option might be to query dbf via SQL, but then instead of piping into Datatables, piping into new DBF from the reader is done. That way Select .. into table is implemented in similar way, and only a special "cursor" handling for specific tables needs to be implemented (special dir, clean up, Buffering/Tableupdate).
Largest benefit I see is the option to use newly created table/cursor again in new SQL queries. Or is SQL now possible against in-memory-Datatables ? When I looked last, one had to use different ways to index, set relation and so on - whereas vfp tries to allow same access mechanism to remote data sources, local tables, local cursors as caches, perhaps rows via scatter name and so on

**Comment by RobertvanderHulst** [comment]
This has been implemented in 2.3.3
