### ISSUE TITLE
Unhandled exception when using greater than or less than uType Logic

### ISSUE THREAD

**Issue by christianschmid200272** [X-Sharp/XSharpPublic#1547]
There is a unhandled exception when using greater than or less than uType Logic.

An unhandled exception is not good, especially as a uType can be anything. If a comparison operator for a type is not implemented, it should always be false.
```
FUNCTION Start() AS VOID STRICT
	LOCAL uTest AS USUAL
	uTest := TRUE
	IF uTest > 0.0
		?"ok"
	ENDIF
	RETURN
```
```
//In this case the compiler said "Error XS0019	Operator '>' cannot be applied to operands of type 'logic' and 'real8'"
FUNCTION` Start() AS VOID STRICT
	LOCAL uTest AS LOGIC
	uTest := TRUE
	IF uTest > 0.0
		?"ok"
	ENDIF
	RETURN
```

**Comment by RobertvanderHulst** [comment]
We cannot produce a compiler error here like in the second example, because uType could be of the right type.
So the comparison is done at runtime.
There is no really an "unhandled exception" here.
Our runtime looks at the types of the 2 operands. In this case the first operand is a logic and the second a number.
As you can see in the code of the Greater Than operator:
https://github.com/X-Sharp/XSharpPublic/blob/main/src/Runtime/XSharp.RT/Types/Usual.prg#L665
this results in the runtime throwing a binary error with the message that the arguments are incompatible (there is no case for __UsualType.Logical)
I understand that you would have expected a return value of FALSE.
But that would hide logical errors in your code and is also not compatible to the behavior of VO and FoxPro

**Comment by christianschmid200272** [comment]
I haven't actually checked the compatibility with VO, if this is not guaranteed then that's done anyway, compatibility is more important.

The ticket can be closed.

**Comment by RobertvanderHulst** [comment]
VO throws the following exception for the first example:
![image](https://github.com/user-attachments/assets/84b40d82-628a-48a4-b86e-167a6e5c4fa3)

**Comment by cpyrgas** [comment]
Those were my findings as well, indeed if we changed that, we would produce a VO incompatibility.
