### ISSUE TITLE
dbcmd.xh  error

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#156]
in the file dbcmd.xh  the line:

`#command FIND <*text*>		=> dbSeek( <(text)> )
`

causes an XS9002 error: Parser: unexpected input.

When i disable the line the error disappears.

```
#include "DbCmd.xh" 

function Start() as void

return 
```

regards
Karl-Heinz

**Comment by JohanNel** [comment]
Hi Karl-Heinz/DevTeam
> in the file dbcmd.xh the line:
> `#command FIND <*text*> => dbSeek( <(text)> ) `
> causes an XS9002 error: Parser: unexpected input.
> When i disable the line the error disappears.
> ```
> #include "DbCmd.xh" 
> function Start() as void
> return 
> ```
Tried and I don't get the error.  However, looking at the FIND #commands, I thought it might be due to the sequence of the 3 FIND commands.  Tried the Test with /ppo set on and got the following, so not sure if that is the expected result.  Sorry for funny AddFromEAVString, but quickly tested it in the module I was busy working with.

#command FIND := <xpr>          => ( find := <xpr> )
#command FIND = <xpr>           => ( find := <xpr> )
#command FIND <*expr*> => AddFromEAVString(<(expr)>) // This can be first or last #command.
/* Quick test
FUNCTION Start() AS VOID
		FIND blah blah
		FIND blah
		FIND := ja ja
		FIND = ja
		FIND = no no
		FIND = no
RETURN
*/
/* PPO Output
AddFromEAVString("blahblah" ) // See space removed
AddFromEAVString("blah" ) // Correct
AddFromEAVString(":=jaja" ) // thought I will get (find := "ja ja")
AddFromEAVString("ja" ) // ??? (find := "ja"
AddFromEAVString("=nono" ) // ??? (find = "no no")
AddFromEAVString("no" ) // ??? (find = "no")
*/
As you can see the order of the FIND commands have no effect

**Comment by RobertvanderHulst** [comment]
Johan,
The order of the commands does have an effect:
```
#command FIND <*text*>          => dbSeek( <(text)> )
#command FIND := <xpr>          => ( find := <xpr> )
#command FIND = <xpr>           => ( find := <xpr> )
Function Start as void      
	local find as string
	find := "123"	
	find = "456"
	find find
	find (find)
	return
```
ppo output:
```
Function Start as void      
	local find as string
( find := "123" )
( find := "456" )
dbSeek( "find" )
dbSeek( find )
	return
```

Now change the order and move the DbSeek to the end of the list:
```
#command FIND := <xpr>          => ( find := <xpr> )
#command FIND = <xpr>           => ( find := <xpr> )
#command FIND <*text*>          => dbSeek( <(text)> )
```
and the output becomes

```
Function Start as void      
	local find as string
dbSeek( ":="123"" )
dbSeek( "="456"" )
dbSeek( "find" )
dbSeek( find )
	return
```
It makes a difference because the `<*text*>`  marker matches anything

Robert

**Comment by JohanNel** [comment]
Hi Robert,
Yes, that is how I understood the pre-proccessor from Clipper days.  I was just trying to test seeing Karl-Heinz issue in a quick and dirty approach and then found what I have observed, although I did not get the same issue as Karl-Heinz producing a compiler error.

**Comment by Karl1155** [comment]
Folks, but that doesn´t solve my problem ... in the meantime i found the reason why i see an XS9002 error. As already described above, this line in the dbCmd.xh causes the compile error:

`#command FIND <*text*> => dbSeek( <(text)> ) 
`
when i replace the word "text" with e.g. "xtext" the error is gone !

`#command FIND <*xtext*> => dbSeek( <(xtext)> ) 
`

when i change another command:

`#command GOTO <n>               => dbGoto(<n>)`

to 

`#command GOTO <text>               => dbGoto(<text>)`

the XS9002 Error is back again.

What´s the problem with the usage of the word "text"? BTW. It´s not neccesarry to #Include the , DbCmd.xh, simply add this command to your source file. 

`#command GOTOX <text>               => dbGoto(<text>)
`

regards
Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,

Which dialect ?

Robert

**Comment by RobertvanderHulst** [comment]
I checked and in the FoxPro dialect this does not work because TEXT has a special meaning. It triggers a special Lexer mode for TEXT .. ENDTEXT. I will change the lexer to make sure that this special mode is only activated when TEXT is the first non whitespace token on a line.

**Comment by Karl1155** [comment]
sorry, yes, it´s about the fox dialect !

**Comment by RobertvanderHulst** [comment]
Fixed in next build.
