### ISSUE TITLE
Problem reading fpt memos with ADS driver

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#188]
Following throws an XSharp.ADS.AdsError when trying to read from a .fpt memo through the ADS driver.

```
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "C:\test\memodbf"
	FErase(cDbf + ".cdx")
	FErase(cDbf + ".fpt")
	FErase(cDbf + ".dbf")
	
	RddSetDefault("DBFCDX")
	DbCreate(cDbf, {{"FLD1" , "C" , 10 , 0} , {"FLDM" , "M" , 10 , 0}})
	DbUseArea(,,cDbf)
	DbAppend()
	FieldPut(1, "abc")
	DbAppend()
	FieldPut(2, "this is a somewhat long text")
	DbCloseArea()
	
	
	RddSetDefault("AXDBFCDX")
	? XSharp.RDD.Functions.AX_SetServerType(FALSE,FALSE,TRUE)
	? DbUseArea(,,cDbf)
	? FieldGet(2)
	DbSkip()
	? FieldGet(2)
	? DbCloseArea()
RETURN
```

XSharp.ADS.AdsError
Error 5005:  The supplied buffer was insufficient for the information returned.  The data may have been truncated.

Callstack : 
static Object XSharp.RT.Functions.DoError(System.String cSymFunc, System.Int32 nTries)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg  :  242
static Boolean XSharp.RT.Functions._DbThrowErrorOnFailure(System.String funcName, System.Boolean resultToCheck)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg  :  19
static __Usual XSharp.RT.Functions.FieldGet(XSharp.__Usual[] Xs$Args)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg  :  593
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  21

**Comment by cpyrgas** [comment]
Can't confirm fix, sample now throws a different exception:

Unhandled Exception: XSharp.ADS.AdsError: Error 7010:  Problem with Advantage server file read.
   at XSharp.RT.Functions.DoError(String cSymFunc, Int32 nTries) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 243
   at XSharp.RT.Functions._DbThrowErrorOnFailure(String funcName, Boolean resultToCheck) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg:line 19
   at XSharp.RT.Functions.FieldGet(__Usual[] Xs$Args) in C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg:line 593
   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg:line 23

**Comment by RobertvanderHulst** [comment]
Chris,
Most likely the memo block size needs to be set to a value > 32.
I had this error too and after increasing the block size to 64 the problem was gone. I forgot to mention that.
This is what the advantage help file says about error 7010:
Problem 1: The Advantage server was unable to read from the specified file.
Solution 1: Check the status of the network and repeat the command.

Problem 2: An Advantage application may receive 7010 errors if:
- DBF tables with FPT memo files are being used.
- The FPT memo file was created with a memo block size of 32 or less.
- The FPT memo file was created with a database driver that is not completely  FoxPro-compatible, such as SuccessWare's SIXCDX RDD, CA-Clipper's DBFCDX RDD,  Loadstone's COMIX RDD, Vista Software's Apollo CDX driver, or the Halcyon CDX  driver.

Solution 2: To alleviate the problem with 7010 errors with DBF tables and FPT memo files created by non-FoxPro compatible database drivers:
- Create a new DBF and FPT using an Advantage database  driver.
- Copy all data from the old DBF and FPT to the new DBF and FPT using the  non-Advantage database drivers.
- Delete the old DBF and FPT and use the new DBF and FPT. The new DBF and FPT  (that were created by the Advantage driver) should be fully functional with both  Advantage and non-Advantage database drivers.

Problem 3: 7010 errors may occur when reading an index if the index is corrupt.
Solution 3: If the 7010 error occurs when performing a database operation that uses an index, or if the Advantage error log (ADS_ERR.ADT or ADS_ERR.DBF) indicates the 7010 error occurred when reading an index file, re-building the index will eliminate the index corruption and should eliminate the 7010 error.

**Comment by cpyrgas** [comment]
Thanks, this makes sense of course! I have sent a new dll to Meinhard to confirm that the problem is fixed.
