### ISSUE TITLE
"Entry point was not found" exception. ForEach over GetProperties()

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#246]
This code causes exception `System.EntryPointNotFoundException: 'Entry point was not found.'` at runtime, at the ForEach statment in Tester.Test()

Running in VFP dialect, but all the code being used is just Core and .Net stuff.

Code can be ran as-is to see the error.

```
Using System
Using System.Collections.Generic
Using System.Text

Using System.Reflection


Function Start() As Void Strict
	
		Var oTester = Tester{}

		Var oObject = MyClass{}
		oTester.Test(oObject)

End Function

//-------------------------------------------------------------------------------
Class Tester
	
	Method Test(oObject)
		
		Var objectType = oObject.GetType()
		
		Var properties = objectType.GetProperties()
		//Local properties = objectType.GetProperties() As PropertyInfo[]
		
		Foreach prop As PropertyInfo In properties
			?prop.name
		Next
		
		Wait

End Class

//-------------------------------------------------------------------------------
Class MyClass

	Export cKey As String
	Export cType As String
	Export cFilename As String
	Export cPkField As String

End Class
```

![2019-10-27 02_35_12-xsMapper (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/309016/67631337-c9f0dd80-f862-11e9-908d-860557447ed7.png)

**Comment by RobertvanderHulst** [comment]
This code passes oObject as untyped variable to Test().
As a result the call to oObject.GetType() is compiled into a Late bound call. The result of this call will therefore be a USUAL containing an object of type System.Type.
objectType.GetProperties() will then also become a late bound call and will return the PropertyInfo[] array as a X# array of usuals.
In this particular case that array will be empty because the class declaration declares fields and not properties.
```
Class MyClass
	Export cKey As String
	Export cType As String
	Export cFilename As String
	Export cPkField As String
End Class
```
The exception was caused by the fact that the USUAL variable that holds the (empty) PropertyInfo[] array did not implement the IEnumerable interface.
We have now added support for IEnumerable for the USUAL type, which will check to see if the usual contains an array and will then return the enumerator for the array. Also when the USUAL contains an object that implements IEnumerable then the enumerator for that object will be returned.

Finally: after this correction the loop is now enumerating an array. The construct  `Foreach prop As PropertyInfo In properties` will not work because the elements of the array are USUAL (containing a PropertyInfo) and not a PropertyInfo object.
This will work:
```
   FOREACH uProp AS USUAL IN properties
      IF uProp IS PropertyInfo VAR prop
	   ?prop.name
       ENDIF
   NEXT
```
But like I said: even with this change the code will not display any properties because there are no properties.
This will work however
```
	VAR fields = objectType.GetFields()
        ? "Fields"
	FOREACH fld AS USUAL IN fields
		?fld.name
	NEXT
      
```
If you want "early bound" code then try this

```
	FOREACH uFld AS USUAL IN fields
            IF uFld IS FieldInfo VAR fld
			?fld.name
            ENDIF
	NEXT
```

**Comment by cpyrgas** [comment]
Not sure this is directly related, but FOREACH currently works for an ARRAY in a usual, bit not for a System.Array in a usual, it throws an exception "Conversion Error from USUAL (OBJECT)  to ARRAY". Should that be supported as well?

```
FUNCTION Start() AS VOID
LOCAL a AS USUAL
a := {1,2,3} // this works
a := <INT>{1,2,3} // this doesn't
FOREACH u AS USUAL IN a
	? u
NEXT

XSharp.Error
Conversion Error from USUAL (OBJECT)  to ARRAY

Callstack : 
static __Array XSharp.RT.Functions.__UsualEnumerator(XSharp.__Usual u)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\CompilerSupport.prg  :  443
```

**Comment by RobertvanderHulst** [comment]
Implicit conversion from usual to System.Array will not be possible.
The compiler needs to know the type of the elements in the collection to be able to generate the right code and to be able to determine if the AS <Type> needs an extra conversion operation.
I would have loved to support this as well, and I have tried several options but could not get this to work.

**Comment by cpyrgas** [comment]
Ah, a pity! Confirmed fixed then.
