### ISSUE TITLE
SetCollation() and SetInternational()

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#281]
i´m using these settings:

SetInternational ( #clipper  ) 
SetCollation ( #clipper ) 

But, if i want to know the current settings, both funcs suddenly return "XXP" instead of "CLIPPER"

? SetInternational ()  // "XXP"
? SetCollation ()      // "XXP"

i think there´s something going wrong with the CollationMode enum because .Clipper and .XPP has the same value 1. Try this:

```
FUNCTION Start() AS VOID

? SetInternational ( #clipper  ) // ok "WINDOWS"
? SetCollation ( #clipper ) 	 // ok "WINDOWS"
?
? SetInternational ()  // "XXP" <---
? SetCollation ()      // "XXP" <---
?
? RuntimeState.CollationMode == CollationMode.Clipper  // true
? RuntimeState.CollationMode == CollationMode.XPP      // true 
?		
? CollationMode.windows	// 0
? CollationMode.Clipper // 1  <-------
? CollationMode.XPP     // 1  <-------
? CollationMode.Unicode // 2
? CollationMode.Ordinal // 3
?
? CollationMode.windows:ToString():ToUpper() // WINDOWS		
? CollationMode.Clipper:ToString():ToUpper() // XXP  <--------
? CollationMode.XPP:ToString():ToUpper()     // XXP  <--------
? CollationMode.Unicode:ToString():ToUpper() // UNICODE
? CollationMode.Ordinal:ToString():ToUpper() // ORDINAL     

RETURN	  
```
Karl-Heinz

**Comment by cpyrgas** [comment]
Also the following (which does not directly call SetInternational()) returns 99, while in VO a value like 2 or 3 is returned, depending on the regional settings. Robert, I think the initialization code needs to take the active dialect into account

FUNCTION Start() AS VOID
? SetDateCountry()

**Comment by Karl1155** [comment]
Chris,

```
FUNCTION Start() AS VOID
? SetDateCountry()
RETURN
```

When i run your code an InvalidCastException is thrown, even when i set datecountry() before.

```
FUNCTION Start() AS VOID

SetInternational ( #clipper  ) 
SetCollation ( #clipper ) 	  

? SetDateCountry ( DateCountry.German )	 // 1
? SetDateCountry() // <------- InvalidCastException

RETURN
```

**Comment by RobertvanderHulst** [comment]
Karl,
This is a known problem, and fixed in the next build. Use RuntimeState.DateCountry in stead of SetDateCountry() for now.

Robert

**Comment by RobertvanderHulst** [comment]
W.r.t. the SetCollation and SetInternational(): you guys are reading too much in these values. I have added XPP as an 'alias' to Clipper. That's all. For XBase++ I have also added collation tables (which are selected with SetCollationTable() or SetCollation().  Nothing more and nothing less.
But since this is apparently confusing I will remove the alias for the next build.

SetDateCountry() is another thing related to Xbase++: they have an extra DateCountry option called "System". "SET DATE SYSTEM".  Check set.ch for the possible alternatives:
```
#command  SET DATE [TO] <x:AMERICAN,MDY>        =>  SetDateCountry(DateCountry.American)
#command  SET DATE [TO] ANSI                    =>  SetDateCountry(DateCountry.Ansi)
#command  SET DATE [TO] <x:BRITISH,FRENCH,DMY>  =>  SetDateCountry(DateCountry.British)
#command  SET DATE [TO] GERMAN                  =>  SetDateCountry(DateCountry.German)
#command  SET DATE [TO] <x:ITALIAN,DUTCH>       =>  SetDateCountry(DateCountry.Italian)
#command  SET DATE [TO] <x:JAPANESE,TAIWAN,YMD> =>  SetDateCountry(DateCountry.Japanese)
#command  SET DATE [TO] USA                     =>  SetDateCountry(DateCountry.USA)
#command  SET DATE [TO] <x:SYSTEM,WINDOWS>      =>  SetDateCountry(DateCountry.System)
```
I made two changes:
1) I have added an enum with all possible values (XSharp.DateCountry) and added System to this enum
2) Our SetInternational(#Windows) also sets the date format to match the format in the System, so I have changed the initialization code. When you call SetInternational(#Windows), which is the default btw, then the DateCountry system will reflect that and return the numeric value of 99. I know that this used to be different, but I think the current solution reflects better that the date format depends on the System. If you want to override that you can still do that, but you should do that after calling SetInternational(). 

I know that I can change the initialization code and make it 100% VO compatible, but who on earth (apart from you 2 guys) inspects the values returned from SetDateCountry() ?

**Comment by Karl1155** [comment]
Robert,

it was Chris who introduced SetDateCountry() - not me ;-), and I also didn ´t mention  SetInternational (#Windows) anywhere. I never used this setting in the past and I will not use it in the future.

But thanks for removing the confusing XPP alias.

Karl-Heinz

**Comment by cpyrgas** [comment]
Robert, hehe, well I did it because I am pretty sure there will be code available out there that does that somehow depends on it indeed. You know well how many times we have said "it is extremely unlikely this xyz is used anywhere", only to find it has been used in dozens of places when we release a new build :)

Karl-Heinz, yeah, sorry about the confusion, should had mentioned that we are using a new intermediate version of the runtime, in which this exception is fixed, but the new result is just not 100% compatible to that of VO.

**Comment by RobertvanderHulst** [comment]
Ok, I'll make that change for Xbase++ dialect only. The other dialects will have values 2 or 3 like before, depending on the format of the Date.

**Comment by RobertvanderHulst** [comment]
Ok, I rolled back that change. Unfortunately I can't easily make this dialect dependent, because this code is called from the class constructor of the RuntimeState and that is before the dialect gets set by the startup code in the Exe. When DateCountry is set in users code then of course the dialect is known and then the code can be dialect specific.
