### ISSUE TITLE
OS() returns different values than in VO

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#289]
On my machine, using VO:
`? OS() -> "Windows 10 Enterprise (x64) (Version 6.2, Build 9200)"`
`? OS(true) -> "Windows 10 Enterprise (x64) (Version 6.2, Build 9200)"`
Using X#:
`OS()->Windows NT`
`OS(true)->Microsoft Windows NT 6.2.9200.0`

And from the source the statements regarding Win32s and Windows 9x dan be removed.

**Comment by JamalAPI** [comment]
The X# OS() is not concise and lacks the information that VO functions returns. Look at the X# source.
Basically, it's using Environment.OSVersion which does not have all the info and incorrect!

lExtended paramater is useless since it does not do anything in VO.

My replacement function is below. It uses Environment.OSVersion, the Windows registry and environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE") to get the information we need. Also passing false in lExtended returns just the OS product name.

On my system, my OS function returns:
? OS() ->       "Windows 10 Enterprise (x64) (Version 6.2, Build 9200)"
? OS(true) -> "Windows 10 Enterprise (x64) (Version 6.2, Build 9200)"
? OS(false) -> "Windows 10 Enterprise"

using Microsoft.Win32
using System

function OS(lExtended) as string
	local os as OperatingSystem
	local registryKey as RegistryKey	
	local pa as string
	local osBits as Long
	local cOS as string	
    
    if lExtended = NIL
         lExtended := true
    endif
        
	registryKey := Registry.LocalMachine:OpenSubKey("Software\\Microsoft\\Windows NT\\CurrentVersion")
	cOS := (string)registryKey:GetValue("productName")  
    if lExtended
        os := Environment.OSVersion
	    pa := Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE")
	    osBits := IIF(((string.IsNullOrEmpty(pa)) .OR. (string.Compare(pa, 0, "x86", 0, 3, true) == 0)) , 32 , 64)
	    cOS += " (x" + osBits:ToString() + ") (Version " + os:Version:Major:ToString() + "." + os:Version:Minor:ToString() + ", Build " + os:Version:Build:ToString() + ")"
    endif
     
    return cOS    

Jamal

**Comment by wriedmann** [comment]
Hi Jamal,
personally I have never used the OS() function as I have my own version of it, and it returns also the current .NET Framework version as this is important now. I had only received a question from another programmer about the incorrect results.
The OS() function should only be changed from the actual state.
I have to admit that my WIndows 10 is not an Enterprise version, but a Professional only, so even VO is wrong.
Wolfgang

**Comment by wriedmann** [comment]
Hi Jamal,
my version is much longer (too long to paste here), and returns also if running on a remote session or not, but has the problem that if the application is not manifested as compatble to Windows 10 it returns always Windows 8.0.
Wolfgang

**Comment by RobertvanderHulst** [comment]
Jamal, Wolfgang,
I will look at this later.
But I can already tell you that I will try to avoid calling the registry here because that is not supported on Non-Windows platforms.

Robert

**Comment by JamalAPI** [comment]
Hi Wolfgang,
Something weird which I just discovered which is caused project's Build tab, **Prefer 32-bit**.  I had the code running in X# and C# and was I getting different values from registryKey:GetValue("ProductName"). So, I went on the hunt.
If Prefer 32-bit is selected, the registryKey:GetValue("ProductName")  returns Windows Enterprise, otherwise, it returns Windows 10 Pro. 

Jamal

**Comment by RobertvanderHulst** [comment]
I have added the suggested improvements to the runtime when running on Windows.
