### ISSUE TITLE
Eval() of a string  representing an expression results in "Argument is not a codeblock' exception [FoxPro]

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#381]
In FoxPro, the Eval() function takes a string that contains a reference to an in-scope variable, Object.Property reference, or even a Function() call, and returns the value of the referenced expression.

In X# we get a run-time exception:

**XSharp.Error: 'Argument is not a codeblock'**

In FoxPro an exception is thrown if the passed expression cannot be evaluated.

BTW - EVALUATE() is the full function name, but people often use the shorter name EVAL() which is valid also.

```
Function TestEvalOnVarReference As Void

	Var cName = "Billy Smith"

	Var cRef = "cName"
	
	? EVAL(cRef)  // Should print "Billy Smith", but gives an exception

	? Evaluate("Date()")  // Another example, making a Function call

	Wait

	Return 

End Function
```

![2020-04-29 13_37_18-Window](https://user-images.githubusercontent.com/309016/80633638-b47d8b80-8a1e-11ea-8f78-68f385679f74.png)

**Comment by RobertvanderHulst** [comment]
Matt,
Like in ticket #382: VAR creates a local and this name is not available at runtime. However if you change this to PRIVATE then it does not work too because there is an Eval() function that is a VO compatible Eval() function that expects a codeblock. We also have Evaluate() that does what you want.
Evaluate() compiles the string into a codeblock with the macro compiler and then executes that codeblock. 
Abbreviating functions to 4 characters may sound like a cool feature but is a very bad idea I think.
I know, many people have used this, but this will only work in an environment with a limited set of functions.

```
Function Start As Void
	PRIVATE cName = "Billy Smith"
	Var cRef = "cName"
	? Evaluate(cRef)  // Prints "Billy Smith"
	? Evaluate("Date()")  // Another example, making a Function call
	Wait
	Return 
End Function
```

**Comment by RobertvanderHulst** [comment]
This should work now when the /fox2 compiler option is enabled and when the Evaluate() function is used
