### ISSUE TITLE
Macro substitution &ObjectRef..Property gives compiler error XS9002 'Unexpected input'

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#382]
In FoxPro we can use macro substitution for an object reference or a WorkArea/Cursor and then further reference a property or field on the object/cursor, if we use this off syntax of using *two* dots between the macro part and the field/property name.

`&ObjectRef..Property`
or
`&CursorRef..Field`

In X# this gives a compiler error XS9002 Parser: unexpected input '.'

Here is a code sample to reproduce this error:

```
*---------------------------------------------------------------------------------
Function TestMacroSubstitutionOnObject As Void

	Var oPerson = Empty{}
	AddProperty(oPerson, "Name", "Ralph Adams")
	
	Var cRef  = "oPerson"
	
	? &cRef..Name // Should print "Ralph Adams", but gives Compiler error XS9002: Unexpected input '.'

	Wait

	Return 

End Function
```
X#: 
![2020-04-29 14_00_29-Window](https://user-images.githubusercontent.com/309016/80635984-5783d480-8a22-11ea-91ab-a8a9956ec81c.png)

FoxPro:

![2020-04-29 14_01_18-NoMachine - DogFace, macOS 10 14 6](https://user-images.githubusercontent.com/309016/80636009-623e6980-8a22-11ea-852a-333e8e254aff.png)

**Comment by RobertvanderHulst** [comment]
Matt,
`Var oPerson = Empty{}`
This declares a LOCAL variable with the name oPerson. This variable is lexically scoped just like local variables declared with LOCAL.
The name of the variable is not known at runtime. You will therefore **NOT** be able to access this variable by name outside of the scope of this function, so also not when using the &cRef construct.

If you change the code to:
```
Function Start As Void
	PRIVATE oPerson = Empty{}   // Note that I changed VAR to PRIVATE
	AddProperty(oPerson, "Name", "Ralph Adams")
	Var cRef  = "oPerson"
	? &cRef..Name // Should print "Ralph Adams", but gives Compiler error XS9002: Unexpected input '.'
	Wait
	Return 
End Function

```
And compile with the option to allow memvars then (with my current build) this will work as expected and the name "Ralph Adams" is returned.

**Comment by mattslay** [comment]
Robert - changing the var to Private is a convenient way to make this code sample run, but just be aware that in an example FoxPro app there could be dozens, even a hundred places where people will use this code pattern with LOCAL vars, and I'm not sure they will be willing to just change all those variable references to PRIVATE.  I guess we just have to wait and see what kind of issues result from this X# vs VFP difference.

**Comment by RobertvanderHulst** [comment]
Matt
I am sure this will cause problems, but there is no way this can work in a real compiled language.
The variable names for local variables are not available at runtime.
I think I have said this before, but I’ll repeat it here, the only way this can work in foxpro is because foxpro “cheats” and implements locals as a special kind of memory variables.
In theory we could do that too but that does not feel right.

**Comment by RobertvanderHulst** [comment]
I understand that there are situations where you want to make “dynamic” code that behaves differently under different situations and that this construct helps.
The alternative for referring locals by name is the use of code blocks ( in clipper and its many successors) or in  dotnet the use of lambda expressions. That is what I would recommend.

**Comment by cpyrgas** [comment]
Robert, would a compiler option that makes LOCAL a synonym to PUBLIC work, or will it be more complicated than that? Of course changing LOCALs into PUBLICs will give a big performance loss and is a big step backwards, but if that does make the code backwards compatible for the people that want it this way...

**Comment by RobertvanderHulst** [comment]
Chris, 
Making a local a synonym to PUBLIC does not work because a new local in a function could then overwrite a local declared in a function above. Plus the fact that Publics are not typed.
We could make local indeed a synonym for PRIVATE (I am sure that FoxPro has implemented it like that, and that is why they are not typed in VFP) but then again, then we lose the typing.

The only way that something like this could be implemented in .NET without sacrificing strong typing would be something in the line of:

```
Function TestMacroSubstitutionOnObject As Void
        // compiler generates something like this to inform the 
        // runtime about the locals in this function
        local _listOfLocals as _ListOfLocals
        _listOfLocals := _ListOfLocals{}
        _RegisterLocalsForRuntime(_listOfLocals)
 
	Var oPerson = Empty{}
	// we can't register the locals before they are actually instantiated  
        // so we do it now
         _listOfLocals.Add("oPerson", {|x| iif(PCount() == 0, oPerson, oPerson := x})
        AddProperty(oPerson, "Name", "Ralph Adams")
	
	Var cRef  = "oPerson"
        _listOfLocals.Add("cRef", {|x| iif(PCount() == 0, cRef, cRef := x})
	
	? &cRef..Name // Should print "Ralph Adams", but gives Compiler error XS9002: Unexpected input '.'

	Wait
         // we have to tell the runtime that the locals are no longer in scope
        _UnRegisterLocalsForRuntime(_listOfLocals)

	Return 

End Function
```

This looks somewhat like the way how privates are implemented but still allows us to use strong typing for the variables. 

And then when code references a local by name we could walk the list and find the local and evaluate the codeblock attached with it to get its value. The codeblock is needed so we can also update the local (like in locals passed by reference to a SqlExec().
We could probably extend the code that keeps track of privates to also hold the names and codeblocks of the locals. So inside the macro compiler a "Get Memvar" or "Put Memvar" would also be able to see the names of the locals.

To make this work reliably the _UnregisterLocalsForRuntime would have to go to a FINALLY block of a TRY ENDTRY to make sure that the variables are also deregistered in case of an error.
Something similar is done already to cleanup private variables.

What would not work is scoped locals, such as locals inside a block or locals declared as loop iterator, unless we also add code that removes them.That would then look like

```
FOREACH VAR oCustomer in aCustomers
    ... do something()
NEXT
```
would become

```
FOREACH VAR oCustomer in aCustomers
_ListOfLocals:Add("oCustomer", {|x| iif(PCount() == 0, oCustomer, oCustomer := x})
// The collection should be smart enough to detect a redefine and overwrite the previous one
// or we need to add code to detect that we are inside the loop for the first time
NEXT
_ListOfLocals:Remove("oCustomer")
```

So, yes, technically this can be done. But is this really what we want ?

**Comment by cpyrgas** [comment]
Well, it's not only what we want, it's also what the users want :). So if some people just want some way to port their apps without changing a lot of their code and do not care (at least in the beginning) about some of the language improvements, I would just go ahead and give them an options to make LOCALs not locals anymore but privates as you said, so they would not be typed anymore indeed, but old code would continue to work.

I mean, also for VO, we keep supporting USUALs, while we could had told VO developers that USUALs are not to be used anymore, everything must be strongly typed, like it should be and how it is everywhere in .Net (well, the fact that MS later changed that and moved many years back to the past when they introduced DYNAMIC is another story :) ). But we did keep supporting USUALs, for backwards compatibility...

**Comment by RobertvanderHulst** [comment]
Ok,
I am willing to give this a try, since it actually makes the implementation of the parameterized Sql functions also a bit easier.

What I will do is:
- Add a new /fox2 commandline option. Description of this option is "Make locals visible by name to the runtime"
- This option HAS to be combined with /memvar (they both need the same infrastructure). That way I can use the current mechanism used to specify the lifetime of privates to also specify the lifetime of locals.
- Reading/Writing of Locals will go through the same function MemVarGet and MemvarPut that are already available in the runtime
- The list of Locals will be added to the MemVarLevel class (see https://github.com/X-Sharp/XSharpPublic/blob/master/Runtime/XSharp.RT/Types/MemVar.prg)
- I will add a function __LocalRegister() to the runtime that takes a name and codeblock to register the local and __LocalUnRegister() to unregister the local.  Behind the scene this puts the info in the MemVarLevel class just like name/value pairs for privates are registered 
- The current code in MemVarLevel  looks for privates first and then for publics. I will insert looking for Locals before the search for privates.
- And the compiler will generate code to register (and unregister) local variables after they are declared.
How does this sound ?

**Comment by cpyrgas** [comment]
Makes perfect sense to me! Let's see now if there's some stumbling block when actually implementing this in practise...

**Comment by RobertvanderHulst** [comment]
It looks promising.
I have wrote a first version of the runtime code and this now compiles and does what you expect:
```
FUNCTION Start as VOID
	TestMacroSubstitutionOnObject()
	RETURN
Function TestMacroSubstitutionOnObject As Void
	Var oPerson = Empty{}   
	__LocalRegister("oPerson", {|x| iif( IsNil(x) , oPerson, oPerson := x)})
	AddProperty(oPerson, "Name", "Ralph Adams")
	Var cRef  = "oPerson"
	? &cRef..Name // Prints "Ralph Adams"
	&cRef..Name := "Robert did it"
	? &cRef..Name // Now prints  "Robert did it"
	Wait
	Return 
End Function
```
With debugging you can actually see the debugger step into the codeblock when accessing or assigning the ..Name property. And the local is on the stack and of type Empty.
Of course behind the scene Roslyn generates a special class to hold the oPerson local for this function (since it does not know what the scope of the codeblock is, so it must assume this could become a 'detached local'. But Roslyn is doing that for all codeblocks that refer local variables, so that was to be expected. And both the VS and XIDE debugger are aware of that and are displaying oPerson as a normal local variable.

**Comment by cpyrgas** [comment]
Oh that's very nice, looking very good!

And I had not realized you had already implemented the double dot syntax, just tried it in the previous build and it works, nice!

**Comment by RobertvanderHulst** [comment]
I’ll try to build this into the compiler tomorrow and will send you a new compiler to play with. I’ve also fixed the bracketed string problem with attributes in the core dialect, so you can test that too.

**Comment by mattslay** [comment]
**Robert** - is this code line something that the FoxPro developers must *add* to their code, or is this something you can do behind the scenes in the compiler?  My whole point of pushing back on this is so that there is some way VFP code will simply run "as-is" without people having to edit their existing code in hundreds of places.

`__LocalRegister("oPerson", {|x| iif( IsNil(x) , oPerson, oPerson := x)})
`

Chris has the right idea that, yes, supporting all their old VFP crazyness, they may miss some of the goodness or even speed of new X# features or strong typing, but they won't care about all that in the beginning.... They just want to see their code compile and run as-is, or else some VFP people won't be willing to give X# a serious look if it requires too many code chanhges.

**Comment by RobertvanderHulst** [comment]
Matt

This is something the compiler will generate automatically when a certain ( new) compiler option is enabled. But before changing the compiler I wanted to try this in code to see if it works.
It could have kept  the discussion between Chris and me hidden but decided to keep it in the open, with the risk that it might confuse people, like it apparently does now.

Well, my conclusion is that it works, that it adds some overhead ( registering the local has to be done once for each local) but it does not negatively influence performance.

Converting all locals would certainly have a negative impact on performance and would also require a similar function call to declare the private variable.
So the user does not have to make  code changes ( only enable a compiler option).
If you would look at the generated IL you would see the generated code to register the locals.

**Comment by mattslay** [comment]
> ... So the user does not have to make code changes ( only enable a compiler option).

Perfect!

**Comment by mattslay** [comment]
Robert - will this new compiler handling idea of your help with implementing the two VFP runtime functions EVL() and NVL()??

**Comment by RobertvanderHulst** [comment]
Matt,
No. EVL() and NVL() take values and do not evaluate variable names as far as I know. 
But it will effect TYPE() and EVALUATE() and also SqlExec()/SqlPrepare() with embedded parameters.
TEXT/ENDTEXT and the parameters in <<>> are handled at compile time, so there is no need to "expose" local variables to the runtime there.

**Comment by lazy-fox** [comment]
Hi Guys,
I had been chiseling a similar concept to keep variable names for Eval() and Type() in the back of my head - was not set at each function level, but in an array mirroring current stack level, as I was not certain that execution context would be at max 1 level away, for instance if macrocompiling a call to eval() - and here you already have a working solution, so delete mental model...
I am a bit worried at the all-or-nothing approach of enabling with a command line option and had similar worries for my approach. My first idea was To build some logic en- and disabling such enhanced compiler behaviour via preprocessor and predefined markers. Benefit: can stay in code running on xSharp and vfp with a little foresight, ability to locally  switch additional overhead on and off. Drawback: simple on and off switches might lag and get out of synch, resulting in more code having slowdown.
Next idea: add a new function type where local names are saved during compilation.
Perhaps appending "_Dyn", "_Mem" or "_vfp" to "function" and "procedure" to signify that in that "function"  the local names go via that special name bag. Benefit: Easy to understand, easy to let code so changed run in vfp (just #define Function_Vfp Function when running vfp), granularity at function level giving the option to "break out" code parts not needing such functionality into subroutines if perf suffers on existing long functions. Needs fixes to existing code, but is a one-shot affair if developers get used to the idea and the places can be pinpointed by the error (name is in string and invisible to compiler) or compiler warnings.
Last idea: why stop there ? Do not work on function level, but create a new variable type:
TWocal (read twisted local...) which is the local with the twisted ability to be used in Eval, Type, Macrocompiler and probably a few other places. Benefits: best granularity (only those locals needing their names for such gymnastics are slowed down, structure is injected only in functions needing it), easy to port back to vfp (#define TWocal Local), probably easier to explain to developers. Drawback: more work by changing Local to Twocal for each such variable when compared to "new function type".

Gut hunch here is that implementing the "function type" idea is probably easiest to switch to given from the things I imagine needed to be already implemented if deciding via /fox2 switch.
Of course, if perf is not much slower with /fox2 switch enabled, those ideas can be scrapped as well.

regards
thomas

**Comment by RobertvanderHulst** [comment]
For now we consider this "implemented". If later tests show that the runtime performance needs extra work then we'll open another ticket
