### ISSUE TITLE
Implement SCATTER and GATHER commands in VFP Dialect

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#387]
I feel like SCATTER and GATHER are 2 very essential pieces of basic FoxPro language commands that many people would find missing early in their X# exploration and the perception of X#.VFP They may dismiss it too early as a viable thing worth continued exploration.

**Comment by mattslay** [comment]
June 2020 milestone??

**Comment by RobertvanderHulst** [comment]
Matt,
Do you know if `SCATTER MEMVAR ` creates Public or Private variables? In the command window the variables are always Public but is that also the case when you run this in a function or procedure ?

**Comment by mattslay** [comment]
It appears to create them as PUBLIC.

See this test code I wrote to make this determination.  If they were only PRIVATE, I believe it would only be in scope withing Proc_One(), yet as this test shows, the vars can be referenced from the call to Proc_Two()



```
Clear All

Proc_One()

Proc_Two()


Procedure Proc_One

	Select 0
	Use wwBusinessObjects Shared
	
	Scatter Memvar
	
EndProc


Procedure Proc_Two

	 ? cFilename
	 
EndProc

```


![2020-08-25_12-03-55](https://user-images.githubusercontent.com/309016/91205765-b1906000-e6cb-11ea-88ff-5b3d3e608dd8.png)

**Comment by atlopes** [comment]
Matt, the string that is displayed comes from the table that is open, not from a memory variable. If you issue "? m.cFilename" instead of "? cFilename", you'll see that there is no cFilename variable in scope.

Trying to answer Robert's question as comprehensible as I can: scattered variables are PRIVATE unless previously declared as local, in which case they become LOCAL (that's the regular behavior of VFP in similar circumstances when a variable is created implicitly by some command like the assignement command, DIMENSION, ALINES, and so on).

`
CLEAR

Test_Public ()

Test_Scope ()

Test_Private ()

Test_Local ()

PROCEDURE Test_Public ()

	CREATE CURSOR SampleData (Filename Varchar (200), OtherField Logical)

	INSERT INTO SampleData VALUES ('Quotes', .T.)

	SCATTER MEMVAR MEMO

	? "Test public"

ENDPROC


PROCEDURE Test_Private ()

	SCATTER MEMVAR MEMO

	? "Test private"

	Test_Scope ()

ENDPROC

PROCEDURE Test_Local ()

	LOCAL Filename AS String

	SCATTER MEMVAR MEMO

	? "Test local"
	
	Test_Scope ()

	? "Test private for non-declared locals"

	Test_Scope_Other()

ENDPROC

PROCEDURE Test_Scope ()

	TRY
		? "Variable:", m.Filename
		? "There is a Filename variable in scope"
	CATCH
		? "There is no Filename variable in private or public scope"
		? "Field:", Filename
	ENDTRY

	? "==============="

ENDPROC

PROCEDURE Test_Scope_Other ()

	TRY
		? "Variable:", m.OtherField
		? "But there is an OtherField variable in private or public scope"
	CATCH
		? "There is no OtherField variable in scope"
		? "Field:", Filename
	ENDTRY

	? "==============="

ENDPROC

`

![image](https://user-images.githubusercontent.com/27675705/91210845-b8d45f80-e705-11ea-9d08-16012b3c257a.png)
