### ISSUE TITLE
Special default argument for PTR type leads to XS7038 error (Failed to emit module)

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#392]
Consider function prototype:

`FUNCTION ScrBits(hDevice := HWND_DESKTOP AS PTR) AS DWORD PASCAL`

It leads to **XS7038 error (Failed to emit module)** without an error/warning on this particular line. A very hard-to-find mistake.
If you change HWND_DESKTOP to NULL_PTR, everything is fine.

**Comment by cpyrgas** [comment]
Confirmed. Robert, here's a repro:

DEFINE HWND_DESKTOP := PTR(_CAST,0)
FUNCTION ScrBits(hDevice := HWND_DESKTOP AS PTR) AS DWORD PASCAL
RETURN 0

When compiling this with /vo7- (disabled), then there's a compiler error, with text which does not look right: error XS1503: Argument 1: cannot convert from 'PTR' to 'object'

When enabling /vo7+, then as Serggio said, the Failed to emit module is thrown

**Comment by RobertvanderHulst** [comment]
In the current compiler build this now produces an error XS0182 (attribute argument must be a constant) on the line where HWND_DESKTOP is used as default value. We will also try to fix that, but this at least helps to find the line where the problem is. (Explanation: compiler 'encodes' default values as attributes on the parameter).

**Comment by nvkokkalis** [comment]
Surprisingly, these few lines of code cause several issues internally.

Robert, I started by trying to make this work with `NULL_PTR`. The following failed, though:

`DEFINE HWND_DESKTOP := NULL_PTR`

because `NULL_PTR` is resolved to `IntrPtr.Zero`, which is not a const. I've managed to work around that by tricking the compiler into considering it a const with the value `(int)0`. So far this works (but please check it as well).

Moving on, however, allowing `HWND_DESKTOP` to be passed as a parameter default value does not work because an `IntPtr` cannot be bound as an attribute argument (and the X#-style default arguments are bound very early, when the type of `HWND_DESKTOP` is not known). I will examine that further.

Note that I have not yet touched upon the `PTR(_CAST,0)` part...

**Comment by nvkokkalis** [comment]
I made some progress towards making this work with `NULL_PTR`. The following code should work now:
```
DEFINE HWND_DESKTOP := NULL_PTR
FUNCTION ScrBits(hDevice := HWND_DESKTOP AS PTR) AS DWORD PASCAL
RETURN 0
```

Now `HWND_DESKTOP` is resolved to a `const IntPtr`, which is not normally allowed by the C# binding rules but is supported by the CLR.

The awkward `PTR(_CAST,0)` construct still does not work. I will examine it next.
