### ISSUE TITLE
Type checking for PTR and PSZ

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#398]
Disclaimer: In no case this is an urgent bug or something super serious, but nevertheless I think it's worth to consider.

```	
	LOCAL tTempVar AS OBJECT // meaning universal type
	
	IF tTempVar IS PSZ VAR pszVar
		.... 
	ENDIF
```
this code leads to *XS7038 Failed to emit module*.

and this code
```
	LOCAL tTempVar AS OBJECT // meaning universal type
	
	IF tTempVar IS PTR VAR ptrVar // this time it is PTR
		.... 
	ENDIF
```
leads to *XS0244 Neither 'is' nor 'as' is valid on pointer types*.

If PSZ/PTR is changed to any other type (INT, DATE, LOGIC, class, etc.), everything's fine.

**Comment by nvkokkalis** [comment]
Unfortunately, implemeting this is problematic.

First, when PSZ is assigned to OBJECT, it is converted to IntPtr due to its special conversion rules, so the type information is lost. As such, it cannot be assigned to a more generic type to allow the IS operator to work.

On the other hand, in the dotNET CLR, pointer types do not inherit from OBJECT or any other class, so PTR cannot be used with the IS operator. Additionally, when a pointer is assigned to OBJECT it is not boxed. Instead it is converted to IntPtr and then boed (so type information is lost).
