### ISSUE TITLE
Evaluating a codeblock that returns NIL assigns the wrong usual type for the return value

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#418]
In the following code, VO prints:

.T.
0
NIL

while x# prints

.T.
6
{(0x0000)0x00000000} CLASS

```
FUNCTION Start() AS VOID
LOCAL cb, uResult AS USUAL
cb := &("{ || NIL }")
uResult := Eval(cb)
? uResult == NIL 	// TRUE, ok
? UsualType(uResult)// 6 (OBJECT), wrong, should be 0
? uResult 			// "{(0x0000)0x00000000} CLASS", should be "NIL"
```

**Comment by RobertvanderHulst** [comment]
Chris,

The problem comes from the fact that we have modeled the macro compiler like how Don modeled the macro compiler for Vulcan. The EvalBlock method in the ICodeblock interface takes an array of objects and returns an object. Inside our macro compiler when returning NIL the macro compiler therefore calls the ToObject static method in the Usual Type to convert the usual to an object. And this method converts NIL values to NULL.

Later this NULL is converted to a USUAL again and inside the USUAL constructor we are translating a NULL to type OBJECT.

So my first thought was to fix this in the runtime. I see 2 solutions:
1) We change Usual.ToObject to not return NULL for NIL values
2) We change the USUAL constructor to not set the type to OBJECT when called with a NULL value.

But I am afraid both of these solutions will have a lot of side effects.

Of course the alternative would be to change ICodeBlock() to take a USUAL array and return a USUAL but that means:
- moving the relevant types outside from XSharp.Core to XSharp.RT
- probably a lot of changes to the compiler for the compile time codeblocks
- probably a lot of changes to the macro compiler for the runtime codeblocks.
This would then definitely break backwards compatibility with previous X# builds so we would have to increase the assembly versions on all our assemblies.

**Comment by cpyrgas** [comment]
Robert,

Thanks for the info, I think it's better to leave it as it is then, at least for now. It's Arne who has reported this issue, and has already told me it is not a big problem for him, just did not feel right. I will point him out to your reply.

**Comment by RobertvanderHulst** [comment]
Fixed
