### ISSUE TITLE
2.5a chm help issues

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#433]
When i click on the [view source] button of e.g. the VFP DMY() function the .../XSharp.VFP/Functions.prg is opened instead of the ../XSharp.VFP/DateFunctions.prg. The same happens in other cases:

e.g. CDX() location is .../XSharp.VFP/Cursors/DbFunctions.prg
e.g. File2Str() location is .../XSharp.VFP/FileFunctions.prg
e.g. ForceExt() location is .../XSharp.VFP/StringFunctions.prg

I also noticed that for functions in other namespaces like ASC (), PadR () etc. no [view source] button is shown at all.

i installed the XSharpSetup24aFox.exe and there are no such chm problems.

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
We are using a tool (Sandcastle Help File Builder, SHFB) to generate these docs. This tool reads the public types and methods of the assemblies, reads the PDB files and XML files and creates the docs , based on XSL templates.

The tool does not "know" about functions, so it sees all our functions as static methods in the Functions class. 
We have written an add-in that detects that the static methods (and fields) are in the Functions class and document them then as Function, Global and Define. We have also written an add-in so the prototypes are in X# format.

I am not sure what the problem is, but apparently SHFB has problems determining where the functions are located.
And I am not really looking forward to debugging someone else his code.
So this will get a low priority, I am afraid.

Robert

**Comment by Karl1155** [comment]
Robert,

i agree, there are more important things to do. But i´m wondering: What has happened since the build 2.4 ? As i wrote, i installed the 2.4a build ( XSharpSetup24aFox.exe )  and the "functions" [view code] buttons are there and the jumps are (almost) correct. The only problem is, that the line param gets lost somehow. For example: the Asc() url points to https://github.com/X-Sharp/XSharpPublic/tree/feature/Runtime/Runtime/XSharp.Core/Functions/String.prg#L22, but there´s no jump to the line 22. When i look at the current Browser location it shows: https://github.com/X-Sharp/XSharpPublic/tree/feature/Runtime/Runtime/XSharp.Core/Functions/String.prg only.

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
I think I know what happened. For the doc generation we have a special "secret" compiler option (so the parameters for Clipper calling convention are compiled as 'normal' parameters with the type USUAL, since SHFB does not understand the Clipper calling convention).
In preparing for 2.5 we have added an implicit /refonly command line option for this compiler option to make sure that the assemblies produced with this special command line option cannot be used in real life.
That /refonly commandline option "kills" all bodies in the assembly and removes private and internal fields/methods. 
I think this also removes line information from the generated PDB.

Robert

**Comment by RobertvanderHulst** [comment]
Fixed
