### ISSUE TITLE
Error class exception

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#468]
The following code throws an exception when reading the Description property:
```
LOCAL e AS USUAL
LOCAL cErrMsg AS STRING
	
BEGIN SEQUENCE
    IF TRUE
        THROW Error{"test"}
    ENDIF
RECOVER USING e
    IF e IS Error VAR oErr
        cErrMsg := oErr:Description // throw exception
    ENDIF
END SEQUENCE
```

Exception: _value in USUAL does not support indexed operations. The value needs to be an X# Array or implement the interface XSharp.IIndexedProperties_.

**Comment by RobertvanderHulst** [comment]
Leonid,
This looks like a problem in the `<usualVar> IS <SomeType> VAR <localvar>` construct.
What happens is that instead of that the object inside of the USUAL is assigned to the local variable, the compiler boxes the usual in an object and it assigns that object containing the usual to `<localvar>`
For now use this instead:
```
IF e IS Error 
   VAR oErr := (Error) e

```

Robert

**Comment by leon-ts** [comment]
Robert,

This also works:
`IF (OBJECT)e IS Error VAR oErr`
I left it that way for now.

**Comment by nvkokkalis** [comment]
The USUAL was boxed in this case, so no proper conversion was done.
I have added a special case for USUAL to avoid this and convert it correctly.
Commit #ed86d49f6 should fix this.
