### ISSUE TITLE
Cannot open projects due to corrupted ".vs" folder contents

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#517]
In the attached solutions, something has gone wrong (while testing VS integration changes) and the contents of the ".vs" folder have been corrupted, leading to showing the projects as "unavailable" when loading the solutions. Deleting the .vs folder allows loading the projects again.

This makes it very difficult to understand what the problem is, so I think that the corrupted .vs situation should be trapped and a message should be disabled (or corrupted contents be automatically deleted?) and projects I get can still be loaded.

[VOMDIApp5.zip](https://github.com/X-Sharp/XSharpPublic/files/5515293/VOMDIApp5.zip)
[VOMDIApp6.zip](https://github.com/X-Sharp/XSharpPublic/files/5515295/VOMDIApp6.zip)

**Comment by RobertvanderHulst** [comment]
Chris,
There is nothing wrong with the .vs folder contents.
Apparently you previously loaded the solution when you had a non working VS project system for X#.
The projects were then marked as "incompatible" and this setting is saved in the .vs folder.

When you reopen the solution later, VS tries to restore the situation just like it was when you closed it, so this marker is restored as well. However when you right click on the project and choose "Reload project" then the project is loaded correctly.
The same thing happens when you choose to Unload a project and close the solution. When you reopen the solution then the project is still unloaded.
To detect that the project state was incorrectly marking a project as "incompatible" would mean that we have to parse the .suo file in the v15 or v16 folder. However, that file format is not documented and different between various versions of VS.

Robert

**Comment by cpyrgas** [comment]
Ah, right, "reload project" does fix it. I would swear that this did not work in the projects of the VSIntegration solution itself though, although I cannot prove it anymore :)

Indeed, I had made a mistake and the voeditors were throwing an exception when I was testing with those projects.
