### ISSUE TITLE
 Suboptimal code generation when comparing with NULL_PSZ and NULL_SYMBOL

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#544]
When comparing a PSZ variable with NULL_PSZ the generated IL-code is such (C# syntax):
`if (pszTestVariable == new __Psz((IntPtr)0))`
which in fact is creating an object.

At the same time, comparing this variable with NULL_PTR generates a much more efficient code:
`if (pszTestVariable == default(__Psz))`
which is optimal, because default for a class type is just null, so there is no creation of an object.

The same issue is with comparing a SYMBOL variable with NULL_SYMBOL:
`if (Xs$SymbolTable._test == new __Symbol(""))`
There is no need to create an instance of __Symbol here. `Default(__Symbol)` would be fine, because this is exactly the same value that symbol variables have by default.

**Comment by cpyrgas** [comment]
Serggio, the __Psz type is a STRUCTURE (value type), not a reference type and it actually consists of one single field (a pointer). So not only there's no GC activity involved with it, but even more, "constructing" this object is the direct equivalent of defining a single LOCAL var of type UInt32 or UInt64 and assigning to it the value of zero. I suspect that the JIT compiler translates this code to only 2-3 simple machine code operations.

**Comment by Serggio** [comment]
Chris, thank you for the prompt response!
You have rather calmed me down, though I still think, there is a needless call to constructor, while `null` would be a better choice. I mean, comparing the same variable with NULL_PTR leads to `default(__Psz)`, why not to make it the same with NULL_PSZ?
Same with SYMBOL and NULL_SYMBOL.

**Comment by cpyrgas** [comment]
Serggio,
That's just an implementation detail which has to do with the different datatypes and the need to follow the CLR rules, not sure exactly why Robert implemented it this way, but I know he experimented with different stuff for supporting PSZ before concluding to this one.

Please note that the dissasmbler tools try to by smart in translating code to a high level language source code, and what you get is not necessarily what it really is :). In order to understand exactly what code is being emitted by the compiler, you need to see the code in IL format, not in c#. And if you do it, you will see that the actual code is practically the same for both NULL_PTR and NULL_PSZ, considering that the only thing that calling the PSZ constructor does, is to assign 0 to the internal field. It simply assigns zero to a memory location and the code for NULL_PTR does the same thing as well. And most probably this constructor call is being inlined to only a single instruction in the generated CPU code.

**Comment by RobertvanderHulst** [comment]
Sergio, Chris,
Interesting discussion.
There may be room for improvement here. 
However, I think more improvements can be made by avoiding the use of PSZ in your code: change Win32 API declarations and mark the string types AS STRING and add the proper ANSI or UNICODE modifier to the declaration.
For example change
```
_DLL FUNCTION MessageBoxEx(hwnd AS PTR, lpText AS PSZ, lpCaption AS PSZ, uType AS DWORD,;
	wLanguageId AS WORD) AS INT PASCAL:USER32.MessageBoxExA
```
to 
```
_DLL FUNCTION MessageBoxEx(hwnd AS PTR, lpText AS STRING, lpCaption AS STRING, uType AS DWORD,;
	wLanguageId AS WORD) AS INT PASCAL:USER32.MessageBoxExA ANSI
```
The ANSI keyword will make sure that the DllImport attribute that is generated will include Charset := Charset.Ansi .
Of course you can also use UNICODE if you call MessageBoxW (which you should probably do).

Now the creation of the Ansi strings and managing of the lifetime of these strings is moved from our runtime to the marshaling code in the framework 
And our code looks much cleaner since you can pass "normal" strings and you no longer have to use String2Psz().

**Comment by Serggio** [comment]
Robert, your advice concerning Win32-calls is very useful. Thank you!
