### ISSUE TITLE
WinForms designer generates wrong assignment for char properties

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#550]
**Describe the bug**
When assigning a char property in the winforms designer, the generator generates code, that causes the error XS0029 (Cannot implicitly convert type 'string' to 'char').

**To Reproduce**
1. Create a winforms project
2. Open the winforms designer
3. Add a TextBox
4. Assign the value \* (or any other character) to the PasswordChar property
5. The designer generates the assignment ``` SELF:textBox1:Properties:PasswordChar := '*' ```
6. Compile the project, you get the error XS0029

**Expected behavior**
The designer should generates the assignment ``` SELF:textBox1:Properties:PasswordChar := c'*' ```

**Desktop (please complete the following information):**
 - OS: Win10
 - Visual Studio Version: 2019 (16.8.3)
 - X#: 2.7

**Comment by cpyrgas** [comment]
Confirmed, when the dialect used is VO, then the designer still generates the constant as 'a'. Since the parser already supports the c'a' syntax, I think it's best to always generate the code this way, no matter the dialect. Attached sample form:

[WindowsFormsApplication17.zip](https://github.com/X-Sharp/XSharpPublic/files/5766565/WindowsFormsApplication17.zip)
