### ISSUE TITLE
Runtime/compiler problem with Mod() function and USUAL/FLOAT params

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#571]
[Reported by Arne Ortlinghaus/Infominds]

As shown in the sample below, the Mod() function returns incorrect results compared to VO, depending on the types of the arguments. This happens because in some cases the overload with INTs gets picked by the compiler, instead of the one with REAL8s, thus truncating the actual values.

Not sure if this is a good idea to handle it in the compiler, looks to me like it's probably better to handle it in the runtime, by removing the 3 overloads and replacing it with a single one, with USUAL params (as in VO). Of course this is a breaking change though, which will require rebuilds of all 3rd party tools and we may want to wait a bit longer for this.

Note though that there's an additional problem, depending on the value type that "u" holds, this code returns different results in VO:

u := 3.0
u := 3
UsualType(Mod(u,2))

If u has an INT value of 3, then the result is an INT 1. But if it holds a FLOAT 3.00, then the result is also FLOAT 1.00. 

If we do want to provide VO compatibility also for this case, this cannot be done at all with the current solution with the 3 overloads and the only solution is to indeed use the single overload with USUAL params.

```
LOCAL f AS FLOAT
LOCAL u AS USUAL
f := 1.5
u := 0.2
? Mod(f,u) // 0.10 in both VO and X#
? Mod(u,f) // 0.20 in VO, 0 in X# <- error!

? "-----"
/*
f := 0.2
u := 1.5
? Mod(f,u) // 0.20 in both VO and X#
? Mod(u,f) // 0.10 in VO, divide by zero exception in X#
*/
? "-----"

f := 0.3
u := 0.3
// All following return 0.2 in VO:
? Mod(2 , FLOAT(0.3)) // System.DivideByZeroException
? Mod(2 , REAL8(0.3)) // 0.2, OK
? Mod(2 , REAL4(0.3)) // 0.2, OK
? Mod(2 , f) // System.DivideByZeroException
? Mod(2 , u) // System.DivideByZeroException

// function overloads from the runtime:
FUNCTION Mod(nDividend AS REAL8, nDivisor AS REAL8) AS REAL8
	RETURN nDividend % nDivisor
FUNCTION Mod(nDividend AS INT64, nDivisor AS INT64) AS INT64
	RETURN nDividend % nDivisor
FUNCTION Mod(nDividend AS LONG, nDivisor AS LONG) AS LONG
	RETURN nDividend % nDivisor

```

**Comment by cpyrgas** [comment]
This is actually mostly fixed now, not sure if it's a side effect of something else, or Robert you changed something here.

There's still one problem, Mod(2 , u) still throws a divide by zero for u = 0.3 and there's also the VO incompatibility with the Mod() return type. Will add a test in the suite for those.

**Comment by RobertvanderHulst** [comment]
Yes, to properly solve this we have to remove several overloads of the Mod() function and inspect the numbers at runtime and decide if we do an integer modulo or a fractional modulo.
There is one change that we could make as well: the compiler could detect that a usual value is passed to a function that has overloads with fractional values and an overload with integral values, and when that happens the compiler could give precedence over the overload with fractional values. That should solve the dividebyzero exception that we see here.
That would also solve the usualtype error because the fractional overload would be chosen which returns a float and not an integer.
