### ISSUE TITLE
Macro execution Misinterpretation parentheses around variable name as type

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#584]
Macro code {|UV,N|(uV)-( uV* n/ 100)}
Error message:
XSharp.MacroCompiler.CompilationError: Macrocompiler (1,9): error XM0221: 'UV' is not a type
The macro code 
{|UV,N|uV-( uV* n/ 100)}
would work as a workaround. 
But as it may has happened more often that admins have made such a formula, it would help us, if the code line would be interpreted without error messages. 
Version: X# 2.7, Dialect VO

**Comment by ArneOrtlinghaus** [comment]
Variable values for example:
uV := 1.5
n := 1

**Comment by RobertvanderHulst** [comment]
Nikos,
Can we change the macro compiler to recognize LPAREN ID RPAREN as paren expression first and not a type cast operation because code coming from VO will never have the typecast expression. Maybe if you can't resolve the ID as a variable in the scope of the macro you could then decide to parse this as a typecast ?

**Comment by nvkokkalis** [comment]
The fix has the side effect that an expressions such as `(int)-5.1` now needs to be written as `(int)(-5.1)` to work correctly.

Let me know if this causes any trouble.

**Comment by RobertvanderHulst** [comment]
Nikos 
Since the ( int ) typecast did not exist in vo ( nor in any of the other dialects) this is only a problem for "new" code.
