### ISSUE TITLE
Warning when explicitly override a method that doesn't exist

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#586]
I noticed, that the following code compiles without error or warning.
 
class Xx
end class
        
class Yy inherit Xx
    
    public override method Funky() as void
        System.Diagnostics.Debug.WriteLine("Funky YYYY")
        return
            
end class
            
I know that the override keyword is not necessary, because in the VO dialect, override is active by default.
Nevertheless it would be nice to get a warning by the compiler, when I tried to explicitly override a method, that doesn’t exist. 
This could be helpful to eliminate errors introduced by typos in overridden method names.
Of course only, if this change is easy to introduce.

**Comment by cpyrgas** [comment]
When OVERRIDE is used with no parent method, I think this needs to always be an error actually (in all dialects). That's because that's not a matter of compatibility with VO and with OVERRIDE the programmer explicitly declares somethng which is obviously wrong. I think the same goes by for NEW with no parent method.

Also when there DOES exist a parent method, but the child method does not use neither NEW or OVERRIDE, then there should be a warning (at least). The question is, should that happen in all dialects? And by default, or with a compiler switch (something like /strict) ? Maybe the best solution is to have this on by default in Core and off by default in all other dialects.

**Comment by VolkmarR** [comment]
IMHO this could be enabled by default for all the Dialects, that didn't support the NEW or OVERRIDE in the original language, because then you can be sure, that ported code doesn't contain code that will raise this error.

**Comment by cpyrgas** [comment]
Confirmed fixed.
