### ISSUE TITLE
OrdKeyCount() and SetDeleted(TRUE)

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#599]
The sample creates a dbf with 12 records. 3 of them are deleted. The problem is that if the scope is set from "A" to "Z" that ordkeycount() returns 3 if setdeleted(false) is used. But when i set the scope from "A" to "S" OrdKeyCount() returns correctly 12. Note:  There’s no record with an "Z" entry,  while "S" exists in the last record of the scope.

 In VO OrdKeyCount() returns in all cases 12, because VO ignores a Setdeleted(true) setting.

FUNCTION Start() AS VOID
LOCAL cDBF, cPfad, cIndex   AS STRING 
LOCAL aFields, aValues AS ARRAY 
LOCAL i AS DWORD  
LOCAL lSet AS LOGIC

    lset := SetDeleted() 
    
    RddSetDefault ( "DBFCDX" ) 
    
    cPfad := "c:\test\" 
 
	cDBF := cPfad + "Foo"
	cIndex := cPfad + "Foox" 
	
	FErase ( cIndex + IndexExt() )
		
	aFields := { { "LAST" , "C" , 20 , 0 } 	} 
	
	aValues := { "g6" , "o2", "g2" , "g1" , "g3" , "g5" , "B1" , "b2" , "p", "q" , "r" , "s" }	
	
	// ------------
	
	DbCreate( cDBF , AFields)
	DbUseArea( ,,cDBF )		

	FOR i := 1 UPTO ALen ( aValues )
		DbAppend() 
		FieldPut ( 1 , aValues [ i ] ) 
		
		IF InList ( Upper(aValues [ i ]) , "B2" , "G3" , "P" )
			? "Delete"  
			DbDelete()
		ENDIF	
	NEXT
	
	DbCreateOrder ( "ORDER1" , cIndex , "upper(LAST)" , { || Upper ( _Field->LAST) } )
	DbCloseArea()
	
	// --------------
	
	DbUseArea( ,,cDBF )
	DbSetIndex ( cIndex )
	DbSetOrder ( 1 ) 

	OrdScope(TOPSCOPE, "A")    // "A"  "A"  
	OrdScope(BOTTOMSCOPE, "S") // "Z"  "S"  
	
	DbGoTop()
	
	
	? "Reccount " , RecCount()  // 12 
	
	SetDeleted ( TRUE )	
	
	? "SetDeleted (TRUE) + OrdKeyCount()" , OrdKeyCount()  // "A" 9  "A"  9    SetDeleted(TRUE)
	
	SetDeleted ( FALSE )  

	? "SetDeleted (FALSE) + OrdKeyCount()" , OrdKeyCount() // "Z" 3  "S"  12   SetDeleted(FALSE)
        
	DbCloseArea() 
	
	SetDeleted( lSet )

**Comment by RobertvanderHulst** [comment]
Chris,
Ignoring SetDeleted() is very easy. Shall I make this compatible with VO and do that too ?

**Comment by Karl1155** [comment]
Robert,

just to be clear: the main reason why i posted the code to Chris is the constellation 

OrdKeyCount() + SetDeleted (false)

its imo ok that OrdKeycount() does *not* ignore the SetDeleted(true) setting as VO does. If i remember correctly did you introduce this behaviour already 3 years ago. 

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
I know that I introduced it. But now in combination with incorrect scopes and descending indexes (see https://github.com/X-Sharp/XSharpPublic/issues/579) it seems to be difficult to implement this correctly. So either I will remove the fix for #579 or I suggest that we switch back to the compatible (and much faster to calculate) solution to count just the records.
Faster because having to process "SetDeleted()" means that we cannot resolve the ordercount from just the index but we will have to also read each and every record in the scope.
On top of that: many people have already added for clauses to their indexes like ".not. deleted()". With a for clause like that the ordercount from the index itself will already exclude the deleted records.

**Comment by Karl1155** [comment]
Robert,

ok, it would be nice to keep the current OrdKeyOunt() + SetDeleted(true) behaviour, but if its easier to handle other problems i have no problem to make OrdKeyCount() 100% VO compatible again. 

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Adjusted the code in 64107df159d32f13dc657770dd2f9a4b37eb1ff6

**Comment by cpyrgas** [comment]
Confirmed fixed.
