### ISSUE TITLE
DbCloseArea() with no open files returns TRUE

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#611]
DBCloseArea() and DBCloseAll() return TRUE, even if no dbf is open:

```
FUNCTION Start() AS VOID
 	? DbCloseArea() // TRUE, should be false
 	? DbCloseAll()  // TRUE, should be false
RETURN

```

**Comment by RobertvanderHulst** [comment]
Does the TRUE mean that a file was open and now closed or that the area is closed after the operation regardless of how it was before.
I'll check what VO and Xbase++ does and will change the code to do the same in X#.

**Comment by cpyrgas** [comment]
At least VO returns FALSE when there's nothing to close, so I guess TRUE means that it did close the (or some, for DBCloseAll()) file(s).

**Comment by Serggio** [comment]
That FALSE in VO is a problem, because it's not an error in fact. In VO I had to do a cycle to MAX_DBAREAS to find if there's at least one open workarea, otherwise I could not distinguish real error associated with close/flush (i.e. sql trigger fault) from a fictitious one, generated because there's just nothing to close.
Quite happy, that X# returns TRUE on no workareas.

**Comment by RobertvanderHulst** [comment]
Chris, Serggio,
I agree that DbCloseAll() should return true when no areas were open, because the end result that you want (all areas closed) was achieved successfully. The fact that this came "for free" does not change the fact that the result = success.
I'll probably add a check to the code to return FALSE for the VO dialect and TRUE for all the other dialects.
For DbCloseArea() on the other hand you may argue that it should indeed return FALSE when no area was open. 
This is typically an example of a function where a TRUE/FALSE result is simply insufficient to distinguish between different scenarios.

**Comment by cpyrgas** [comment]
Guys, I agree, I cannot think of any situation where it could be useful information this FALSE from DBCloseAll(), if there's no dbf open. Such a FALSE cannot be used in a meaningful way. So I suggest to let DBCloseArea() as it is now, return TRUE when no dbf is open in all dialects,  I don't see how it can break existing VO code.

About DBCloseArea(), I think it's probably better to change it to be compatible with VO and return FALSE in this scenario, denoting that something probably is wrong in the program flow.

**Comment by RobertvanderHulst** [comment]
Ok, I will change DbCloseArea() to return FALSE when no area is open. DbCloseAll() will only return FALSE when there was a failure to close an area.

**Comment by cpyrgas** [comment]
Confirmed fixed.
