### ISSUE TITLE
Problem with the Workareas debug window

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#625]
In Robert's session for X# 2.80, there was an exception when using the workareas window with a certain dbf/cdx.

Robert, can you please attach those files to have a look?

**Comment by RobertvanderHulst** [comment]
[data.zip](https://github.com/X-Sharp/XSharpPublic/files/6413141/data.zip)

**Comment by RobertvanderHulst** [comment]
Chris, these files should be opened with the DBFVFP driver. The RDD is smart enough to detect that there is a DBC and read the additional info from this DBC .
You may also want to consider to use FieldInfo(DBS_CAPTION) for the details window instead of the field name. This will return the defined caption for tables in a DBC and will return the field name for other tables.
And when the table has a field name > 10 characters then I think you can get the longer name with DBS_ALIAS.

**Comment by cpyrgas** [comment]
Thanks! Looks like the error you were getting was a _handled_ exception, it is because of https://github.com/X-Sharp/XSharpPublic/issues/627

Thanks about the tip with FieldInfo(DBS_CAPTION), will do that. But I noticed that FieldInfo(DBS_ALIAS) also returns the field name, even for small ones. Is there a reason not to use DBS_ALIAS always?

**Comment by cpyrgas** [comment]
Confirm fixed
