### ISSUE TITLE
Handle Navigationbar for Codewindow with splitter

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#641]
At this moment we're not properly handling the navigation bar for code windows that are split.
Roslyn does the following:
- It creates its own VsCodeWindowManager 
- The navigationbar is created for this object
- The dropdown bar has a list of views that are attached to it (_trackedTextViews)
- The dropdown bar registers events for the TextView.PositionChanged and TextView.GotAggregateFocus

**Comment by cpyrgas** [comment]
This is fixed, but I see a problem, when you click on the mouse on the navigation bar to select an entity, the cursor goes there correctly, but focus is not actually sent to the editor, it remains on the navigation bar itself. So if you try to type something nothing happens, and if you try to use the arrow keys, then you make the navigation bar drop down. In order to focus the editor, you need to click again with the mouse over the editor area (and can cause the cursor to move again) or hit ESC.

I do not know if this is a side effect of this fix, or it is an old problem. If it's an old thing, please let me know and I will open a new ticket for it. I checked what c# does and it does give focus th the editor as expected when selecting an item in the navigation bar.

**Comment by RobertvanderHulst** [comment]
This is a side effect of the fix. Before I was always calling a method that would not look at the active textview in the editor (each split pane is a textview). I had chosen methods now that set the selection but did not make the TextView active. I have changed that now in commit 83d219cd2c6b766b385bcb37cc7d2b597ecd9eb4

**Comment by cpyrgas** [comment]
OK, confirmed fixed now!
