### ISSUE TITLE
Bug in oClone

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#667]
Cloning an object via oClone() gives a NULL_OBJECT

Not too important, there are ways to avoid its usage, but we have it in several places in VO

**Comment by cpyrgas** [comment]
Yeah, the compiler should be reporting a warning in every place that OCLone() is used, that this function is obsolete.

This function cannot be properly implemented in .Net, except under specific circumstances. If the objects you clone always have a default constructor (that accepts no parameters and is a STRICT one), then this implementation with reflection should work:


```
USING System.Reflection

FUNCTION OClone(oObject AS OBJECT) AS OBJECT
	LOCAL oType AS Type
	LOCAL oNewObject AS OBJECT
	IF oObject == NULL
		RETURN NULL
	END IF
	oType := oObject:GetType()
	oNewObject := Activator.CreateInstance(oType)
	FOREACH oField AS FieldInfo IN oType:GetFields(BindingFlags.Public + BindingFlags.NonPublic + BindingFlags.Instance)
		oField:SetValue(oNewObject, oField:GetValue(oObject))
	NEXT
RETURN oNewObject
```

Problem is that classes in VO code usually have constructors (Init() methods) with parameters, and for such classes the above code will throw an error. 

Another option would be to use the MemberwiseClone() method that is available in every object in .Net, but unfortunately this method is protected, so can be used only from within that class. But you can define something like this, in all the classes that you need to support cloning:

METHOD Clone() AS <name of current class>
RETURN SELF:MemberwiseClone()

and then call this Clone() method from "the outside", instead of using OClone()

**Comment by cpyrgas** [comment]
On second thought, MemberwiseClone() can be called even from the outside, with reflection. Please try this function below, it is not officially supported and it will not work in a protected environment with elevated security settings, but in normal situations should do the trick, with all kind of classes. Just define it in a base library in your code :


```
USING System.Reflection
FUNCTION OClone(oObject AS OBJECT) AS OBJECT
	LOCAL oMethod AS MethodInfo
	LOCAL oNewObject AS OBJECT
	IF oObject == NULL
		RETURN NULL
	END IF
	oMethod := oObject:GetType():GetMethod("MemberwiseClone" , BindingFlags.NonPublic + BindingFlags.Instance)
	oNewObject := oMethod:Invoke(oObject , OBJECT[]{0})
RETURN oNewObject
```

Does it work for you as expected?

**Comment by ecosSystem** [comment]
Just tried it in one place and it seems to work. Will this be part of a later version or shall I implement this in our base library ?

**Comment by cpyrgas** [comment]
Not sure, this small hack is not an "encouraged" way to do things in .Net. On the other hand, late binding is already implemented in similar ways... Robert what do you think?

**Comment by RobertvanderHulst** [comment]
Chris,
It is dirty, but if it works. Why not ?
If this was the only dirty thing in the runtime...

**Comment by cpyrgas** [comment]
OK, agreed, function is now implemented in the runtime! It's safe to have it also defined in the app code for now.
