### ISSUE TITLE
Slow Build Solution with no changes

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#675]
In one of our projects, compiling in Visual Studio takes 55 sec (already compiled before and no changes in the code).
With the following manual call of MsBuild this process takes about 4 sec:

`msbuild.exe Radix_Full.sln /maxcpucount:1 /nodeReuse:True /nologo /p:Configuration=Debug /p:OutDir=C:\Projects\XSharp\Radix\publish /p:Disable_CopyWebApplication=True /target:Build /verbosity:Minimal /WarnAsError:MSB3245`

**Comment by RobertvanderHulst** [comment]
Inside VS for each project we keep track of the "current configuration".  Based on the configuration certain properties (such as output folder, and list of enabled/disabled warnings) may be different.

Since a build inside VS may also trigger a build for other configurations (from the Batch Build menu) we need to make sure that we pass the right configuration to MsBuild. So we cannot assume that the current configuration for the project is correct.
I think that at this moment we are always creating a new configuration and evaluating the properties for this configuration even when we are building for the active configuration. We can probably suppress that and return (a copy of) the cached current configuration.
I also suspect that in response to the build command we re-evaluate the list of references and update the locations for these references. That can probably be suppressed if we already know the location of all references.

**Comment by RobertvanderHulst** [comment]
Hans Joerg,
Can you confirm that 2.8b improves the Solution Build speed ?

**Comment by hpetriffer** [comment]
It is about 60% faster than before
