### ISSUE TITLE
Issues with PRIVATE and PUBLIC vars in VFP dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#703]
After today's compiler update, it is no longer possible to do this in VFP dialect (it was working before):

```
FUNCTION Start( ) AS VOID 
PRIVATE pri := 1 // error XS9002: Parser: unexpected input 'PRIVATE'
? pri
```
Interestingly though, this is not allowed in FoxPro itself either. It was just allowed in FoxPro dialect of X#, not sure if we want to continue supporting it.

Trying the same thing with a PUBLIC, results to a different error on another line:

```
FUNCTION Start( ) AS VOID 
PUBLIC pub = 0
pub := 2 // error XS9002: Parser: unexpected input 'pub'
```

Note that this is not allowed in VFP itself either. So if it's difficult to allow the declaration/assignment syntax, then I think it's OK to properly disallow it in X#, too (but with a consistent error message).

**Comment by RobertvanderHulst** [comment]
Chris,
The PRIVATE rule is now the same as the rule in FoxPro

`PRIVATE VarList`

I am working on the alternative

`PRIVATE ALL [LIKE Skeleton | EXCEPT Skeleton]`

This worked before because I did not differentiate between the general rule and the foxpro rule.
I have now created separate rules for FoxPro and the other dialects, to also help prevent the problem where the PRIVATE instance variable inside a class was seen as a PRIVATE statement. 

The XBase (general) rules for MEMVAR, PUBLIC, PRIVATE etc are on line 705 in the parser definition:
https://github.com/X-Sharp/XSharpDev/blob/main/XSharp/src/Compiler/XSharpCodeAnalysis/Parser/XSharp.g4#L705

The FoxPro rules are on line 724 and these also include DIMENSION and PUBLIC ARRAY and LOCAL ARRAY.

https://github.com/X-Sharp/XSharpDev/blob/main/XSharp/src/Compiler/XSharpCodeAnalysis/Parser/XSharp.g4#L724

The General rules for PRIVATE and PUBLIC use the xbasevar subrule (line 713) that allows for optional array size and optional initialization.

The FoxPro rule for PRIVATE and PUBLIC use the foxbasevar subrule (line 752) that only allows for a name.

Both rules (xbasevar and foxbasevar) allow for an ampersand in front of the name and they both use the varidentifiername rule that allows the name to be prefixed with M. (MDot)

**Comment by RobertvanderHulst** [comment]
BTW it will be difficult to get a proper error message. The only way that I can think of is to add the initialization to the PRIVATE rule and then manually produce an error, but that will then confuse the compiler when distinguishing between PRIVATE fields in a class and PRIVATE variables inside a method in a class.
I could add a predicate in the parser rule so the MEMVAR, PRIVATE, PUBLIC etc. rules will only be considered when the program is compiled with /memvar, but for these situations the compiler would then still get confused.

**Comment by cpyrgas** [comment]
Robert, OK agreed, that sounds good! But my main point was that the private syntax:

FUNCTION Start( ) AS VOID 
PRIVATE pri = 1
System.Console.WriteLine("test")

results to a "error XS9002: Parser: unexpected input 'PRIVATE'" reported on the PRIVATE line, which is indicative of the problem enough. But in the case of a PUBLIC:

FUNCTION Start( ) AS VOID 
PUBLIC pub = 1
System.Console.WriteLine("test")

the error message is "error XS9002: Parser: unexpected input 'System'", which is quite different/not informative and does not point to the line with the error. If the reason why this happens is more complicated that it looks, please don't bother with it.

**Comment by cpyrgas** [comment]
Oh, OK, just saw your next message. OK, I think this can be closed now then, I will update the sample in the test suite.
