### ISSUE TITLE
Occurs2 ?

### ISSUE THREAD

**Issue by lazy-fox** [X-Sharp/XSharpPublic#719]
**Describe the bug**
Getting reaquainted with x# docs and coding patterns I stumbled upon Doc entry
Remarks
Occurs2() is the same as Occurs() except Occurs2() returns a WORD.  See Occurs() for more information. 

while code reads:
/// <include file="VoFunctionDocs.xml" path="Runtimefunctions/occurs/*" />
FUNCTION Occurs(cSearch AS STRING,cTarget AS STRING) AS DWORD
	RETURN Occurs3(cSearch,cTarget, 0)   

/// <include file="VoFunctionDocs.xml" path="Runtimefunctions/occurs2/*" />
FUNCTION Occurs2(cSearch AS STRING,cTarget AS STRING) AS DWORD
	RETURN Occurs3(cSearch,cTarget, 0)   

was the plan to do as docs say and after copy forgotten ?
Or plan dropped as benefit of casting result of occurs() in potentially many places is more bearable than inflating function count ?

**Comment by cpyrgas** [comment]
Looks like just an error in the docs. Those are taken from VO, but even in VO, even in very old versions, both Occurs() and Occurs2() are completely identical and both return a DWORD.

**Comment by lazy-fox** [comment]
Hi Chris,
part of the reason look in code was to decide how to code alternative method signatures - I don't want my code to stick out like a wart just because I keep my own "standards", esp. as I know not enough of Dotnet/x# to base any own standards on. 
Did not know about 2&3 existing in VO- and you‘d want to keep Occurs3 compile error if no 3rd parameter is given, and as they are tiny, doing some compiler #define magic to map Occurs2  to Occurs is probably less pressing.

On alines, the 2 overloaded options to call with least # of parameters (in the __FoxArray version) are:
= alines(taFox, tcSource)
= alines(taFox, tcSource, nFlags)
which can map into
#ifdef NODEFPARM
`function alinesT(aResult ref __FoxArray, cExpression as string)  as dword
	return alinesT(@aResult, cExpression, 1)

function alinesT(aResult ref __FoxArray, cExpression as string, nFlags as dword)  as dword
#else
function alinesT(aResult ref __FoxArray, cExpression as string, nFlags=1 as dword)  as dword
#endif
both being correct. Any current preference for a way to code ? Just follow example of Occurs and create Overloads without default ? Based on tested speed benefit and/or x#devteam opinion of „nicer“ code ? If neither exists, I’ll test to see if there are speed differences and decide then.

And yes, there I‘ll aim for a core/string[] version as well ;-)

**Comment by RobertvanderHulst** [comment]
The reason why we have Occurs(), Occurs2() and Occurs3() is that in earlier versions of XBase there was no support for method and function overloads.

I have a slight preference over the single overload with a default parameter, since the 2 overloads either result in duplicate code, or the overload with less parameters will call into the one with the extra parameter causing an extra level on the callstack.
Our compiler, macro compiler and late bound code all 3 support the default parameter value, so this will work.

**Comment by RobertvanderHulst** [comment]
One remark: I DO prefer to use `:=` instead of `=` since that is supported in all dialects and is a little more self-explaining.
And also the use of
```
alines(taFox, tcSource)
alines(taFox, tcSource, nFlags)
```
without the leading '=' character. FoxPro is the only language that I know that does requires this funny assignment operator for function calls in an expression statement. Assignment to what ?

**Comment by lazy-fox** [comment]
In the final version '::' and ':=' will be there as was in GetWord. But sometimes I copy parts over to vfp to check something, and there this way does not work. Had ':=' in Pascal and Modula looong time ago.

The leading '=' for me is a similar guard against reading with tired eyes to '::':
Parameters in function calls are passed by value, in Do procedure with by reference.
Any line starting with '=' has no need to watch for 'Do' or 'with', eyes and hindbrain can relax.

Similar when refactoring old stuff: I prefer to not just prefix "L" to "PARAMETERS" where possible, but instead to move list into the function brackets to allow faster reading later.
Trying to minimize read error ;-)
