### ISSUE TITLE
ReportPro 2: Process suggetions from Jörg

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#739]
See https://www.xsharp.eu/forum/topic?p=2422#p2422

**Comment by cpyrgas** [comment]
Reported items:

nachdem ich den X# Reportpro2 Code vom Robert erhielt und in einem Projekt mit eingebunden habe sind mir einige Dinge aufgefallen, die ich – zum großen Teil -bereits damals in der Vulcan-Quelle lokalisierte:
- Übersetzungsfehler in der ReportPro2.German.dll
- keine Tool-Tip-Darstellung im Preview-Fenster
- Wheel-Rädchen der Maus reagiert oft nicht im Preview-Fenster
- Zoomstufen sind vertauscht: normal->am größten->größer
- kein scrollen auf die nächste/vorhergehende Preview-Seite möglich
- der Report wird in der Preview-Seite nach unten verschoben dargestellt
- Unterstreichung wird bei RTF-Text nicht wieder ausgeschalten
und andere Laufzeitkorrekturen. Die Zusammenstellung in der angehängten PDF hilft vielleicht die Problemstellen nachzuvollziehen bzw. gleich zu korrigieren. Einige Problemstellen konnte ich wegen dem CDX-Problem in der X# Variante noch nicht testen.

In English:

after I received the X# Reportpro2 code from Robert and included it in a project, I noticed a few things that I had already located - for the most part - in the Vulcan source:
- translation errors in the ReportPro2.German.dll
- no tooltip display in the preview window
- mouse wheel often does not respond in the preview window
- zoom levels are swapped: normal -> largest -> larger
- no scrolling to the next/previous preview page possible
- the report is displayed shifted downwards in the preview page
- underlining is not turned off again for RTF text
and other runtime corrections. The compilation in the attached PDF may help to understand the problem areas or to correct them immediately. I have not been able to test some problem areas in the X# variant because of the CDX problem.

**Comment by cpyrgas** [comment]
All items seem to have been fixed already in the past. I cannot confirm the German translation issues, but I assume that's fixed, too. Unfortunately the pdf mentioned in the message is no longer available.
