### ISSUE TITLE
Intellisense doesn't show default values for NULL and NULL_OBJECT

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#743]
If the program library is linked to the project as an external DLL, then Intellisense VS2019, when displaying method signature hints, does not display the default values NULL and NULL_OBJECT. For classes of the same project or libraries in the same solution, all default parameters are displayed correctly. The problem is only in external DLLs.

**Visualization of the problem:**
![Screenshot1](https://user-images.githubusercontent.com/64518775/127107598-19049bad-0752-4e9e-93a8-e1dd552f11f0.png)

**Test project to reproduce the problem:**
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/6883231/TestConsoleApplication.zip)

**Comment by RobertvanderHulst** [comment]
Confirmed. This is related to how default parameter values are encoded with a DefaultParameterValue attribute.
Apparently the attribute with the value

`[DefaultParameterValue(null, 0)]`

which means `NULL` is not decoded properly
As you can see in https://github.com/X-Sharp/XSharpPublic/blob/main/VisualStudio/XSharpCodeModelXs/PE/XPEMemberSymbol.prg#L356
the code checks for NULL and forgets to return the value "NULL" or "NULL_OBJECT" when the attribute has a value of NULL.

Btw the encoding is a bit "strange". We inherited this from Vulcan. It was coded this way so you can also have a default symbol, psz, ptr, NIL or date value, which would otherwise be impossible

**Comment by cpyrgas** [comment]
Problem is fixed for NULL_OBJECT, but similar problem exists with NULL_DATE which is shown as "0001.01.01" in the tooltip.

Also another small problem is that the parameters are shown with "As" in the tooltip, instead of "AS" in VS 2019. Problem happens only in VS2019, in VS2017 they are correctly shown with "AS":

![VS2019_default_params](https://user-images.githubusercontent.com/14542129/127683568-ccc7d273-7a3e-497d-92b2-e1edc9bf3b6d.png)

**Comment by RobertvanderHulst** [comment]
Chris,
The "As" keyword in the code follows the current setting for the Keyword Case Synchronization.
I'll make sure that the NULL_DATE is handled correctly.

**Comment by cpyrgas** [comment]
I think this is related then to the other problem I reported, that in VS2019 my case sync setting is ignored and also gets reset to None after I close and reopen VS. Only happens in VS2019, in VS2017 it's fine.

**Comment by RobertvanderHulst** [comment]
Does your VS2019 solution have an .editorconfig file ?

**Comment by cpyrgas** [comment]
No, and that happens even with not opening a solution at all. I just open VS2019 (with no solution), go to the options/formatting, option is set to None. I select UPPER, close VS completely, open it again and the settings has been reset to None.

**Comment by cpyrgas** [comment]
Robert, I just realized, this is not a new problem, but still happens after I reverted back to the original 2.8c build. Where does VS2019 store the settings, so I can check what the actual value is in there and try changing it manually?

**Comment by RobertvanderHulst** [comment]
VS Stores settings like this in a special "private registry".  In the past (before they allowed side by side installations of Professional and Enterprise) this was stored in the registry. You can also install "Extensibility Extensions". It is included in that package.

If you install an extension "settings store explorer" in VS then you get an extra menu option in the  View/ Other windows menu.
That window acts like the registry editor.
The values are stored in the key "User\Text Editor\XSharp"
and in the key "User\ApplicationPrivateSettings\TextEditor\XSharp"

**Comment by cpyrgas** [comment]
Thanks! Before I do that, I guess you cannot reproduce the problem with not being able to change the case sync setting in VS2019?

**Comment by RobertvanderHulst** [comment]
No, I cannot reproduce that. When I change the setting in VS2019 and close VS, the setting is still there after reopening VS.
