### ISSUE TITLE
VOWED ComboBoxEx controls should have a fixed height, as in VO

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#750]
https://www.xsharp.eu/forum/private-product/2618-different-behaviour-comboboxex-vo-vs-x

In VO the designer always gives a fixed height to the ComboboxEx controls, while in it X# allows you to specify the height, same as for the simple ComboBox.

**Comment by leon-ts** [comment]
Chris,
In VO it was very inconvenient. When displaying large ComboBoxEx lists, I could not control the number of items simultaneously visible in the list. The height is always fixed. X# is now much more convenient. The only thing that might cause a small problem is that after converting the window from VO to X#, the ComboBoxEx height is missing and needs to be manually stretched. I propose to bring the question up for discussion on the X# forum.

**Comment by cpyrgas** [comment]
Leonid, another customer requested that we change it the way it works in VO! :)
I am thinking of an intermediate solution, maybe when the designed size is very small (similar to the non-dropped control height), then the designer will make it 5-6 items tall, like in VO. But when the designed size is larger (so the programmer has set it manually), then it will be emitted in that exact size.

**Comment by leon-ts** [comment]
Chris,
The client has a strange desire :)) In X # the size of ComboBoxEx works better than in VO and, moreover, does not eliminate the features that were in VO, but only expands them :))

Here's a real example.
One of my applications in VO, when entering the program, offers a list of databases with icons (ComboBoxEx). Some of my clients have a long list and they complain that only 5 databases are visible at a time and asked to make the list larger. But ComboBoxEx does not allow this. I am currently porting applications from VO to X # and ran into a problem that the ComboBoxEx was not expanding. It turned out that he was just the minimum size. I stretched it to the size I needed and everything began to be displayed. I also realized that X # fixed this old ComboBoxEx height issue. And now one of your clients wants to return this problem :))

Nevertheless, the solution you proposed will suit everyone. Thanks!

**Comment by cpyrgas** [comment]
Leonid, I completely understand, and I also prefer the previous X# implementation (probably because I am also very used in working this way in VO for simple ComboBox controls), but the customer is always right! :)

Anyway, I implemented the hybrid solution and it seems to be working well..
