### ISSUE TITLE
upper("µ") returns ? instead of "µ"

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#762]
All ASCII-characters apart from µ are converted equally to VO. Only µ returns a question mark. 
This happens with Cahors 2.8c, Dialect VO. I believe that this was already in earlier versions from last year. Unfortunately one customer needs this character quite a lot.

**Comment by ArneOrtlinghaus** [comment]
I have overwritten functions UpperA, Upper and Transform for having a quick solution. 
For us the issue will be resolved although it is not a nice solution. I can also close the case if you don't see any necessity for other users.  

function UpperA(cString ref string ) as string strict
	if cString != null
      if instr("µ", cString)
         cString := cString:replace ("µ", "$MY%")
   		cString := cString:ToUpper()
         cString := cString:replace ("$MY%", "µ")
      else
   		cString := cString:ToUpper()
      endif
	endif
	return cString

function Upper(cString as string ) as string strict
//p Upper character conversion of a string
//a cMain - String: zu dem etwas hinzugefügt werden soll
	if cString != null
      if instr("µ", cString)
         cString := cString:replace ("µ", "$MY%")
   		cString := cString:ToUpper()
         cString := cString:replace ("$MY%", "µ")
      else
   		cString := cString:ToUpper()
      endif
	endif
	return cString

**Comment by Karl1155** [comment]
Using ToUpperInvariant() instead of ToUpper() seems to be the solution .

https://stackoverflow.com/questions/14712464/toupper-is-changing-sometimes-the-character-%c2%b5-m

"äöümdg567µ".ToUpperInvariant()  //  ÄÖÜMßDG567µ

Karl-Heinz

**Comment by Karl1155** [comment]
sorry, made a copy and paste error - in the test above the "ß"  is missing.   

? "äöümßdg567µ".ToUpperInvariant() //  ÄÖÜMßDG567µ

**Comment by ArneOrtlinghaus** [comment]
This seems to be the solution. Currently the function Upper calls the Dotnet ToUpper method.

**Comment by cpyrgas** [comment]
Guys, are you sure this is not a GUI/console display and/or .prg file encoding issue? Because I just tried using oForm:Text := "µ":ToUpper() in a WinForms app and this worked fine.

Can you please attach a small app showing the problem? So we can see both the encoding of the .prg and the exact output and in which GUI. Also I assume you are using German or similar System locale in your windows settings?

**Comment by ArneOrtlinghaus** [comment]
Hi Chris, 

> are you sure this is not a GUI/console display and/or .prg file encoding issue
Yes, I am sure. 

> Also I assume you are using German or similar System locale in your windows settings?
Yes, this is right. 
Also some global settings at the beginning:
   SetAnsi (true)
   SetInternational (#Windows)
   SetCollation(#ORDINAL)
   SetDateCountry   (5/*GERMAN*/)

**Comment by cpyrgas** [comment]
OK, can you please attach a small sample project, so we can reproduce and fix it?

**Comment by Karl1155** [comment]
Chris,

attached is a zipped Foxpro viaef. The results are here: 

MessageBox ( Upper("µ") )  // the build in FoxPro Messagebox() shows "M"

? "µ".ToUpper()  // shows "?"
? "µ".ToUpperInvariant() // shows "µ"
[XSharpFoxVariant.zip](https://github.com/X-Sharp/XSharpPublic/files/7013377/XSharpFoxVariant.zip)

Karl-Heinz

**Comment by ArneOrtlinghaus** [comment]
[ConsoleTests.zip](https://github.com/X-Sharp/XSharpPublic/files/7013387/ConsoleTests.zip)
![consolemy](https://user-images.githubusercontent.com/58024066/130046899-71ff0934-a94a-4d35-97bb-12f3f935fecb.png)

**Comment by ArneOrtlinghaus** [comment]
Yes, of course. Here is the test program as a console program. I have also attached what is output on my computer.  So it should be the culture info set in Windows. In the regional settings most parameters are set to "German"/"Germany". Shall I retrieve the parameters as can be seen by the program? If yes, how should I do it?

function TestUpperMy()
   local c as string
   c := "µ"
   Console.WriteLine(c)
   c := upper(c)
   Console.WriteLine(c)
   return nil

**Comment by cpyrgas** [comment]
Karl-Heinz, as you can see here, the message box show the letter in upper case correctly, so the function seems to work correctly, at least on my machine:

![Upper_m](https://user-images.githubusercontent.com/14542129/130047710-36f9b497-e120-47a3-8b23-206b795e7062.png)

In the console, indeed there's question mark shown, but that's most likely because the console can't show it.

What does the dialog display in your PC?

**Comment by cpyrgas** [comment]
..and I see that when using ToUpperInvariant(), then the result is the same as the source. Maybe I am missing the point, because "µ" is a greek letter and its upper form is "M" as the function returns. But maybe you are expecting a different result?

**Comment by ArneOrtlinghaus** [comment]
My console program can show the µ correctly. Upper("µ") shows the question mark instead. I expect µ as the upper case for µ similar as VO did.

**Comment by cpyrgas** [comment]
Arne, I think the console thing is a only a visual issue, but not sure how to change this.

I just tried this in VO:

FUNCTION Start( ) AS VOID 
? Asc("µ")
? Asc(Upper("µ"))

and I get in both cases 181, is that what you are getting as well? And this is what you expect to get indeed, no change at all to the character after using Upper() to it? It does not look right to me, but I am probably looking at it from a different perspective.

If that's how it needs to be, then maybe indeed we need to change ToUpper() with ToUpperInvariant(). But need to check what side effects this could have (except for making the function actually perform better!)

**Comment by ArneOrtlinghaus** [comment]
This is what I see, when I change my sample program to Console.WriteLine(c + " " + asstring(Asc(c)))

![consolemy2](https://user-images.githubusercontent.com/58024066/130051144-88395257-723d-4562-812b-4017f1127960.png)

**Comment by Karl1155** [comment]
Chris,

> Karl-Heinz, as you can see here, the message box show the letter in upper case correctly, so the function seems to work correctly, at least on my machine:

so the Upper result "M" in the MessageBox() of the greece letter "µ" is correct ?  Honestly, i don´t get it ... So the earlier mentioned thread is completely wrong ?

https://stackoverflow.com/questions/14712464/toupper-is-changing-sometimes-the-character-%c2%b5-m

Karl-Heinz

**Comment by cpyrgas** [comment]
Arne, in X# Asc() is doing ansi<->unicode translation before retrieving the ascii value. In order to see the real usinvode value, you need to use AscW() and this returns 924 for the Upper().

Karl-Heinz, in the thread you mention, they are saying the same thing, aren't they? I don't think there's a "right" or "wrong" here. The greek lower case form of the english letter "m" is "µ" and it's uppercase form is "M" (same with the english one), so it makes sense that Upper("µ") == "M". On the other hand, you could argue that when using the letter "µ" in a PC using non-Greek culture info, then "µ" stands for a symbol (like "™" or "®"), not a letter, so there should be no upper case for it and Upper() must return the same symbol.

Since ToUpperInvariant() gives the same result with VO in this case, maybe it's indeed the way to go, we just need to understand the other implications this might cause..

In any case, as a quick fix, Arne you could simply redefine the Upper() function in your code in a base library, so all your code will be using this version, instead of the one in the X# runtime:

```
FUNCTION Upper(cString AS STRING) AS STRING
	IF cString != NULL
		cString := cString:ToUpperInvariant()
	ENDIF
	RETURN cString
```

If you give this a try, then you can also check if something else does not work as expected in your application after making this change..

**Comment by ArneOrtlinghaus** [comment]
Chris, 
yes, I resolved it like this. Additionally I had to modify UpperA and two places where Transform is used.

**Comment by Karl1155** [comment]
Hi Chris,

i accept that the "real" upper presentation of "μ" is "M" ;-)  I made some console tests using the setting` Console.OutputEncoding := System.Text.Encoding.Utf8`, and these are the results: 

/*
γ Γ Γ
ω Ω Ω
δ Δ Δ
π Π Π
μ Μ Μ
ε Ε Ε
*/

i expect that you see excatly the same results ?


```
FUNCTION Start() AS VOID

? "current code page: " , Console.OutputEncoding.codepage
Console.OutputEncoding := System.Text.Encoding.Utf8 // System.Text.encoding.unicode 

? "current code page: " , Console.OutputEncoding.codepage
Console.Title :=  "X# Console" 

// small gamma to upper 
? ChrW ( 0x03B3 ) , ChrW ( 0x03B3 ).ToUpper() , ChrW ( 0x03B3 ).ToUpperInvariant() 

// small omega to upper
? ChrW ( 0x03C9 ) , ChrW ( 0x03C9 ).ToUpper() , ChrW ( 0x03C9 ).ToUpperInvariant() 

// small delta to upper
? ChrW ( 0x03b4 ) , ChrW ( 0x03b4 ).ToUpper() , ChrW ( 0x03b4 ).ToUpperInvariant() 

// small pi to upper
? ChrW ( 0x03C0 ) , ChrW ( 0x03C0 ).ToUpper() , ChrW ( 0x03C0 ).ToUpperInvariant()

// small mu to upper 
? ChrW ( 0x03BC ) , ChrW ( 0x03BC ).ToUpper() , ChrW ( 0x03BC ).ToUpperInvariant()

// small epsilon to upper
? ChrW ( 0x03B5 ) , ChrW ( 0x03B5 ).ToUpper() , ChrW ( 0x03B5 ).ToUpperInvariant()

 
RETURN	
```

Karl-Heinz

**Comment by cpyrgas** [comment]
Karlh-Heinz, I still haven't installed .Net 5.0, so I can't use those extra console commands (nice to know though!), but I directed the output to a message box and yes indeed I get those values.

**Comment by Karl1155** [comment]
Chris,


That´s strange ... According the docs `Console.OutputEncoding` is available since the framework 2.0. 

https://docs.microsoft.com/en-gb/dotnet/api/system.console.outputencoding?view=netframework-2.0

If you don´t see in the console the letters correctly take a look at your console font setting. My Win 8.1 laptop offers the TT-Fonts 
"Consolas" and "Lucida Console". With both fonts the letters are shown correctly.

btw. .net core isn´t installed on my Win 8.1 machine, only on my win10 machine.

Karl-Heinz

**Comment by cpyrgas** [comment]
Karl-Heinz,

Ah, you are right, the error I was getting was for the code

Console.OutputEncoding.codepage // error XS0426: The type name 'OutputEncoding' does not exist in the type 'System.Console'

But that was because of the dot used, as I hadn't added support for that in the compiler options. Once done, the code compiles fine and I do get the result you mention.

**Comment by cpyrgas** [comment]
Will let the current behavior for the time being, since making changes will have side effects.
