### ISSUE TITLE
Feature Request: Create Warning, when changing the signature of a strict method on override

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#777]
I'm currently trying to change methods in the base classes from clipper convention to strict.  One example is the following method:

```method KeySelect(oBrowser)```

Using a converter, I converted the signature to 

```method KeySelect(oBrowser := null_object as object) as void```

This method is part of a base form and I found one case where this method was overridden in this way:

```method KeySelect()```

In that case, I converted this signature to 

```override method KeySelect() as void```

The tricky thing is, that I introduced a bug by doing this. With clipper convention, the call `KeySelect(self)` would still call the overridden method without parameters. But after the change to strict, the method in the base form (with the parameter) is called instead.

My question is now, if it would be possible to get a warning by the compiler, when a strict method is overridden with a different signature. 

I'm not sure, if it would be better to show this warning only, when I explicitly mark the overridden method with _override_ (so then old code won't trigger this warning) or if the warning should be always shown. 

And maybe this is already solved with the already closed Issue #586.

This is an example for this problem:

```
AA{}:Test("With Param") // <- Calls A:Test
AA{}:Test() // <- Calls AA:Test

class A
   virtual method Test(a := "empty" as string) as void strict
		Console.WriteLine(a)
		return
end class

class AA inherit A
   override method Test() as void strict
		Console.WriteLine("Override")
		return
end class
```

**Comment by cpyrgas** [comment]
Volkmar, this is a bug indeed, because even in core, and even with no base class used, there's still no warning shown at all. I had the impression this warning was added in the compiler recently, but apparently it was not:

```
CLASS TestClass
	OVERRIDE METHOD NoBase() AS VOID // this should definitely be a warning! (or even an error most likely)
END CLASS
```

About when to show the warning, I think it needs to be shown only when OVERRIDE is used, because otherwise defining different signatures with the same name in the class hierarchy is absolutely valid. Unless maybe a new and different such helper warning could be introduced for the VO dialect only for this case.

What is definitely not allowed though, is overriding strict and clipper methods in the hierarchy and this is treated by the compiler as an error. You can see this if you change the 2nd method in your sample from STRICT to CLIPPER

**Comment by cpyrgas** [comment]
Ahh, no, please ignore what I said above :)

I had forgotten that for testing purposes I had reverted to a previous version of the compiler. Now installed back our current newest internal version, and indeed the above code throws an error, as expected:

error XS0115: 'Test': no suitable method found to override

So I think this covers it, do you agree Volkmar?

**Comment by RobertvanderHulst** [comment]
Chris.
I think we should send the internal build to Volkmar to test this.
And we should set up a folder with "nightly builds" somehow for FOX subscribers.
Let's discuss this tomorrow.

**Comment by cpyrgas** [comment]
Agreed Robert!

**Comment by VolkmarR** [comment]
Great, that this issue is already fixed in the next version. It is not a problem for us to wait for the next version. 
You can close this issue.

**Comment by cpyrgas** [comment]
Volkmar, I have just sent you an email with the the newest compiler version, so you can give it a try if you want to make sure that it is indeed working as you expect now. Please don't worry if you do not have the time to do this now!

**Comment by cpyrgas** [comment]
Confirmed fixed
