### ISSUE TITLE
Descend function in X# is incompatible with VO

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#779]
It seems that the function of X# **Descend** ignores the Windows code page, while in VO code page is taken into account. This makes index searches incompatible in DBF files created in VO using **Descend** in an expression.
In particular, I am using the Cyrillic code page (Windows 1251).

For example, there is an expression: `Descend("20101001")`

Executing it in VO gives the result (see screenshot 1): 
![1](https://user-images.githubusercontent.com/64518775/133804956-b8426a9c-3809-4eff-8255-f686ff2194b5.png)

Whereas in X # its result is different (see screenshot 2): 
![2](https://user-images.githubusercontent.com/64518775/133804978-cf167eab-587c-446c-a472-01694e6b715d.png)

**Comment by cpyrgas** [comment]
There is indeed a bug in the Descend() function in X#, in VO the result for each original character "c" in the string is 256-c (except when c=0, in which case it remains unchanged), while X# accidentally uses 255-c, which is wrong.

We will fix this, but still there will always be VO incompatibilities with VO in this function, because when it comes to strings, Descend() is a binary function. Since strings in X#/Net are unicode (so character are 0...65535), maybe a better way would be to use 65536-c, but that will be even more incompatible with the results of VO. Even without that, the result of 256-c in .Net results to "unprintable" characters, so it won't be the same with VO. Maybe we could do a ansi->unicode conversion to the result string, but that could probably introduce even more incompatibilities, depending on how the result string is being used and stored in the actual app code. It would also make sorting results very different to VO...

I think for starters we need to fix the 255-c thing, but from then on, the function really needs to be customized on a specific usage base. Leonid, can you please describe what exactly you are doing with the result of Descend(), how you are using it, where you are storing it etc, in order to suggest a specific solution?

**Comment by leon-ts** [comment]
Hi Chris,
Usage is as follows:
DBF files have index expressions for sorting dates in reverse order within a record with a specific key.
For example (index expression): `"STR(ID,8)+DESCEND(DTOS(DATEOP))"`
If you need to find a record with a specific date, the VO code uses the following expression (example):
```
cS := Str(nID, 8) + Descend(DToS(dDateOp))
DBSeek(cS)
```
This is a generalized use case.

**Comment by cpyrgas** [comment]
Hi Leonid,

OK, in this case the simple fix for subtracting from 256 instead of from 255 should be enough for you. As a quick workaround, please define this in one of your base libraries in the X# version of the code:

```
FUNCTION Descend(uValue AS USUAL) AS USUAL
	IF IsString(uValue)
		RETURN _descendingString( (STRING) uValue)
	ENDIF
RETURN XSharp.RT.Functions.Descend(uValue)

INTERNAL FUNCTION _descendingString(s AS STRING) AS STRING
	VAR sb  := System.Text.StringBuilder{s}
	VAR nlen := s:Length-1
	LOCAL i AS INT
	FOR i := 0 TO nlen
		IF sb[i] < 256 .and. sb[i] != 0
			sb[i] := (CHAR) (256 - sb[i])
		ENDIF
	NEXT
RETURN sb:ToString()

```

so now the compiler and macrocompiler will be both using this version of the function instead of the one defined in the X# runtime. Can you please confirm that your app now works as expected in both VO and X#?

**Comment by leon-ts** [comment]
Chris,
The modified function didn't help. The result was both visually different from VO, and the Seek function in X# program did not find an existing entry in the DBF file created in VO. I suspect the Windows codepage is important in the compatibility of the Descend function. Perhaps, if the DBF file is indexed in X#, then it will work with the Descend function in X#. But I have a different situation. I have X# and VO interaction.

Next, I modified the **_descendingString** function to bind it to the Windows code page. I used the X# StringHelpers inner class for this. And it helped. The Descend function in X# became VO compatible and Seek function began to find records in a DBF file.

The modification looks like this:
```
INTERNAL FUNCTION _descendingString(s AS STRING) AS STRING
	VAR bytes := StringHelpers.WinEncoding:GetBytes(s)
	FOR VAR i := 1 TO bytes:Length
		IF ( bytes[i] != 0 )
			bytes[i] := ( 256 - bytes[i] )
		ENDIF
	NEXT
	RETURN StringHelpers.WinEncoding:GetString(bytes)
```

**Comment by cpyrgas** [comment]
Leonid,

OK, that's great, the encoding/decoding is what I would suggest next, but because in your case you are using only the "0"-"9" characters (so ascii values < 128) for Descend(), it should not be needed for your specific usage. Maybe you are using also other characters in other places? (it did work correctly for me in both X# and VO, with indexes created in either of them). Or it's maybe because of the different codepage in your system, which has more "international" characters than mine.

But in any case, I think it's indeed safer to always make this ans<->unicode conversion as standard also in the official runtime code, it will probably solve more such problems, than causing side effects.

**Comment by leon-ts** [comment]
Chris,

>  but because in your case you are using only the "0"-"9" characters (so ascii values < 128) for Descend(), it should not be needed for your specific usage

Unfortunately, even with these symbols, the current implementation of Descend function (without WinEncoding) does not work under my conditions. The character codes "0" - "9" are located in the standard ASCII range from 0 to 127 only when entering the Descend function. And the output is a subtraction from 256, and the resulting character code is already in the extended ASCII range that is sensitive to the Windows code page. For example, the ASCII code of the symbol "0" is 48. After the subtraction operation 256 - 48, we get the code 208.

In a CDX file created in VO, the result of Descend ("0") is stored as a character from ASCII code 208 of the current Windows code page. When a Seek (string) operation is performed, X # converts the input string to an ASCII byte array using the Windows code page. In my case, the passed character becomes code 63 instead of 208 and the search does not work.

Let me demonstrate with an example:
```
VAR cS := Descend("0")
VAR chars := cS:ToCharArray()
VAR bytesWin := StringHelpers.WinEncoding:GetBytes(cS)
```
Debug window:
![1](https://user-images.githubusercontent.com/64518775/133919940-0bd338f9-510c-47d7-abd8-0f76a12147e0.png)

If you look at the resulting string in the form of CHAR codes, then the result is correct (code 208). But in X# DbfCdx RDD (and VO) the cS string will be converted to ASCII codes using the Windows code page. And from this particular cS string, we get (on my system) code 63, which is not correct.

I just want to say that using the Windows code page in the Descend function is not as desirable as necessary, since the X# DBF driver works from this code page for ANSI. Otherwise, the Descend function is incompatible even with the internal RDD algorithm in X#.

**Comment by cpyrgas** [comment]
Leonid, I think the best way is to use either the WinEncoding or the DosEncoding, based on the state of the SetAnsi() setting. Will do it in a similar way that Chr() works already:

```
FUNCTION Chr(dwCode AS DWORD) AS STRING
  LOCAL b   AS BYTE
  LOCAL ret AS STRING
   b := (BYTE)( dwCode & 0xFF )  // VO ignores the high 24 bits

   IF b <= 0x7F
      ret := Convert.ToChar( b ):ToString()
   ELSE
      LOCAL encoding AS Encoding
      IF RuntimeState.Ansi
        encoding := StringHelpers.WinEncoding
      ELSE
        encoding := StringHelpers.DosEncoding
      ENDIF

      LOCAL chars := CHAR[]{ 1 } AS CHAR[]
      LOCAL bytes := BYTE[]{ 1 } AS BYTE[]
      LOCAL decoder := encoding:GetDecoder() AS Decoder
      bytes[__ARRAYBASE__] := b
      decoder:GetChars( bytes, 0, 1, chars, 0 )
      ret := chars[__ARRAYBASE__]:ToString()
   ENDIF
   RETURN ret

```

**Comment by RobertvanderHulst** [comment]
Chris, Can you implement this ?
And Leonid, our implementation is almost identical to what Vulcan did. I take it that you never tried this with Vulcan. Is that right ?

**Comment by leon-ts** [comment]
Robert, quite right.
I have not used Vulcan for my DBF applications.

**Comment by cpyrgas** [comment]
Yeah, will do the changes Robert. Indeed also the vulcan implementation was wrong (subtracted 255 instead of 256 that VO does)

**Comment by RobertvanderHulst** [comment]
Fixed
