### ISSUE TITLE
VFP Type() function inconsistency with array elements in the macro compiler

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#805]
Following code in VFP prints L,L, while in X# (FoxPro dialect) prints U,O

```
FUNCTION Start() AS VOID
Dimension a[3]
? Type ( "a(1)" )
? Type ( "a[1]" )
```

**Comment by RobertvanderHulst** [comment]
If you change the example to:

```
FUNCTION Start() AS VOID
Dimension a[3]
? ValType(a[1])  // L
? ValType(a(1))  // L
? Type ( "a(1)" ) // U
? Type ( "a[1]" ) // O
? &("a[1]") // {(0x0000)0x00000000} CLASS
? &("IsNil(a[1])") // True
WAIT
RETURN
```
I suspect that a[1] detects a usual with the value NIL and returns a NULL_OBJECT

**Comment by cpyrgas** [comment]
Robert, seems often tickets get closed automatically (like in this case), so I can easily miss them. How can we prevent that?

Also please send me a new macrocompiler dll, because I have trouble building this library now.

**Comment by RobertvanderHulst** [comment]
This was closed because I had merged the branch in which I had used the text "Fixes #1234" into the main branch. The automation then decides that. For the next month I will remove that automation.

**Comment by cpyrgas** [comment]
The original sample now prints U,L. Since VFP prints L,L, I think this is still open, isn't it?

**Comment by RobertvanderHulst** [comment]
Chris,
For this to work properly you need to enable the /fox2 compiler option.
If A had been a PUBLIC then you would also need /memvar 
_Btw: XIDE refers to this option as "Locals visible to macrocompiler', but that is no longer valid.
This option is now  called "FoxPro Compatible Array Handling"._ 
In this case the problem is that A(1) could both be a function call and an array access. 

The Type() function uses the macro compiler to evaluate the type.
When /fox2 is enabled then the macro compiler checks to see if It can resolve this to a function (with the name a) or to a memvar.
When it could both be a function and a memvar then the macro compiler calls __FoxArrayAccess() and lets this function (there are 2 overloads) take care of resolving this.
When the name (a) is not the name of a function then it assumes it must be an array.
When the name is a function and there are more than 2 parameters then it also directly calls the function.

If you add the following to the test 
`? Type ( "b(42)" )`

And add a function 

```
function b (num as int) as string
    return num:ToString()
```
Then the macro compiler will call that function and the return value will be "C".

If you then add 
`PUBLIC B[42]`
before the the type check of B(42) then the return value will be "L" again.

If you then add the code 
`B = Today()`

thinking you are replacing the array with a date then you're wrong (I made that mistake myself) because with the /fox2 compiler option this will actually filled the array with dates and the return value is therefore 'D' 
To force the public to become a date instead of an array you need to release it first

```
MemVarRelease("B")
B := Today()
```
Then the function will be called again.

I know this is **VERY** messy but this is how it works in FoxPro too.

**Comment by cpyrgas** [comment]
Robert, thanks, I have changed the caption now. But even with /fox2 enabled (I had it enabled already before), I am still getting the result U, L. Also for the code that you mentioned above:

```
// fox2+
FUNCTION Start() AS VOID
PUBLIC B[42]
? Type ( "b(42)" )

FUNCTION b (num AS INT) AS STRING
RETURN num:ToString()
```

I get back "C", not "L" that you mentioned. If I remove the function, then I get "U"

**Comment by cpyrgas** [comment]
Oooops, sorry, please ignore the above! 

I forgot that I had reverted to an older compiler version for back to back testing and didn't install back the latest one. I just did that and now everything works indeed as expected!
