### ISSUE TITLE
Creating DBF files with custom file extension

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#834]
In VO, you can write the following code:
```
LOCAL cPath AS STRING
LOCAL aStruct AS ARRAY
cPath := WorkDir()
aStruct := { { "DATA", "M", 10, 0, "DATA" } }
RDDINFO(_SET_MEMOEXT, ".DBF.FPT.U")
DBCREATE(cPath + "MEMOTEST.DBF.U", aStruct, "DBFCDX")
```
This will create two files on disk:
MEMOTEST.DBF.U
MEMOTEST.DBF.FPT.U

The same code in X# ignores the specified extensions and creates the following files:
MEMOTEST.U
MEMOTEST.FPT

**Comment by cpyrgas** [comment]
Now those 2 filenames are being created:

MEMOTEST.DBF.U
MEMOTEST.DBF.DBF.FPT.U

while VO creates those 2 instead, which I think is the more "correct":

MEMOTEST.DBF.U
MEMOTEST.DBF.FPT.U

**Comment by RobertvanderHulst** [comment]
Chris
> 
> Now those 2 filenames are being created:
> MEMOTEST.DBF.U MEMOTEST.DBF.DBF.FPT.U
> while VO creates those 2 instead, which I think is the more "correct":
>  MEMOTEST.DBF.U MEMOTEST.DBF.FPT.U

This depends on what you see as the extension of the table in this case.
For a file with the name MEMOTEST.DBF.U, what is the extension.
- Is the extension .U ?
- or is the extension .DBF.U ?

The normal behavior for memo files would be to replace the extension of the main table (the DBF) with the specified extension.
If you see the extension for the main table as '.U' then setting the MemoExt to ".DBF.FPT.U" would result in a filename that ends with ".DBF.DBF.FPT.U"
If you see the extension for the main table as .DBF.U then setting the MemoExt to ".DBF.FPT.U" would result in a filename that ends with ".DBF.FPT.U"

Leonids example shows

`? System.IO.Path.GetExtension(cPath + "MEMOTEST.DBF.U") // result: U`

So that is why with the given Set_MemoExt the result is ".DBF.DBF.FPT.U"

**Comment by leon-ts** [comment]
Guys,
So strange it worked in VO. For VO to open the FPT file for the FILENAME.DBF.U file, the FPT file must be named FILENAME.DBF.FPT.U. For a file with this name to be created, it was necessary to specify MEMOEXT as .DBF.FPT.U when creating the master DBF file. Then MEMOEXT had to be set as .FPT.U before opening that DBF file

Now I like the naming behavior better: if MEMOEXT is specified as .FPT.U, then it should just replace the extension of the DBF file (as Robert wrote:
FILENAME.DBF.U -> FILENAME.DBF.FPT.U
FILENAME.DBF -> FILENAME.FPT.U

I understand that there is a certain contradiction: on the one hand, I am asking to make the behavior like VO, but on the other hand, to make it more correct (not like in VO). The main problem was that, up to this point, X# did not support modifying DBF filename extensions in principle. And now you have implemented it. At the same time, some oddities from VO were not implemented, and this is very good!

**Comment by cpyrgas** [comment]
OK, that's why I said "correct" in quotes, neither behavior was trully "correct"!
So I say let's leave it as it is now, and Leonid will tell us if it's working as he expects when this is released.

**Comment by RobertvanderHulst** [comment]
My guess is that VO treats everything after the first '.'  character as extension. That is why you would need to set the extenstion to DBF.FPT.U. The problem for apps like VO was that by the time they were developed there were no reliable functions in the OS() to return extensions. So the developers had to create their own code.
Even now in .Net core the developers wrote their own code, and they use the last '.' character to find the extension:
https://github.com/dotnet/runtime/blob/09c1a1f7b0c477890b04912d8dd4f742f80faffc/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs

**Comment by leon-ts** [comment]
Guys,
It works well now!
