### ISSUE TITLE
Internal Compiler Error with Type() in FoxPro dialect with /fox2+ enabled

### ISSUE THREAD

**Issue by jpmoschi** [X-Sharp/XSharpPublic#840]
The project run in revision before
Severity	Code	Description	Project	File	Line	Suppression State
Error	XS9999	An internal compiler error has occurred: 'Unexpected value 'TypeExpression' of type 'LanguageService.CodeAnalysis.XSharp.BoundKind'',    at LanguageService.CodeAnalysis.XSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used)	ConsoleApplication1	XSC	1

**Comment by RobertvanderHulst** [comment]
Juan,

Can you share the code of this project ?

Robert

**Comment by jpmoschi** [comment]
> Juan,
> 
> Can you share the code of this project ?
> 
> Robert
here it is. 
It is only clear for my bat i think you only want to rebuild.
[ConsoleApplication1.zip](https://github.com/X-Sharp/XSharpPublic/files/7469336/ConsoleApplication1.zip)

**Comment by cpyrgas** [comment]
Thanks Juan, Robert the problem seems to by the use of Type(), in conjunction with /fox2:

```
// /fox2+
FUNCTION Start() AS VOID
LOCAL pVarId
? Type(pVarId)
// error XS9999: An internal compiler error has occurred: 'Unexpected value 'TypeExpression' of type 'LanguageService.CodeAnalysis.XSharp.BoundKind'',    
```

Btw, Robert, Juan's solution seems to demonstrate an intellisense problem as well: Open the file CodeFIle1.prg, and then try to invoke a tooltip practically anywhere, VS freezes for several seconds (more than 10 in my fast machine) until it unfreezes, but no tooltip is shown,. Can you reproduce this?

**Comment by cpyrgas** [comment]
Confirm fixed
