### ISSUE TITLE
Feature request: Add sub-option to "/vo3": "Demand OVERRIDE or NEW keyword for descendant methods"

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#846]
If there is "All instance methods virtual" (/vo3) option enabled then not only VIRTUAL keyword is needless to be written manually, but OVERRIDE or NEW keywords are needless in descendant methods. And that may seem fine, but there is a problem with this in .Net because of overloads, which were not supported in VO. So now if you change signature of parent method, its descendant method suddenly becomes an overload and not an override-method. That is dangerous because it may still be compiled fine and then work differently.
Yes, you still may write OVERRIDE manually, no one prohibits that, but that would be just a voluntary contract, because those methods, where you forgot to write it, are still vulnerable to a, so to speak, "stealing of parent method".
It would be safe to introduce a new option "Demand OVERRIDE or NEW keyword for descendant methods" which may be toggled only when "All instance methods virtual" (/vo3) is ON. With this option the VIRTUAL attribute would still be added automatically, but if programmer wants to override this method in a descendant class he is obliged to write OVERRIDE or NEW, depending on what he wants, or get a compile error otherwise. Maybe a warning, not an error, but there must be something that draws programmer's attention to a potential problem.
And you may even make this new option applicable only to strict methods and let clipper methods be the same, because there is no such thing as overloading for them.

**Comment by Serggio** [comment]
I've just switched off "All instance methods virtual" (/vo3) option and was surprised that though it demands VIRTUAL for methods which may have descendants, it still doesn't demand OVERRIDE or NEW keywords in descendant methods themselves. Maybe it's something that doesn't work for VO-dialect and it's only Core-dialect which is strict about it?

**Comment by Serggio** [comment]
Oh, my. With "All instance methods virtual" (/vo3) option being off, it compiles strict descendant methods, which do not have explicit OVERRIDE or NEW modificators, as NEW. Don't think it's appropriate. I think OVERRIDE and NEW should be written excplicitely by programmer and it must an error otherwise (if there is a parent method with the same signature).

**Comment by cpyrgas** [comment]
Serggio, we have indeed discussed about this and plan to add an option to make OVERRIDE/NEW modifiers mandatory. It can't be done for this build, but should be available in one of the next ones. The reason why this is not already enforced by default, is compatibility with VO...

**Comment by cpyrgas** [comment]
Can't seem to get the /strict option, I get an error XS2007: Unrecognized option: '/strict'
Do I use the wrong name?

**Comment by RobertvanderHulst** [comment]
Chris,
I have changed the compiler option name from "strict" to "enforcevirtual" because "strict" was way too vague / generic

**Comment by cpyrgas** [comment]
Hmm, isn't that a problem in conjunction with the /vo3 (all methods virtual) option? Let's take both cases separately:

- When /vo3 is disabled, then it works very nicely now, VIRTUAL, NEW and OVERRIDE keywords need to be specified (almost) in the same manner as in c#. But there is an exception, in x# you can override a VIRTUAL method with another method marked as VIRTUAL:

VIRTUAL METHOD Test() // CLASS Parent
VIRTUAL METHOD Test() // CLASS Child

and this compiles with no warnings. If you try to do the same thing in c#:

```
class parent
{
	public virtual void test(){}
}

class child:parent
{
	public virtual void test(){}
}
```

you get warning CS0114: 'child.test()' hides inherited member 'parent.test()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.

maybe that's how x# should work as well, when this new compiler option is enabled?

- When /vo3 is enabled, and that will be the most common scenario for almost all code ported from VO, then there's a controversy, as in this code:

CLASS parent
	METHOD Skata() AS VOID
END CLASS
CLASS child INHERIT parent
	OVERRIDE METHOD Skata() AS VOID
END CLASS

we are now getting an error XS0115: 'Test': no suitable method found to override, while we have implicitly told the compiler to automatically add VIRTUAL for all methods (well, at least those that do not have the explicit NEW or OVERRIDE modifiers). 

So in my opinion the option should not be name /enforcevirtual, but instead something like /enforceoverride and let VIRTUAL still be handled by the /vo3 option. Sergio, I think that's the way you were thinking about it, too, am I right?

**Comment by Serggio** [comment]
> maybe that's how x# should work as well, when this new compiler option is enabled?

I guess, it shouldn't. Without /vo3 it should be as strict as C#.

> Sergio, I think that's the way you were thinking about it, too, am I right?

Yes, when "/vo3" and "/enforcevirtual" are both enabled, method without modificators should be still treated as virtual but derived methods should have NEW or OVERRIDE if the method is strictly typed. If it's a clipper method - everything is the same as it was always: virtual and override are implicit.

**Comment by RobertvanderHulst** [comment]
Ok, this what I suggest:

1.  Rename the new option to 'enforceoverride'
2. When the new option is not enabled then the compiler works as before. So  with /vo3 the compiler makes all instance methods virtual and automatically adds OVERRIDE to overridden methods in subclasses. And without /vo3 the compiler will report  `warning XS0108: 'child.Skata()' hides inherited member 'parent.Skata()'. Use the new keyword if hiding was intended.`
3. When the new option is enabled then the compiler still follows the /vo3 rules and adds 'VIRTUAL' to the method in the parent class (parent.Skata). But it no longer automatically adds OVERRIDE to the method in the child class. In that case the code above will generate the warning: `XS0114: 'child.Skata()' hides inherited member 'parent.Skata()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.

To summarize in a table:
| Vo3 | EnforceOverride | Result |
| --- | --- | --- |
| -| - |  XS0108:  ....  Use the  new keyword if hiding was intended|
| + | - | Compiles without warnings|
| - |+ | XS0108:  .... Use the new keyword if hiding was intended|
|+| + | XS0114: .... add the override keyword. Otherwise add the new keyword.|

**Comment by Serggio** [comment]
Exactly! And all this should be applied to strictly-typed methods only, keeping clipper-methods working as before.

**Comment by cpyrgas** [comment]
Crap, I had used a "bad" word in my small internal test and then forgot to change it when I posted my sample code above! I hope no Greek developer sees the above :)

But yes I agree this is how it should work. Not sure about CLIPPER methods though, there are good arguments for making them behave either way...

**Comment by cpyrgas** [comment]
Robert, when /enforceoverride is DISABLED, the following does not override the method and reports a warning that the child method hides the parent one. This will break a lot of existing code (since this is how it used to work for years now in X#).

Sorry, I missed that previously from your table above, but I think this needs to be reverted, and still allow VIRTUAL keyword to also override the parent class (when /enforceoverride is disabled). Only when /enforceoverride, then the compiler shoudl be stricter/like in c# and OVERRIDE should be required to override the parent method.

```
CLASS Parent
VIRTUAL METHOD Test() AS VOID
END CLASS

CLASS Child INHERIT Parent
VIRTUAL METHOD Test() AS VOID
END CLASS
```

**Comment by Serggio** [comment]
Cpyrgas, I think it's fine, because VIRTUAL is written here deliberately, thus you know what you're doing and really - Child's "test" hides Parent's "test" here, so this should be an error.
The other point is that if you omit VIRTUAL then it should work as it has been working always: implicitly treat Parent's method as virtual and Child's as override.

**Comment by RobertvanderHulst** [comment]
Chris,
Yes, I have seen that too. This also was used a lot in the X# runtime.
I have cleaned up the runtime code and replaced VIRTUAL with OVERRIDE when needed.
But I'll fix the compiler today.
In my words: 
WITHOUT /enforceoverride VIRTUAL means both VIRTUAL and OVERRIDE and the compiler should be smart enough to detect what was meant. 
WITH /enforceoverride VIRTUAL means just VIRTUAL and OVERRIDE MUST be used in subclasses.

**Comment by cpyrgas** [comment]
Robert, agreed.

Serggio, you are right, but the problem is that it's has been working like that for years in X#, more than a dozen years if you include vulcan from which many projects have been ported, so if we made it work differently now (not optionally), we would be breaking A LOT of existing code.

**Comment by cpyrgas** [comment]
Looks pretty good to me, except with one case, with ACCESSes (methods work perfectly), when /vo3 is DISABLED. I am not sure if it's worth further adjusting the compiler for this, but FWIW:

With vo3 disabled (also /enforce override disabled), the following reports only one warning:

warning XS0108: 'Child.Access2' hides inherited member 'Parent.Access2'. Use the new keyword if hiding was intended.

What I would expect, is an error instead, for both of the OVERRIDE ACCESSes, since there's no access to override. With a method instead of an access, the compiler does exactly that, reports an error that there is no method to override.

```
CLASS Parent
	OVERRIDE ACCESS Access1
	RETURN "parent"
	ACCESS Access2
	RETURN "parent"
END CLASS

CLASS Child INHERIT Parent
	OVERRIDE ACCESS Access2
	RETURN "parent"
END CLASS
```

**Comment by VolkmarR** [comment]
I made some tests with the /enforceoverride compiler option, and it worked as expected. Can you give me an estimate, when the checkbox for this switch will be added to project options?

**Comment by RobertvanderHulst** [comment]
Volkmar,
This option is already on the Language page in 2.10:
![image](https://user-images.githubusercontent.com/14240939/153845705-b6bbdd50-849b-455e-883d-37b963fdf848.png)

**Comment by VolkmarR** [comment]
OK. Then I'm doing something wrong. I tried this option and it didn't work. Then i added the /enforceoverride compile switch and i got the correct Compiler message.

**Comment by VolkmarR** [comment]
I created a small test project with this options

![image](https://user-images.githubusercontent.com/9860916/153857517-8984d43c-466f-4594-938f-431c87ed7578.png)

It compiles without warnings and errors. When I add the switch /enforceoverride, then I get the expected error.

![image](https://user-images.githubusercontent.com/9860916/153857659-95d2f4b1-2bbe-4c5a-a9eb-5973651bab8a.png)


[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/8060267/XSharpTests.zip)

**Comment by VolkmarR** [comment]
Maybe the problem is, that the compiler excepts the option /enforceoverride and the flag sets the option /enforcevirtual?

**Comment by RobertvanderHulst** [comment]
Volkmar,
Aargh. That's it. I'll change the project system to set the right flag in the project file.

Robert

**Comment by cpyrgas** [comment]
Original ticked confirmed done
