### ISSUE TITLE
Feature request: Do not generate $Init calls for libraries without INIT procedures for the sake of postponed loading

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#854]
X# generates a hidden method in the main executable project which calls $Init methods from all the referenced assemblies (even if they lack INIT procedures written by programmer) and thus forcing JIT to load them all immediately at the start of application, while it's natural for .Net to load libraries only when they are really needed.
What is proposed to do: if there are no INIT procedures manually written by a programmer, then compiler should skip generation of this early $Init call for this assembly so that it gets loaded only when it is really needed.

**Comment by Serggio** [comment]
There are $Exit calls either. But there is an easy solution: call them only if particular assembly was actually loaded.

**Comment by RobertvanderHulst** [comment]
We are generating these because it forces X# compiled assemblies to be loaded, allowing to create classes in these assemblies to be instantiated with CreateInstance() without actually declaring them.
If we had not one that then you would have to explicitly use these types to force them to be linked in.
I can imagine that we create a compiler option that:
- suppresses the generation of the $Init1() function in libraries when there are no init procedures
- suppresses the call to the $init procedures in the main exe.

The code in the main exe that initializes the runtime state will have to remain there

**Comment by Serggio** [comment]
> CreateInstance()

Now I see. Well, I'll be the first who would suffer if it doesn't work :) But being aware of it I will write some code to ensure the library is loaded before calling CreateInstance. Maybe I'll create a function like CreateInstanceFromLibrary that would accept not only the class name but the library's name either, ensuring the latter to be loaded.

Thank you for the feedback!

**Comment by RobertvanderHulst** [comment]
I have added an experimental switch for this. If you include the compiler option /noinit then the compiler will only created $Init1 methods and $Exit methods when a DLL really has an INIT1 or EXIT procedure.
A Main app that links to this assembly will then also not 'hard link" to this DLL if you are not calling functions or using types from this DLL.
To use this you need to add the /noinit to the additional compiler options slot on the Build page in your VS project

**Comment by Serggio** [comment]
Thank you, Robert!

**Comment by cpyrgas** [comment]
Looks good to me, but will let Serggio test and confirm this with his own code

**Comment by cpyrgas** [comment]
This doesn't seem to work anymore, in the attached solution a library only contains a small class and no INIT functions, but the main app still adds a hard reference to it through $AppInit(), despite using /noinit.

It's not a problem with VS and setting of compiler options, because I get the same behavior in XIDE.

[ConsoleApplication13.zip](https://github.com/X-Sharp/XSharpPublic/files/8008388/ConsoleApplication13.zip)

**Comment by cpyrgas** [comment]
Oh, maybe this is because the library is a VO dialect library, which in turn depends on (runtime) libraries which do have _INIT procedures? And in which case also the libraries need to be compiled with /noinit ?

**Comment by RobertvanderHulst** [comment]
Chris,
The /noinit command line option prevents a library or app from generating the $Init1() function when no init procedures exist. In your example you apply the /noinit to the main app and not to the library.
This is exactly the opposite of how it is supposed to be done.
I have considered to also suppress the call to the $Init1(), $Init2() etc methods in the main app but that would also mean that init procedures would not be called, causing all kind of unwanted side effects. I thought that would be asking for problems.
If you add the /noinit to the library then it works.

**Comment by cpyrgas** [comment]
OK, confirmed fixed!
