### ISSUE TITLE
Compiler 2.10 gives error "String2Psz() and Cast2Psz() are only allowed in a local context"

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#898]
With the new compiler 2.10 we get in the following code the error "String2Psz() and Cast2Psz() are only allowed in a local context".

```
local swinNETRESOURCE as _winNETRESOURCE
local cremotepath  as usual
winNETRESOURCE := MemAlloc( dword(_sizeof(_winNETRESOURCE)) )
swinNETRESOURCE.lpRemoteName  := String2psz( cremotepath ) // ----> error
```

**Comment by RobertvanderHulst** [comment]
Hans Joerg,
This error message is correct.
Since swinNETRESOURCE  is declared AS a VOSTRUCT this means that you could pass this pointer to another location.
But the PSZ allocated with String2Psz() only is valid in the context where it is allocated.
You are not showing the rest of the code, so I do not know if the pointer is indeed passed around.

The safest solution is to replace String2Psz() with StringAlloc() here and call MemFree() on the allocated PSZ when you are done with the VOSTRUCT.

Robert

**Comment by hpetriffer** [comment]
This is the entire code:
```
function FMapDrive (cmapdrive, cremotepath , cuser , cpassword , uOptions, lwithErrormessages)
   local lOk as logic
   local nresult   as dword
   local swinNETRESOURCE as _winNETRESOURCE
   local cError as string
   local nError as dword
   local lpErrorBuf, lpNameBuf as ptr

   lOk := true
   if isNil(cRemotepath)
      cRemotepath:=  ""
   endif

   if isNil(cUser)
cUser :=  ""
endif

   if isNil(cPassword)
cPassword :=  ""
endif

   if isNil(lwithErrorMessages)
lwithErrorMessages :=  true
endif


   if SLen(cMapdrive) == 1
         cMapDrive += ":"
   endif


   if !Empty(cRemotepath)
         swinNETRESOURCE := MemAlloc( dword(_sizeof(_winNETRESOURCE)) ) //X# AO 11/2016
         swinNETRESOURCE.lpRemoteName  := /*X# AO 11/2018*/ String2psz( cRemotepath)
         swinNETRESOURCE.dwScope   := RESOURCE_GLOBALNET
         swinNETRESOURCE.dwType    := RESOURCETYPE_ANY
         swinNETRESOURCE.dwDisplayType  := RESOURCEDISPLAYTYPE_SERVER
         swinNETRESOURCE.dwUsage   := RESOURCEUSAGE_CONNECTABLE
         if !cmapdrive == null_string
             swinNETRESOURCE.lpLocalName := /*X# AO 11/2018*/ String2psz( cmapDrive )
         endif
         swinNETRESOURCE.lpComment    := null_psz //X# AO 11/2016
         swinNETRESOURCE.lpProvider   := null_psz //X# AO 11/2016
         nresult := WNetAddConnection2( swinNETRESOURCE , /*X# AO 11/2018*/ String2psz( cpassword ) , /*X# AO 11/2018*/ String2psz(cuser ) , CONNECT_REDIRECT )
         MemFree( swinNETRESOURCE )
         if nResult != 0
               lOk := false
               if lwithErrorMessages
                     cError := ""
                     if nResult == dword(ERROR_EXTENDED_ERROR)
                           lpErrorBuf := MemAlloc(1025)
                           lpNameBuf := MemAlloc(1025)
                           WNetGetLastError(@nError,lpErrorBuf,1024,lpNameBuf,1024)
                           cError := "("+NTrimSafe(nError) + ") " + PSZ2String(lpErrorBuf)
                           cError += CRLF + PSZ2String(lpNameBuf)	+ CRLF
                           MemFree(lpErrorBuf)
                           MemFree(lpNameBuf)
                     endif
               		MsgErrorRuntime ("Assignment Drive " + CRLF + Typevalue2String(cMapDrive, cTmpRemotePath, cUser) + CRLF + cError + LastWindowsErrorAsText(nResult))
               endif
         endif
   else
         WNetCancelConnection2( /*X# AO 11/2018*/ String2psz(cMapDrive) ,CONNECT_UPDATE_PROFILE , true )
   endif


   return lOk
```

**Comment by RobertvanderHulst** [comment]
Hans Joerg,

We have added this error message because of some bug reports by others where they were allocating PSZs with String2Psz and did not realize that the PSZ would be released automatically. So now we only allow assigning a PSZ allocated with String2Psz() to a LOCAL or to a field of a VOSTRUCT declared with IS.

In this code there is no problem, but it is very difficult for the compiler to "know" that.
To solve this I would declare swinNETRESOURCE  as follows (change AS to IS)

`local swinNETRESOURCE IS _winNETRESOURCE`

And then you can remove the lines where swinNETRESOURCE  is allocated and freed and change the line 

`nresult := WNetAddConnection2( swinNETRESOURCE  , ....`

to 

`nresult := WNetAddConnection2( @swinNETRESOURCE  , ....`

That should resolve the issue.

**Comment by cpyrgas** [comment]
Robert, after seeing more cases, I think this error should be turned into a warning instead, because it is breaking in many cases potentially incorrect but in fact correct code. As you said, assigning String2Psz() on a structure declared with AS is currently not allowed, because this pointer can be passed outside. But in the same way, when using directly a pointer, then there is no error message:

```
LOCAL p AS PTR
p := String2Psz("abc") // no error reported here
RETURN p
```

so this might be misleading that it's ok to use a pointer (or PSZ) like that, but it's a problem using a VOSTRUCT instead.

I agree it can help finding potential problems though, so having it at least as a warning is good I think. I was thinking that maybe it should be kept as an error in stuff like assigning String2Psz() on a GLOBAL, but then again if the developer knows what they are doing and are using that value in the global locally only, this can be perfectly valid as well, just very bad coding practice. But that's up to the developer to decide what's good and bad, I think the compiler should only "suggest" that with a warning, not an error.

On the other hand, currently this does not report an error or warning, if it's possible it would be nice to make the compiler report a warning on that, too:

```
FUNCTION GetApsz() AS PSZ
RETURN String2Psz("Least lived PSZ ever") // this is allowed currently
```

**Comment by RobertvanderHulst** [comment]
I will see what I can do.

**Comment by cpyrgas** [comment]
Nice, and I like the updated warning text
