### ISSUE TITLE
XBase++: The REQUEST statement

### ISSUE THREAD

**Issue by Danila2903** [X-Sharp/XSharpPublic#929]
In our projects we often use REQUEST statement (https://doc.alaska-software.com/content/stmt_xpplrm_request.html). It lets us link function, which we will be able to call dynamically during runtime.
I didn't find any information about it in XSharp documentation. Are you going to implement it in future updates?

**Comment by RobertvanderHulst** [comment]
If a function is part of an assembly or project that is referenced by your code, then these functions are automatically available at runtime, also when called from a macro.
So there is no need for the REQUEST statement.
We will add a REQUEST UDC in the next build so your code will compile unchanged.

**Comment by Danila2903** [comment]
@RobertvanderHulst Thank you very much! We're looking forward to next build

**Comment by Danila2903** [comment]
@RobertvanderHulst
In documentation you mention, that XSharp doesn't support commands SAY, GET, etc (https://www.xsharp.eu/help/cmd_cat_terminal.html)
1) I couldn't build one of examples from documentation: https://www.xsharp.eu/help/command_create_from.html  
```
FUNCTION Start()
 CreateDatabase("newfile")
 
FUNCTION CreateDatabase(cNewDbf)
 // Create empty structure-extended file
 CREATE tmpext
 USE tmpext
 lMore := TRUE
 DO WHILE lMore
         // Input new field definitions
         APPEND BLANK
         CLEAR
         @ 5, 0 SAY "Name.....:  " GET Field_Name
         @ 6, 0 SAY "Type.....:  " GET Field_Type
         @ 7, 0 SAY "Length...:  " GET Field_Len
         @ 8, 0 SAY "Decimals.:  " GET Field_Dec
         READ
         lMore := (!EMPTY(Field_Name))
 ENDDO
 
 // Remove all blank records
 DELETE ALL FOR EMPTY(Field_Name)
 PACK
 CLOSE
 
 // Create new database file
 CREATE (cNewDbf) FROM tmpext        
 ERASE tmpext.dbf
```
Is it possible to be compiled?
2) What should we use instead of these commands?

**Comment by RobertvanderHulst** [comment]
Danila,

This example should never have made it into the docs.

We used a tool to "grab" the contents of the Visual Objects documentation and add it to our documentation.
We kept the Computer Associates copyright, to make sure that they would not send a lawyer after us for this (but to be honest, nobody inside Computer Associates knows about Visual Objects anymore).

But actually this code did not work in Visual Objects as well for many years, because @ SAY .. GET was dropped from Visual Objects in the 90's.
I'll scan the documentation for examples like this and will remove them.

**Comment by cpyrgas** [comment]
...having said that, it might still be possible to compile and use @ SAY commands, with a bit of preprocessor help and a clever library that translates such commands to windows forms controls :)

**Comment by Danila2903** [comment]
@cpyrgas thank you :)
The question is a bit off topic, but can I combine c# and XBase++ code in one project? I've tried to call methods of Console and MessageBox classes and they work, but I need to use XBase++ syntax. But I still haven't figured out how to create new objects (e.g. Form, Button).
I still compile project with xsc.exe. Will I be able to compine .cs and .prg file if I try Visual Studio extension?

**Comment by cpyrgas** [comment]
You cannot combine code from different languages in the same project (executable or dll), but it's no problem at all combining separate dlls and executable written in different languages.

In order to create forms etc, you will need to add references to the appropriate system dlls, namely System.WIndows.Forms and System.Drawing first. But all this will be very complicated, especially if you are not yet familiar with windows forms in .Net. I'd suggest just using VS for that, create a new X# Windows Forms project and go from there.

**Comment by cpyrgas** [comment]
Confirmed fixed
