### ISSUE TITLE
Implicit cast does not give an error when assigning a wrong class

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#961]
In X# it is currently possible to assign objects to other variables even if the type of the variable does not match.

```
function Start() as void strict
local x as object
    local y as BaseClass2
    x := BaseClass1{}
    
    y := (BaseClass2)x
    y.Test()
return

class BaseClass1
    method Test() as void
    console.WriteLine("BaseClass1")
    return
end class

class BaseClass2 
    method Test() as void
    console.WriteLine("BaseClass2")
    return
end class
```
X#
![image](https://user-images.githubusercontent.com/20905638/154102826-f94b693f-9e50-47b1-ac86-233a50855e0e.png)
 
C#
 ![image](https://user-images.githubusercontent.com/20905638/154102857-9adbf56f-a1e5-4e30-8a54-6e0fc365696d.png)

Here you can assign e.g. x to the variable y without getting an error.Whether you cast with (BaseClass2) or not makes no difference. Even a string can be assigned to y.  In this case then the output of the method is not done....

It seems that if you disable "Allow late binding" and disable "Implicit casts and conversions" the castclass IL instruction is generated

X# Version 2.10.3

**Comment by cpyrgas** [comment]
I seem to be still getting the wrong behavior and C830 is failing, but maybe it's just that the new compiler has not been updated?

**Comment by cpyrgas** [comment]
OK, I think the compiler has been updated now. But I'm still seeing the original problem. Please note that the original code, which I had included in the C830 test was:

```
LOCAL x AS OBJECT
LOCAL y AS BaseClass2
x := BaseClass1{}
y := (BaseClass2)x
```

When this is compiled with either /lb+ or /vo7+ enabled, then there's still no runtime exception in the cast, while there should be one. When /lb and /vo7 are both disabled, then I do get a System.InvalidCastException as expected.

Robert, I see you have modified the above test code, by changing 

y := (BaseClass2)x

with

y := x

and this now indeed throws an exception as expected, but this is different to the original report. Hope we're not seeing different things due to different compiler binaries!

**Comment by RobertvanderHulst** [comment]
There was indeed a problem when the explicit cast was used. The compiler now outputs `castclass BaseClass2` both with and without the cast in the code

**Comment by cpyrgas** [comment]
I'm afraid there's still no runtime error when the original sample is compiled with /lb+ and/or /vo7+

**Comment by cpyrgas** [comment]
I tried also with today's https://github.com/X-Sharp/XSharpDev/actions/runs/1885058225, but still C830 fails at runtime and indeed the original sample does not produce an exception on the invalid cast, when /lb+ or /vo7+ are enabled

**Comment by cpyrgas** [comment]
Confirmed fixed
