### ISSUE TITLE
xBase: Strange behavior of the TEXT statement

### ISSUE THREAD

**Issue by kpa174** [X-Sharp/XSharpPublic#977]
**Describe the bug**
[On the one hand, the documentation says that the TEXT statement is not supported.](https://www.xsharp.eu/help/cmd_cat_terminal.html)

[But on the other hand, there is a description of this statement.](https://www.xsharp.eu/help/command_text.html)

Perhaps it only works in FoxPro dialect. At least not for xBase:
`error XS0103: The name 'TEXT' does not exist in the current context`

We desperately need support for this operator, [a description of which can be found here](https://doc.alaska-software.com/content/cmd_xppfcref_text.html)

However, we use only the second version of the syntax, we do not need the first one.

```
// Unnecessary syntax
TEXT [TO PRINTER] | [TO FILE <cFilename>]
   <Text>
ENDTEXT
```
```
// Required syntax
TEXT [INTO <variable> [TRIMMED]] |
     [INTO <variable> WRAP] |
     [INTO <variable> WRAP <cLineBreak> [TRIMMED]]
   <Text>
ENDTEXT
```
**To Reproduce**
```
TEXT
    qqqqqqqqqqqqqqqqqqqq
ENDTEXT
```
**Expected behavior**
```
    qqqqqqqqqqqqqqqqqqqq
```

**Additional context**
X# Compiler version 2.10.0.3 (release)

**Comment by kpa174** [comment]
By the way, the TEXT statement is implemented in xBase at the preprocessor level.

**test.prg**
```
  TEXT INTO cSql WRAP
    select sum(SALD)
      from ibs.accfil    
    where ACC_ID=:nAccId and TYPE=:nType
      and D_RECO>=:d1 and D_RECO<=:d2   
  ENDTEXT
```
**test.ppo**
```
cSql := "    select sum(SALD)" + CHR(13)+CHR(10)
cSql += "      from ibs.accfil    " + CHR(13)+CHR(10)
cSql += "    where ACC_ID=:nAccId and TYPE=:nType" + CHR(13)+CHR(10)
cSql += "      and D_RECO>=:d1 and D_RECO<=:d2   " + CHR(13)+CHR(10)
```

**Comment by RobertvanderHulst** [comment]
Peter,
You are right. TEXT .. ENDTEXT is handled for FoxPro only and it is handled in the compiler.
We were not aware of the Xbase++ implementation.
I just checked and there is also a Harbour implementation. And it is again difference

We are processing this in the compiler at this moment because FoxPro allows embedded expressions in the TEXT .. ENDTEXT. We are converting the text body to an interpolated string to handle this.

### XBase ++ syntax:
```
TEXT [TO PRINTER] | [TO FILE <cFilename>] 
   <Text> 
ENDTEXT 
```

or  

```
TEXT [INTO <variable> [TRIMMED]] | 
     [INTO <variable> WRAP] | 
     [INTO <variable> WRAP <cLineBreak> [TRIMMED]] 
   <Text> 
ENDTEXT 
```


### FoxPro syntax:
```
TEXT [TO VarName [ADDITIVE] [TEXTMERGE] [NOSHOW] [FLAGS nValue] [PRETEXT eExpression]]
      TextLines
ENDTEXT
```

### Harbour syntax:
```
TEXT [TO PRINTER] | [TO FILE <cFilename>] 
   <Text> 
ENDTEXT 
```
but the Harbour docs also show UDC's that support
```
TEXT INTO <v>
   <Text> 
ENDTEXT 
```
or
```
TEXT TO VAR
   <Text> 
ENDTEXT 
```
Harbour translates TEXT to `#pragma __text` and also has alternatives `#pragma __stream`  and `#pragma __cstream` (that last one accepts escaped characters  such as `\r` and `\n`

We'll look into this and we will see if we can add TEXT .. ENDTEXT support in the General dialect and the specific implementations in the various dialects.

**Comment by kpa174** [comment]
> We'll look into this and we will see if we can add TEXT .. ENDTEXT support in the General dialect and the specific implementations in the various dialects.

Thanks Robert, hopefully.

**Comment by cpyrgas** [comment]
Confirmed fixed
