### ISSUE TITLE
Cannot use indexing with PSZs

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#98]
Following compiles and runs as expected in VO but reports a compiler error in X#

```
FUNCTION Start() AS VOID
	LOCAL p AS PSZ
	LOCAL i AS DWORD
//	 prints 49,50,51 in VO
	p := String2Psz("123")
	FOR i := 1 UPTO 3
		// error XS0021: Cannot apply indexing with [] to an expression of type 'XSharp.__Psz'
	    ? p[i]
	NEXT
RETURN
```

**Comment by cpyrgas** [comment]
The compiler error is fixed now (it was a typo, see https://github.com/X-Sharp/XSharpPublic/commit/13fb20cb067ceb2a7df5e24428ed45d01927f98d), but there's still a problem, when /az is disabled when running the sample code it runs fine, but when /az is enabled, PSZ elements get offset by one. I think the /az option should not have an effect on PSZ indexing.

**Comment by RobertvanderHulst** [comment]
Chris,
PSZ Indexers are 1 based in the VO dialect and 0 based in the Vulcan dialect. This is to be compatible with Vulcan.

**Comment by cpyrgas** [comment]
Robert,
Yes, but it is also /az compiler option that play a role as well. Run the above sample two times, both in VO dialect, first time with /az+ and second time with /az-, you will get different results.

**Comment by RobertvanderHulst** [comment]
Chris,
That is correct there are different results. And this is no purpose. VO uses 1 based PSZ indexers.
So with the dialect VO and /az+ then looping from 1 to 3 will not subtract 1 from the index so it skips the first element and reads the elements 2, 3 and 4. With /az- (the default) then 1 is subtracted and the elements 1,2 and 3 are read.

If you compile in Vulcan mode then the /az option does not make a difference for PSZ indices because Vulcan (incorrectly) did not support 1 based PSZ indices. 
So the code should either:
- use the VO dialect, /az- and loop from 1 to 3
- use the VO Dialect, /az+ and loop from 0 to 2
- use the Vulcan dialect and loop from 0 to 2 for /az+ and /az-

**Comment by cpyrgas** [comment]
But why does /az makes any difference? In my opinion it should not. /az+ does not make a difference when referencing indexed properties, it only makes a difference in array elements. In this sample, p[i] is not accessing an array element, what it does is pretty much the same as an indexer, for example cString[i] to access a char within a string and /az does not have any influence on that. I think it shouldn't also in our case (accessing a psz char).

**Comment by RobertvanderHulst** [comment]
Chris,
Ok, now I understand what you want.

I will make the PSZ indexed properties independent of the /az option. And for VO the property will then be 1 based and for Vulcan zero based.

Robert
