### ISSUE TITLE
Issues with the "Navigation Bar" in Visual Studio 2022 and version 2.11.0.1

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#995]
We have encountered some minor problems when navigating in code with the "Navigation Bar".
- If you open a new file (in our case Test1->TestClass), then the navigation bar is empty. You have to click in another line of the file
![image](https://user-images.githubusercontent.com/20905638/158805771-5103df10-0143-4246-8522-5a58c0ab9252.png)
- Sometimes, when switching between files several times by selecting a different method, the field of methods is displayed empty or the wrong method is displayed in gray. The same thing happens wenn you navigate inside the code between files with "Go to definition"
![image](https://user-images.githubusercontent.com/20905638/158805677-9e6baf69-36e4-4be6-87dc-5e99225856b8.png)
 
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/8285037/XSharpTests.zip)

**Comment by hpetriffer** [comment]
Antoher problem it seems when we have defined a local function or procedure
```
public partial class TestClass

	public method TestMethod2() as void
		
		local function Test() as void
			self:TestMethod3()
		end function
		
		Test() // -> Click here
		return
		
	public method TestMethod4() as void
		// Search 
		return
end class
```
In this case inside if you select a line after end function (inside the method TestMethod2, you get allways the following "Navigation bar"
![image](https://user-images.githubusercontent.com/20905638/158813287-c0214c94-7583-44d7-8a54-4e0337af4ecd.png)

**Comment by hpetriffer** [comment]
@RobertvanderHulst are you able to reproduce this?

**Comment by cpyrgas** [comment]
@hpetriffer I can confirm both the problems with needing to click in the editor otherwise the bar is empty and the one with always showing "Global scope" with your code above.

**Comment by RobertvanderHulst** [comment]
These were 2 completely different and not related problems, but I have found and fixed them both.

**Comment by cpyrgas** [comment]
The problem with LOCAL FUNCTION is fixed, but the first problem with the incorrect navigation bar contents when first showing a file, is only partially fixed: 

When opening a solution, usually there are plenty files automatically opened, since they were open in the previous session. When initially showing any of those files (with the caret being automatically somewhere in the middle of the file), the left part pf the navigation bar always shows "Global Scope" and the right hand side shown an incorrect entity, until moving the caret, when it shows the correct contents:

![VS_navigation_bar](https://user-images.githubusercontent.com/14542129/165730773-9f26c34f-36b2-4093-affc-27777976e056.png)

Here's a small sample project showing this behavior, but it can be reproduced with any solution:

[WindowsFormsApplication33.zip](https://github.com/X-Sharp/XSharpPublic/files/8581797/WindowsFormsApplication33.zip)

**Comment by cpyrgas** [comment]
Confirmed fixed
